hamlet-io/engine-plugin-aws

aws/components/mobileapp/state.ftl
AWS plugin changes to allow for https://github.com/codeontap/gen3/pull/1272 
Allows for the export method setting to be defined to handle different provisioning profiles
Tested through an automated build and deploy 
None
=> <feature> allow to define export method

aws/components/db/setup.ftl, aws/components/db/state.ftl
Add the ability for the Instance version to include a minor version indication, initially for MySQL.
=> <feature> rds minor version support

aws/components/adaptor/setup.ftl, aws/components/adaptor/state.ftl
AWS implementation of the adaptor component. This should work from the shared provider but doesn't seem to be working at the moment. Allows for anyone to define their own component using the existing macros that we offer for building components
=> <feature> Adapator component

aws/components/userpool/id.ftl, aws/components/userpool/setup.ftl, aws/components/userpool/state.ftl, aws/services/cognito/id.ftl, aws/services/cognito/resource.ftl
AWS implementation of https://github.com/hamlet-io/engine/pull/1301 
Moves all configuration from Cli into cloudformation as it now supports everything we currently have in place for userpools
Enables advanced security services to provide stronger identity management
Server to server cognito authentication is useful in products where a service needs to call an API. This interaction can now use the same userpool that is used for users themselves rather than having to implement another auth method 
Refactor: Cloudformation configuration is easier to understand and manage change
Tested locally with a new deployment 
- [X ] None of the above.
=> <feature>Add Userpool resources and CFN support

aws/inputsources/shared/masterdata.ftl
Upgrade to a supported version of nodejs.
Current version no longer supported for new functions by AWS
=> <fix> Update version of nodejs for cf redirect handler

aws/components/network/state.ftl
The network component shouldn't assume that the "Operations" segment object is present in the segment.
Ran into this issue with the Azure provider where it doesn't exist because its not in Shared masterdata. It's only available to the AWS provider because Flow Logs are implemented in the AWS provider masterdata, within the Operations object. If they were to be moved/updated, then this check would fail as it has with Azure.
Tested the same check in the Azure provider.
=> Refactor - VPC Flow Log Check

aws/components/userpool/setup.ftl
Basic configuration does not require API version so make it optional.
Avoid having to provide unnecessary configuration.
=> refactor: API version optional for facebook IdP

aws/components/s3/setup.ftl
Add support for 404 errors from S3 to cloudfront 
Makes working with cloudfront easier to troubleshoot with support for 404 and 403 errors 
Tested in template generation
=> feat(s3): cdn list support for s3

aws/components/userpool/setup.ftl
For some identity providers on a userpool, the provider name that can be used is fixed so ensure the correct name has been used.
Avoid obscure errors generated when the correct provider name is not used.
=> feat: Enhanced checks on userpool auth provider names

aws/components/ecs/state.ftl
Adds state attributes to support running fargate tasks or running tasks with the awsvpc network mode 
Allows running tasks using the fargate engine which removes the need for ec2 instances
=> feat(ecs): fargate run task state support

aws/components/externalnetwork/id.ftl, aws/components/externalnetwork/setup.ftl, aws/components/externalnetwork/state.ftl, aws/components/gateway/id.ftl, aws/components/gateway/setup.ftl, aws/components/gateway/state.ftl, aws/services/service.ftl, aws/services/transitgateway/resource.ftl, aws/services/vpngateway/id.ftl, aws/services/vpngateway/resource.ftl
AWS implementation of https://github.com/hamlet-io/engine/pull/1328 
Initial external network implementation is for an external network with VPN connection to a network or router
Supports VPN based connections to AWS VPC services
Tested in local deployment
=> feat(externalnetwork): vpn support for external networks

aws/components/privateservice/id.ftl, aws/components/privateservice/setup.ftl, aws/components/privateservice/state.ftl, aws/services/vpc/id.ftl, aws/services/vpc/resource.ftl
Intial aws implementation of the private service component introduced in https://github.com/hamlet-io/engine/pull/1330 
This allows for services provisioned within an AWS VPC to be shared with another VPC using private networking rather than IP restrictions over the internet
Tested locally on active deployment
=> feat(privateservice): initial implementation

aws/components/gateway/setup.ftl
Adds subset check for gateway resources 
Fixes issue where resources were being provisioned in other subsets
Tested locally on active deployment
=> fix(gateway): subset control for CFN resources

aws/components/router/state.ftl
Include core id in the formatting of the resourceShare for routers
Ensures that all resources we deploy are unique 
Tested locally
=> fix(router): fix id generation for resourceShare

aws/components/apigateway/setup.ftl, aws/components/lambda/setup.ftl
In order to permit stacks to be rolled back successfully on error, don't delete previous config files until the stack update has completed successfully.
Also fix a minor bug in the legacy documentation bucket cleanup.
Support stack rollback
Local generation of templates
=> refactor: API Gateway and Lambda S3 config file management

aws/components/externalnetwork/setup.ftl, aws/components/gateway/setup.ftl, aws/services/vpngateway/resource.ftl
AWS implementation of https://github.com/hamlet-io/engine/pull/1339 
Uses an epilogue and cli command to apply the changes as they aren't available via cloudformation.
IPSec VPN connecitons often require specific configuration to align with network devices and security recommendation. This allows for strict control over the vpn connection options
=> feat(externalnetwork+gateway): vpn gateway configuration options

test/run_aws_template_tests.sh
Fix typo.
There was a typo. I fixed it.
Tested mrkdir wasn't a thing. It wasn't a thing.
=> fix(tests): mkdir not mrkdir

aws/components/ecs/setup.ftl
Default Inbound ports on ECS tasks when there aren't any ports
Fix for ecs tasks or services which don't expose any ports
Tested locally
=> fix(ecs): combine inbound ports

aws/services/ssm/id.ftl, aws/services/ssm/policy.ftl
Adds support at the component level for the console changes introduced in https://github.com/hamlet-io/engine/pull/1356 
Allows for the CMK for console access to be an externally defined or independent key 
Tested locally
=> feat(ssm): supports the use of a dedicated CMK for console access

aws/components/bastion/setup.ftl
Include networkProfile in bastion links security groups
It should be included
Tested locally
=> fix(bastion): networkprofile for bastion links

aws/components/userpool/setup.ftl, aws/services/cognito/resource.ftl
Adds supports for email verification type - code or link. All verification message properties are moved to VerificationMessageTemplate object.
To support a verification email for Cognito with a link instead of code. 
=> feature(cognito): support VerificationMessageTemplate

aws/components/apigateway/setup.ftl, aws/components/bastion/setup.ftl, aws/components/computecluster/setup.ftl, aws/components/datafeed/setup.ftl, aws/components/datafeed/state.ftl, aws/components/ec2/setup.ftl, aws/components/ecs/setup.ftl, aws/components/es/setup.ftl, aws/components/lambda/setup.ftl, aws/components/mobilenotifier/setup.ftl, aws/components/network/setup.ftl, aws/services/cw/resource.ftl
AWS implementation of https://github.com/hamlet-io/engine/pull/1355 
- Adds a collection of macros for managing cloud watch log subscriptions using network profiles and links 
- Components which support receiving logs should be configured with an outbound role `logwatcher` this role has two properties 
- `Destination` - The arn of the log forwarding endpoint supported by [cloudwatch log subscriptions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-subscriptionfilter.html#cfn-cwl-subscriptionfilter-rolearn) 
- `Policy` - The IAM policy required for the log subscription to invoke the destination 
- Updates all components with log groups currently implemented to support log subscriptions 
In this PR we now create the subscription from the component sending …
=> Log forwarding for all

aws/inputsources/shared/masterdata.ftl, aws/masterData.json, aws/resourcelabels/resourcelabel.ftl
Add resource labels to the AWS plugin as part of the support for https://github.com/hamlet-io/engine/pull/1362 
Allows resources to be labelled for categorisation of resources for deployments or documentation
Tested locally
=> feat: resource labels

aws/components/filetransfer/id.ftl, aws/components/filetransfer/setup.ftl, aws/components/filetransfer/state.ftl, aws/components/user/setup.ftl, aws/components/user/state.ftl, aws/services/cw/resource.ftl, aws/services/service.ftl, aws/services/transfer/id.ftl, aws/services/transfer/resource.ftl, awstest/provider.ftl, awstest/scenarios/filetransfer.ftl
AWS implementation of https://github.com/hamlet-io/engine/pull/1369 
Adds the following 
- Services for the AWS Transfer family ( https://aws.amazon.com/aws-transfer-family/ ) 
- Component for file transfer based on the AWS Transfer family 
- Public Key support for the user component - allowing for multiple public keys to be configured for a user 
- Public and private support for SFTP gateway using EIP's and Security groups 
To Support file transfer integration with services that do not support cloud provider integration
- executor-bash : https://github.com/hamlet-io/executor-bash/pull/76
- engine: https://github.com/hamlet-io/engine/pull/1369
- engine-plugin-aws: https://github.com/hamlet-io/engine-plugin-aws/pull/108
- [X ] None of the above.
=> Filetransfer service

awstest/provider.ftl, awstest/scenarios/apigateway.ftl, awstest/scenarios/s3.ftl
Add basic tests for apigateway and s3
Supporting some basic tests and mock components for our standard serivces
Tested locally and used the tests
=> chore(awstest): add tests for apigateway and s3

aws/resourcelabels/resourcelabel.ftl
include the pregeneration subnet for application level iam resources
some iam resources rely on the tasks completed in the pregeneration step to be created
Tested locally
=> fix(resourcelables): add pregeneration subset to iam resource label

aws/services/transfer/resource.ftl
Minor fix to security policy parameter for aws transfer server
Deployment via cloudformation failing
Tested locally
=> fix(transfer): security policy name property

aws/components/filetransfer/setup.ftl
Add security group rules based on links for the filetransfer component
Missed in initial implementation 
tested locally
=> fix(filetransfer): add support for security group updates using links

aws/services/ecs/resource.ftl
AWS implementation of https://github.com/hamlet-io/engine/pull/1382 
Allows for container health in ECS to be determined by docker health check scripts
Tested on local deployment 
Requires: https://github.com/hamlet-io/engine/pull/1382
=> feat(ecs): docker based health check support

aws/components/apigateway/setup.ftl, aws/components/apigateway/state.ftl, aws/services/apigateway/resource.ftl
Implements hamlet-io/engine#1376 on the `apigateway` component. This is server-side throttling to protect the backend - it is not client-side throttling.
* Throttling defined at 3 independent levels: the whole API (aka defaults), the stage (overwriting any defaults) and individual methods (overwriting any of the others that would have applied to those methods)
* Throttling can be defined at two levels:
* the stage
* On a pattern, which implements the throttling on matching methods
Example `apigw.json` shows the following:
* stage level throttling is set to a burst of 5000, and a rate of 800
* Any methods patching the regex path `/.*/search` with a verb of `post` will be throttled to a burst of 1000 and rate of 300.
**Numbers are for example only, they are not appropriate throttle …
=> Enable throttling apigatway at api, stage and method levels

aws/components/apigateway/setup.ftl
Support situation where no method specific config has been provided.
It is common for no method specific config to be provided.
=> fix: Allow for no patterns in apigw.json

aws/services/waf/resource.ftl
* allow for handling WAF Conditions of rules that do not have tuples - such as Rate Limit Rules
* During WAF ACL creation, dynamically build the rules for Rate Limiting the IPAddressGroup's defined in the solution
* Various updates to WAF ACL & Rule creation macros to handle RateLimitRules
Would like to be able to control the rate at which an APIGateway behind a WAF can be hit.
Local template generation and deployment
=> Allow for Configuration of WAF Rate Limit Rules

aws/components/apigateway/setup.ftl
Tests for content need to provide an empty value of no content is provided to check.
Prevent freemarker exceptions.
=> fix: Default throttling checks

aws/components/adaptor/setup.ftl, aws/components/computecluster/setup.ftl, aws/components/contentnode/setup.ftl, aws/components/dataset/state.ftl, aws/components/lambda/setup.ftl, aws/components/mobileapp/setup.ftl
Implement additional build reference scopes
See https://github.com/hamlet-io/executor-bash/pull/95 for background.
Local Deployment
=> feat: "account" and fixed build scope

aws/components/globaldb/setup.ftl, aws/components/globaldb/state.ftl
Remove forcing of sortKey if defined. Tidy up inclusion and use of sortKey in the state.
Permit developer choice of sortKey name. 
=> fix: globaldb sortKey logic

aws/components/adaptor/state.ftl, aws/components/apigateway/setup.ftl, aws/components/bastion/setup.ftl, aws/components/contenthub/state.ftl, aws/components/contentnode/state.ftl, aws/components/datapipeline/setup.ftl, aws/components/dataset/state.ftl, aws/components/db/setup.ftl, aws/components/ec2/setup.ftl, aws/components/ecs/setup.ftl, aws/components/es/setup.ftl, aws/components/es/state.ftl, aws/components/gateway/setup.ftl, aws/components/lb/setup.ftl, aws/components/lb/state.ftl, aws/components/mobileapp/state.ftl, aws/components/userpool/setup.ftl, aws/components/userpool/state.ftl, aws/deploymentframeworks/cf/output.ftl, aws/services/autoscaling/resource.ftl, aws/services/resource.ftl
Change all usage of "COT" to "Hamlet".
Tidy up activity to align messaging with renaming of the framework.
Should only be merged AFTER
=> refactor: switch COT to Hamlet

aws/services/ecs/resource.ftl
AWS implementation of https://github.com/hamlet-io/engine/pull/1431 
Allows for container ulimits to be modified as part of the task definition 
Tested locally on active deployment
=> feat(ecs): adds support for ulimits on tasks

awstest/inputsources/shared/blueprint.ftl, awstest/provider.ftl, awstest/scenarios/apigateway/scenario.ftl, awstest/scenarios/db/scenario.ftl, awstest/scenarios/filetransfer/scenario.ftl, awstest/scenarios/lb/scenario.ftl, awstest/scenarios/s3/scenario.ftl
Aligns the test scenarios with https://github.com/hamlet-io/engine/pull/1439 
Allows for scenarios to be loaded and configured as part of blueprints 
Tested locally
=> refactor: align testing scenarios with new format

awstest/scenarios/apigateway/scenario.ftl, awstest/scenarios/db/scenario.ftl, awstest/scenarios/filetransfer/scenario.ftl, awstest/scenarios/lb/scenario.ftl, awstest/scenarios/s3/scenario.ftl
Minor fixes to align with some additional changes in https://github.com/hamlet-io/engine/pull/1439 which removed required parameters for scenarios and allows scenario designers to set their own macro parameters
Removing explicit parameters removes the need so set a specific parameter and allows for flexibility in scenario design
Tested locally
=> fix: align testcases with scenerios config

aws/components/ecs/setup.ftl
A minor fix for ECS containers inbound ports.
Tested locally
=> fix: inbounPorts for containers

awstest/inputsources/shared/blueprint.ftl, awstest/modules/apigateway/module.ftl, awstest/modules/db/module.ftl, awstest/modules/filetransfer/module.ftl, awstest/modules/lb/module.ftl, awstest/modules/s3/module.ftl, awstest/provider.ftl
AWS implementation of https://github.com/hamlet-io/engine/pull/1448 
Better understanding of the concept 
Tested using awstest suite
=> refacotor: align with scenario rename to module

aws/components/lb/setup.ftl
Include the baseline encryption key in the LB steup process to allow for it to be used as part of log streaming
Template generation was failing WAF logs are enabled and forwarding to an encrypted Ops data Bucket
Tested locally
=> fix(lb): fix logging setup process

aws/services/amazonmq/id.ftl, aws/services/amazonmq/resource.ftl, aws/services/service.ftl
Adds support for amazonmq with a focus on implementing the requirements for RabbitMQ 
https://aws.amazon.com/blogs/aws/amazon-mq-update-new-rabbitmq-message-broker-service/ 
This allows us to use the cloud providers offering of a highly available cluster service without have to rely on our own container implementations
Tested locally
=> feat(amazonmq): add support for amazonmq as a service

aws/components/baseline/setup.ftl, aws/components/datafeed/id.ftl, aws/components/s3/setup.ftl
* Updates the description for provider-specific `datafeed` attribute `aws:WAFLogFeed`
Current wording for this attribute suggests it sets up configuration unique to WAF. Whilst this isn't incorrect, it really only enforces a naming convention. I wanted to provide clarity around this, however minor.
n/a
=> Update to Datafeed aws:WAFLogFeed Attr Description

aws/inputsources/shared/masterdata.ftl
Add a description to the api gateway service role.
The description needs to match what AWS expect.
=> fix: add description for API Gateway service role

aws/components/datafeed/setup.ftl, aws/modules/consolidatelogs/module.ftl
Minor fixes to align with the actual logic required for S3  destinations in the datafeed
had the wrong variables in the wrong places 
Tested locally
=> fix(datafeed): encryption logic and disable backup

awstest/modules/s3/module.ftl
Add basic testing for S3 notifications on S3 buckets
Testing for #176  
Run locally
=> chore(s3): add testing for s3 notifications

aws/components/ecs/setup.ftl
- Force cluster replacement on update when managed termination is enabled for EC2 instances
- Adds an empty prologue script to try and flush out the current prolgue scripts which have been saved to cmdb's at the moment they are executed if present and using the old CMDB format 
When using managed scaling for ECS ( which is part of the capacity provider service ) ec2 instances must have scale in protection enabled, this ensures that  instances which are running active tasks aren't included aren't terminated. However when scale in protection is enabled it is also applied during cloudformation updates which trigger scaling activities themsevles. Since they wait for the desired count to reach whats specified in the cloudformation update this leaves the instances in a hung state. 
So instead …
=> fix(ecs): handle scale in protection during updates

aws/components/baseline/state.ftl, aws/components/network/setup.ftl, aws/components/network/state.ftl, aws/modules/consolidatelogs/module.ftl, aws/services/vpc/resource.ftl
- aws implementation of https://github.com/hamlet-io/engine/pull/1482
- Adds a network log for for all network flows to the logconsolidator module 
- Include ARN and other S3 attributes on baseline state to support links to baseline data component 
Allows for greater control over how flow logs are created and where they can be stored 
Tested locally and on development deployment
=> User defined network flow logs

aws/components/ecs/setup.ftl
Always replace ec2 instances in an ecs cluster when managed termination is enabled
When scale in protection is enabled on the autoscaling group as part of ecs capacity provider scaling, and a scaling event happens during the cloudformation updates ( to replace instances, or update configuration ) the scale in protection stops the cloudformation update from going through. 
If a rolling update is performed and a rollback is required then scale in protection enabled on the new instances stops the roll back from happening as well. 
Forcing the replacement of the cluster on each update and requiring the deployment of a new cluster makes this process safer and will ensure instances are removed as required 
Tested locally and on active deployments
=> fix(ecs): require replacement for capacity provider scaling

aws/components/apigateway/setup.ftl, aws/components/lambda/state.ftl, aws/components/mobilenotifier/state.ftl, aws/inputsources/composite/stackoutput.ftl, aws/inputsources/mock/blueprint.ftl, aws/services/resource.ftl
Refactor - Account-layer Attribute AWSId to ProviderId 
#169
tested with the changes made with executor
Closes #169
=> updated Attribute AWSId to ProviderId #169

aws/components/adaptor/setup.ftl, aws/components/apigateway/setup.ftl, aws/components/bastion/setup.ftl, aws/components/cdn/setup.ftl, aws/components/computecluster/setup.ftl, aws/components/configstore/setup.ftl, aws/components/datapipeline/setup.ftl, aws/components/ec2/setup.ftl, aws/components/ecs/setup.ftl, aws/components/federatedrole/setup.ftl, aws/components/lambda/setup.ftl, aws/components/mobileapp/setup.ftl, aws/components/spa/setup.ftl, aws/components/template/setup.ftl, aws/components/user/setup.ftl, aws/inputsources/shared/masterdata.ftl, aws/masterData.json
aws implementation of https://github.com/hamlet-io/engine/pull/1494 
Updates all components which currently support fragments to the new
extensions process which includes support for fragments. 
This allows for
extensions to be defined as part of our plugin setup and allows for
components to call multiple extensions
=> feat: fragment to extension migration

aws/components/baseline/setup.ftl, aws/components/lambda/setup.ftl, aws/components/mta/id.ftl, aws/components/mta/setup.ftl, aws/components/mta/state.ftl, aws/components/s3/id.ftl, aws/components/s3/setup.ftl, aws/services/ses/id.ftl, aws/services/ses/resource.ftl
Implements https://github.com/hamlet-io/engine/issues/1499
First implementation of inbound and outbound MTAs.
The outbound implementation mainly provides link and attribute support to permit sending of emails.
The inbound implementation supports rulesets and IP filters. S3, lambda and drop actions are supported.
Because inbound email support is only available in limited regions, the implementation currently assumes that if S3 encryption is required, AES will be used. KMS is more problematic as the framework support for sharing KMS keys is not yet complete.
Simplify management of email capabilities for solutions.
Local template generation and customer deployment
=> feat: Message Transfer Agent component

aws/components/lambda/setup.ftl
Includes a couple of changes around lambda functions 
1. When using the Url Image source configuration the build unit is set to the component name instead of the deployment unit. 
2. Disables the creation of the Lambda Version when the `CreateVersionInExtension` attribute has been defined in an extension
1. Allows for multiple lambda functions deployed under the same unit to have distinct lambda code images
2. Allows for an extension to handle the creation of lambda versions, this is useful when you use custom lambda resources to modify the lambda code before creating the version and is especially useful for lambda@Edge functions which don't support env vars
Tested locally
=> feat(lambda): extension version control

aws/components/globaldb/setup.ftl, aws/services/dynamodb/resource.ftl
Support the inclusion of secondary indexes on globaldb tables, as well as key attribute type control.
Project requirement for more complex table configuration
Depends on https://github.com/hamlet-io/engine/pull/1507
=> feat: globaldb secondary indexes

aws/components/s3/setup.ftl
Add support for extensions to the s3 component which would allow for custom policy to be defined during template generation
#203
Got it tested locally
=> Feat s3 extensions support

aws/components/filetransfer/state.ftl, aws/components/template/setup.ftl
Implementation of https://github.com/hamlet-io/engine/pull/1513 which allows for sourcing template images via a URL instead of the build registry 
Includes a minor fix for the filetransfer component to handle out of date networks during state lookups 
The image sourcing helps in demonstration of prototyping scenarios where you don't wan't to worry about creating a build job for the template file
Tested locally
=> feat(template): url image source

aws/components/userpool/setup.ftl
AWS implementation of: https://github.com/hamlet-io/engine/pull/1521 
Adds support for extensions and links to authproviders as part of userpools 
Dynamic configuration of settings required to configure authprovider federation
Tested locally
=> feat(userpool): extension support for providers

aws/components/spa/setup.ftl
AWS implementation of https://github.com/hamlet-io/engine/pull/1522 which pulls images from an external source for single page applications 
Allows for providing pre-built artefacts when deploying single page apps
Tested locally
=> feat(spa): image source via url

aws/components/federatedrole/setup.ftl
Adds support for environment settings in federated role assignments which can be used in contexts to determine roles and permissions
Provides settings that can be used during context processing
Tested locally
=> feat(federatedrole): support for env in assignemnts

aws/components/ecs/setup.ftl, aws/components/network/setup.ftl, aws/components/network/state.ftl, aws/inputsources/shared/masterdata.ftl, aws/masterData.json
Remove redundant code/masterdata and add support for a transition from legacy support to explicit configuration on the network components.
- Ensure smooth transition from existing to new configurations
- Catch use of legacy configuration and flag that it needs to be updated
Requires https://github.com/hamlet-io/engine/pull/1531
Fixes https://github.com/hamlet-io/engine-plugin-aws/issues/224
=> fix: flowlog tidyup

aws/components/s3/setup.ftl
Do not validate bucket source / destination sequence when performing stack deletion.
When replicating a data bucket into another, we only want to validate the order of operations on their creation/update. Performing thet same validation on the delete of a bucket implies that a replica destination should still exist during the deletion of the source - but that is not usually the req.
Related to hamlet-io/engine#1526
Testing still required.
=> Bugfix - S3 Replica Priorities on Stack Deletion

aws/components/bastion/setup.ftl, aws/components/ec2/setup.ftl, aws/components/ecs/setup.ftl, aws/components/user/state.ftl, aws/services/ec2/resource.ftl
per hamlet-io/engine#1489
On ssh segment for integration environment of one of the tenants, confirmed to be working as expected.
=> feat(ec2): SSH Key Import to ec2 instances

aws/components/bastion/setup.ftl
Minor fix to support the Active solution configuration on the AWS bastion implementation.
This appears to have been missed in the bastion implementation, and allows for turning on the bastion instance at the solution level. This can be used for specific maintenance deployment modes using deployment profiles
Tested locally
=> fix(bastion): support active config on component

aws/inputsources/shared/masterdata.ftl, aws/masterData.json
The AWS implementation of changes made in https://github.com/hamlet-io/engine/pull/1548
Fixes a number of incorrect attributes in the provider master data.
Listed as breaking change as this will likely cause changes to existing deployments.
https://github.com/hamlet-io/engine/pull/1548
Locally tested against corresponding Engine PR.
=> Fix - Invalid Data

aws/modules/cloudwatchslack/README.md, aws/modules/consolidatelogs/README.md, aws/modules/no_master_resourcesets/README.md, aws/modules/no_master_vpc/README.md
Add README's to existing provider modules.
Documentation
n/a
=> Docs - Provider Modules

aws/inputsources/shared/masterdata.ftl, aws/masterData.json, aws/modules/cloudwatchslack/module.ftl
Corrects a number of minor issues with input source data for masterdata and modules.
Discovered during the development of hamlet-io/engine#1548
Alongside the above engine PR
=> Fix: Invalid Input Source Data

aws/inputseeders/aws/id.ftl, aws/inputseeders/aws/masterdata.json, aws/inputseeders/aws/regions.json, aws/inputseeders/inputseeder.ftl
Implement seeders to provide input state via the refactored input source processing.
Masterdata is now dynamically loaded directly from JSON files, and provided to the masterdata stage. If is filtered by region if provided.
It also provides an example of a seeder that is specific to a particular input source. The example needs to adjust the command line options but only for the `mock` input source.
Note that this change has not affected the existing input processing. A subsequent change will be introduced to perform the transition.
=> feat: input seeders

aws/services/vpngateway/resource.ftl
Implements: https://github.com/hamlet-io/engine/pull/1563 
https://github.com/hamlet-io/engine/issues/1562 
Tested locally
=> feat(gateway): vpn gateway dpd action

README.md
Updates the Plugin README
Consistency across Hamlet Deploy documentation
n/a
=> chore: review the plugin readme

test/run_aws_template_tests.sh
Align with the cli changes introduced in https://github.com/hamlet-io/executor-python/pull/89
Testing broken 
Will use CI Testing
=> fix: test args for hamlet cmds

aws/components/db/state.ftl
Adds handling for invalid configuration during db state processing.
Allows for the broken config to be handled by our existing exception handling process
Tested locally
=> fix: invalid config handling for db

aws/deploymentframeworks/cf/output.ftl
Updates the aws provider to support output writing as part of the engine
AWS support for https://github.com/hamlet-io/engine/pull/1583
Tested locally
=> refactor: output handling in engine

aws/components/bastion/setup.ftl, aws/components/computecluster/setup.ftl, aws/components/ec2/setup.ftl, aws/components/ecs/setup.ftl, aws/inputseeders/aws/masterdata.json, aws/services/ec2/resource.ftl
Implementation of https://github.com/hamlet-io/engine-plugin-aws/issues/259 which replaces the scripts in cloudinit-aws with engine generated equivalents 
Easier to manage changes in EC2 script requirements 
Allows for supporting different OS's 
Scripts can be more explicit in what they are doing 
Tested locally
=> Refactor replace startup scripts

Jenkinsfile
Install the latest version of hamlet on the setup of job. 
Removes the waiting period required for containers to build and provides more reliable testing results as the code will align between the components
Will test in Jenkins pipeline
=> feat(cd): setup latest hamlet on each run

aws/components/apigateway/setup.ftl
AWS implementation of https://github.com/hamlet-io/engine/pull/1622 adds support for getting open api definitions from other sources 
Allows for more control over where open api specs are sourced from including support for defining them in modules
Tested locally
=> feat(apigateway): Image sourcing

aws/inputseeders/aws/id.ftl
Remove specific logic to normalise AWS stacks.
AWS cli format stack outputs are now normalised in the shared provider, since the same format is used for pseudo stacks.
=> fix: pseudo stacks

aws/services/ec2/resource.ftl
Minor fix for typo in disk mounting
Error thrown during execution of script 
Tested locally
=> fix(ec2): typo in mount point check

aws/components/es/setup.ftl, aws/deploymentframeworks/cf/output.ftl, aws/services/ec2/resource.ftl, awstest/inputseeders/awstest/id.ftl, awstest/modules/apigateway/module.ftl, awstest/modules/bastion/module.ftl, awstest/modules/ecs/module.ftl
Adds base tests cases for some of our ec2 based components along with some fixes found when running cfn_lint as part of the tests
Increase test coverage and make our templates cleaner
Tested locally
=> chore: testing for ec2 based components

aws/deploymentframeworks/cf/output.ftl
Updates the output configuration to work with refactoring of the output properties process
Aligns AWS provider with https://github.com/hamlet-io/engine/pull/1639 
Tested locally
=> refactor: update output properties for new format

aws/components/adaptor/setup.ftl, aws/components/computecluster/id.ftl, aws/components/computecluster/setup.ftl, aws/components/computecluster/state.ftl, aws/extensions/computetask_linux_scriptsdeployment/extension.ftl, awstest/inputseeders/awstest/id.ftl, awstest/modules/computecluster/module.ftl
Adds support for providing an image source for compute clusters as part of https://github.com/hamlet-io/engine/issues/1486 
This allows for more custom approaches to build compute clusters including installs of COTS products
- None
- None
- None
=> feat: Compute cluster image source

aws/components/apigateway/setup.ftl
- Adds support for configuring mutualTLS on apigateways.
- Adds support for disabling the default execute api domain names if custom domains are found. This ensures consistency on endpoints and is also required for mutualTLS
MutualTLS is a common authentication pattern for apigateways and TLS endpoints. Adding support for this allows for integration with more services 
Disabling execute endpoints is required for mutualTLS and it also ensures that TLS policies overall are followed as they are enforced on the custom domain name.
Tested locally
- https://github.com/hamlet-io/engine/pull/1677
- None
- None
=> feat(apigateway): mutualTLS support

aws/components/adaptor/state.ftl
Includes the adaptor attributes configured in the solution in the occurrence state
Allows for more integration between adaptors and other components
- None
- None
- None
=> feat(adaptor): support for adaptor attributes

aws/extensions/computetask_linux_docker/extension.ftl, aws/extensions/computetask_linux_docker_compose/extension.ftl, aws/extensions/computetask_linux_userbootstrap/extension.ftl
This PR introduces two new extensions - docker and docker-compose.
In order to support running docker-compose projects on ec2 instance docker and docker-compose need to be installed there during cfn init stage.
Tested locally
- None
- None
- None
=>  feat: add docker and docker compose compute tasks 

aws/components/apigateway/setup.ftl
- Documentation (new or update to existing)
Ensure schema model names are alphanumeric.
Add support for modifying swagger specs to meet the additional constraints applied by AWS. Much of this was previously done in the bash executor using `jq`, but it seems more appropriate to apply these constraints at the point of deployment rather than at the time of build.
Local template generation of existing specs as well as the new specs which triggered the need for the PR.
Once this PR is merged, a …
=> fix: API Gateway Schema naming constraint

.dockerignore, .github/workflows/package.yml, Dockerfile
Adds support for publishing a docker based image of the repository as part of the move to fixed package installations
To make it easy to install and setup hamlet ( hamlet-io/architectural-decision-log#11 )
- None
- None
- None
=> feat: add support for docker packaging

aws/components/dataset/setup.ftl, aws/components/dataset/state.ftl, awstest/inputseeders/awstest/id.ftl, awstest/modules/dataset/module.ftl
- Adds support for using an external url for the image source of a component
- Adds basic generation tests for the dataset component to catch any obvious errors 
This provides flexibility for users to use their own process for managing images while integrating with hamlet for hosting
https://github.com/hamlet-io/engine/issues/1486 
Tested locally
- None
- None
- None
=> feat(dataset): image source configuration

aws/services/ecs/resource.ftl
Adds support for setting ecs placement strategies on services. This allows for greater control over how tasks are placed and what conditions are used to pick the host
Allows for configuring how hosts are chosen for container placement. Combining this with capacity providers allows for ECS to manage and reduce the number of instances required
Tested locally
- https://github.com/hamlet-io/engine/pull/1697
- None
- None
=> feat(ecs): add support for placement strategies

aws/inputseeders/aws/masterdata.json
Update the segment deployment unit priorities to manage the dependencies between the different components during deployments
Deployments in aws using the standard generated solution fails as the eip resource set is being deployed before the VPC is available. This fixes the ordering to make sure it all works 
Tested locally
- None
- None
- None
=> refactor: update segment unit priorties

aws/components/apigateway/setup.ftl, aws/components/bastion/setup.ftl, aws/components/cache/setup.ftl, aws/components/cdn/setup.ftl, aws/components/computecluster/setup.ftl, aws/components/datafeed/setup.ftl, aws/components/datapipeline/setup.ftl, aws/components/db/setup.ftl, aws/components/db/state.ftl, aws/components/ec2/setup.ftl, aws/components/ecs/setup.ftl, aws/components/ecs/state.ftl, aws/components/efs/setup.ftl, aws/components/es/setup.ftl, aws/components/es/state.ftl, aws/components/externalnetwork/setup.ftl, aws/components/filetransfer/setup.ftl, aws/components/gateway/setup.ftl, aws/components/healthcheck/setup.ftl, aws/components/lambda/setup.ftl, aws/components/lb/setup.ftl, aws/components/mobilenotifier/setup.ftl, aws/components/network/setup.ftl, aws/components/queuehost/setup.ftl
Updates the aws components to use the updated profile lookup functions that have been introduced in the shared provider
Make profiles easier to configure and understand
- https://github.com/hamlet-io/engine/pull/1699
- None
- None
=> refactor: standarise the profile lookup process

aws/components/lambda/setup.ftl
Correct cut/paste error resulting from changes to profile handling.
Also fix an issue with the generated prologue script that was identified during testing of the profile fix.
Generation of lambda templates is failing.
Local template generation and comparison with previously generated templates.
- None
- None
- None
=> fix: update get profile calls

.github/workflows/package.yml, .github/workflows/testing.yml
Updates triggers for packaging to run once testing has completed. 
removes filter on push container to always run and only push on specific refs
Ensures we only create a package if the testing worked
Will be tested with PR
- None
- None
- None
=> fix(ci): packaging handling

.dockerignore
Adds the .git dir to the dockerignore to reduce the size of the package
reduce the size of the docker image as a build summary is now included in the .hamlet dir
Tested locally
- None
- None
- None
=> refactor(ci): ignore the git dir in docker

.github/workflows/package.yml
Updates the default docker tag handling to allow for commits on different branches and PRs
Makes docker image tagging work as expected
- None
- None
- None
=> fix(ci): default docker tagging handling

awstest/inputseeders/awstest/id.ftl, awstest/modules/service/module.ftl
Adds basic linting tests for the service component to provide minimal coverage over the setup and state functions
To increase our testing coverage across key components in the AWS provider
Tested with testing commands
- https://github.com/hamlet-io/engine/pull/1734 - Fixes a bug which stopped the test case from loading
- None
- None
=> feat(tests): add basic testing for service

aws/components/userpool/state.ftl, awstest/inputseeders/awstest/id.ftl, awstest/modules/userpool/module.ftl
Check if the existing reference for userpool region isn't an empty string. If it is - set to regionId.
hamlet-io/engine#1261
A basic test has been added.
- None
- None
- None
=> Fix region for userpool

aws/components/sqs/setup.ftl, aws/services/sqs/resource.ftl, awstest/inputseeders/awstest/id.ftl, awstest/modules/sqs/module.ftl
Include tags for SQS components
https://github.com/hamlet-io/engine/issues/1133
Locally
- None
- None
- None
=> Add tags for SQS

aws/components/ecs/setup.ftl
Raise Hamlet fatal error for task without container 
Fixes https://github.com/hamlet-io/engine-plugin-aws/issues/361
Shift onus of test onto Hamlet
Locally
- None
- None
- None
=> Fatal error if no containers for service or task

aws/components/ecs/setup.ftl, aws/components/ecs/state.ftl, aws/inputseeders/aws/masterdata.json, aws/services/ecs/resource.ftl, awstest/inputseeders/awstest/id.ftl, awstest/modules/ecs/module.ftl, awstest/modules/service/module.ftl, awstest/modules/task/module.ftl
Include tags for ECS Cluster, Service and Tasks
Fixes https://github.com/hamlet-io/engine/issues/1132
Locally
- None
- None
- None
=> Add tags to ecs cluster services and tasks

aws/components/topic/setup.ftl, aws/services/sns/resource.ftl, awstest/inputseeders/awstest/id.ftl, awstest/modules/topic/module.ftl
Add tags on topics
Fixes https://github.com/hamlet-io/engine/issues/1131
Local template generation and deployment to aws
Extended testcases to include
- None
- None
- None
=> Add tagging support for SNS topics

aws/components/apigateway/setup.ftl, aws/components/apigateway/state.ftl, aws/services/apigateway/resource.ftl, awstest/inputseeders/awstest/id.ftl, awstest/modules/apigateway/module.ftl, awstest/modules/apiusageplan/module.ftl, awstest/modules/apiuser/module.ftl
Add tags to AWS::ApiGateway:: children
Fixes https://github.com/hamlet-io/engine/issues/1130
Locally 
- None
- None
- None
=> Add tagging support for APIgateway

aws/components/apigateway/setup.ftl, aws/components/cdn/setup.ftl, aws/services/cf/resource.ftl, awstest/inputseeders/awstest/id.ftl, awstest/modules/apigateway/module.ftl, awstest/modules/cdn/module.ftl
Add tags to CF Distribution from CDN and APIgateway
Fixes https://github.com/hamlet-io/engine/issues/1134
Local generation and additional test cases
- None
- None
- None
=> feat (cf distribution): tags

aws/components/apigateway/setup.ftl, aws/components/baseline/setup.ftl, aws/components/bastion/setup.ftl, aws/components/computecluster/setup.ftl, aws/components/datafeed/setup.ftl, aws/components/datapipeline/setup.ftl, aws/components/datavolume/setup.ftl, aws/components/db/setup.ftl, aws/components/ec2/setup.ftl, aws/components/ecs/setup.ftl, aws/components/es/setup.ftl, aws/components/federatedrole/setup.ftl, aws/components/filetransfer/setup.ftl, aws/components/healthcheck/setup.ftl, aws/components/lambda/setup.ftl, aws/components/mobilenotifier/setup.ftl, aws/components/network/setup.ftl, aws/components/s3/setup.ftl, aws/components/user/setup.ftl, aws/components/userpool/setup.ftl, aws/services/cw/resource.ftl, aws/services/iam/resource.ftl, aws/services/kinesis/resource.ftl, awstest/modules/apiuser/module.ftl
Add tags for IAM::Users and IAM::Roles
Fixes https://github.com/hamlet-io/engine/issues/1129
Local generation and extend test cases for users
- None
- None
- None
=> feat(iam): tags

aws/components/firewall/setup.ftl, aws/inputseeders/aws/id.ftl
- fixes the log handling case statement for s3 destinations
- adds a specific output lookup to handle the format of network firewalls
An unexpected fatal message was being logged when configuring logging on the firewall to s3 
tested locally
- None
- None
- None
=> fix(firewall): s3 log type detection

aws/inputseeders/aws/id.ftl
When mocking data, override any already mocked values provided by the shared seeder. 
This ensures the value provided more closely aligns with AWS expectations.
Fixes https://github.com/hamlet-io/engine/issues/1800
- engine - https://github.com/hamlet-io/engine/pull/1802
- None
- None
=> fix: whatif processing

aws/components/gateway/setup.ftl
- add deployment subset check on route creation
- fix combine behaviour for ip address group array
Fixing some issues during deployment to product 
Tested locally
- None
- None
- None
=> fix(igw): firewall route handling

aws/components/firewall/setup.ftl
- fixes a minor typo where the wrong solution configuration was used for firewall destinations
Template generation issues
- None
- None
- None
=> feat(firewall): fix link issue for destinations

aws/components/firewall/setup.ftl, aws/components/firewall/state.ftl
Include the occurrence on IP Address lookups to ensure we can support local networks
Performing lookups of the local net returned a global address which in turn caused conflicts on the routes
- None
- None
- None
=> fix(firewall): provide occurrence for ip address

aws/components/directory/id.ftl, aws/components/directory/setup.ftl, aws/components/directory/state.ftl, aws/services/ds/id.ftl, aws/services/ds/resource.ftl, aws/services/service.ftl, awstest/inputseeders/awstest/id.ftl, awstest/modules/directory/module.ftl
Add new component "directory" and service "ds"
**Note**: I have deliberately not included the createAlias feature as this has warning associated with it that it can not be reused (ie http://_alias_.awsapps.com is permanently unique)
Fixes https://github.com/hamlet-io/engine/issues/1756
Locally generated, new test cases and deployed to AWS. Note deployment is very slow (30 minutes)
- https://github.com/hamlet-io/engine/pull/1796
- None
- None
=> feat(ds): New Component - Directory Services

aws/deploymentframeworks/cf/output.ftl
ensure all tags have content before they are included in the tag set
Deployment failing on missing tag content
tested locally
- None
- None
- None
=> fix(tags): ensure values exist before use

aws/components/db/setup.ftl, aws/components/db/state.ftl, aws/services/rds/resource.ftl, awstest/modules/db/module.ftl
- aligns the db zone handling with the expectations of the AWSAzReferences function
- Enables cfn lint for db testing to ensure templates are valid
Template generation failing which should have been picked up in testing
tested locally and with test cases
- None
- None
- None
=> fix: db zone handling

aws/components/computecluster/setup.ftl, aws/components/directory/setup.ftl, aws/components/directory/state.ftl
A couple of minor updates to the directory component
- Locks the username for the default admin account to Admin
- Sets ingress and egress rules for the group to allow full comms  between Ad instances
- Adds Directory attribute details so they can be used in domain join setup
Usability updates to align with usage in real world setup. 
Align with recommended security policies
- None
- None
- None
=> refactor(directory): attributes and ip access

.github/workflows/release.yml, README.md, aws/inputseeders/aws/ec2_masterdata.sh
- Removes the use of dos2unix in hamlet
- Updates the ci/cd pipeline to install the right pypi package
- Aligns documentation with install guide
dos2unix isn't installed by default on most CI/CD pipelines or OS'
cleans up documentation and removes dependency on old python package
Tested locally
- None
- None
- None
=> refactor: remove dos2unix

awstest/modules/bastion/module.ftl, awstest/modules/cdn/module.ftl, awstest/modules/computecluster/module.ftl, awstest/modules/correspondent/module.ftl, awstest/modules/db/module.ftl, awstest/modules/directory/module.ftl, awstest/modules/ec2/module.ftl, awstest/modules/ecs/module.ftl, awstest/modules/firewall/module.ftl, awstest/modules/healthcheck/module.ftl, awstest/modules/lb/module.ftl, awstest/modules/network/module.ftl, awstest/modules/queuehost/module.ftl, awstest/modules/service/module.ftl, awstest/modules/sqs/module.ftl, awstest/modules/task/module.ftl, awstest/modules/topic/module.ftl
Updates the cfn-lint configuration in testing modules to align with new structure
Continue the operation of the test suites
- https://github.com/hamlet-io/engine/pull/1828
- None
- None
=> refactor: cfn-lint configuration

aws/components/directory/setup.ftl, awstest/modules/directory/module.ftl
Remove code which created irrelevant security group
Epilogue script change to modify AWS created security group to align with defined IPAddressGroups
Fixes https://github.com/hamlet-io/engine/issues/1832
Locally generated and deployed to AWS
- None
- None
- None
=> fix(ds): Remove redundant sg and modify sg to align with IPAddressGroups

aws/components/directory/setup.ftl
Reworked epilogue to create rules from any existing DS rule rather than only global and corrected removals to handling updates of customised security group
Fixes https://github.com/hamlet-io/engine/issues/1844
Locally generated and deployed to AWS
- None
- None
- None
=> fix(ds): security group update fix

aws/deploymentframeworks/cf/output.ftl
- Replaces the use of eval with eval_json when loading json based objects
Aligns with the recommendations from freemarker
https://freemarker.apache.org/docs/ref_builtins_expert.html#ref_builtin_eval
- None
- None
- None
=> refactor: replace eval with eval_json

aws/services/kinesis/resource.ftl
Add explicit config to indicate when a Kinesis delivery stream is NOT performing KMS encryption.
Kinesis does not gracefully handle the removal of encryption settings on a delivery stream (even though the documented default value would suggest it does). Instead, additional config is needed to indicate that KMS encryption is explicitly NOT required.
This is an unusual situation as once set, encryption settings are normally not altered. However, as cloudformation thinks everything is ok (it hasn't forwarded the encryption options), to avoid confusion and additional troubleshooting and frustration, the extra configuration is explicitly set.
- None
- None
- None
=> refactor: delivery stream encrpytion changes

aws/components/mta/setup.ftl, aws/components/mta/state.ftl, aws/components/topic/setup.ftl, aws/services/ses/resource.ftl
- Fixes the merging of state when on mta roles
- Fixes a missing arn array update for topic subscriptions ( appears to have been a merge issue )
- Removes tagging which is not used
- 
Deployments failing for send based mtas
Tested locally
- None
- None
- None
=> fix(mta): send SNS topic subscriptions

aws/services/kinesis/resource.ftl
Add configuration support for enabling partitioning when the destination is S3.
Dynamic partitioning must be enabled if adding delimiters between records or when using dynamic partition operators in the prefix or error prefix.
Partition values will typically be added via a `metadata` attribute on each record by a lambda processor.
- None
- None
- None
=> feat: kinesis dynamic partitioning

aws/components/mta/setup.ftl
Extend epilogue to include using sesv2 put|create-email-identity to configure default routing
Fixes https://github.com/hamlet-io/engine/issues/1861
Locally generated and deployed to AWS, but email routing not tested
- None
- None
- None
=> Outbound MTA email identity support

aws/components/mta/setup.ftl
Incorporate feedback from Roley
Incorporate feedback from Roley
Locally generated and deployed to AWS
- None
- None
- None
=> fix: email identity

aws/services/kinesis/resource.ftl
Set minimum buffer size for S3 destination to 64Mb if dynamic partitioning is being employed.
This is the minimum AWS allows in this case.
- None
- None
- None
=> fix(kinesis): minimum buffer hint

aws/services/ecs/resource.ftl
- Adds the required configuration for enabling GPUs on ecs tasks
Enables the configuration of GPU's for ecs tasks
More details on ECS with GPU available here https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-gpu.html
Tested locally and with deployment
- https://github.com/hamlet-io/engine/pull/1866
- None
- None
=> feat(ecs): add gpu support to task definitions

aws/components/db/state.ftl, aws/components/directory/state.ftl, aws/components/secretstore/state.ftl
Don't raise exceptions when state lookups look for links and they can't be found.
Template generation fails when performing initial deployment 
Tested locally
- None
- None
- None
=> fix: handle state lookup before deployment

aws/attributesets/aws_antivirus/id.ftl, aws/attributesets/aws_computeimage/id.ftl, aws/attributesets/aws_ecs_computeimage/id.ftl, aws/attributesets/aws_operatingsystem/id.ftl
remove plural types on attribute set
Not required or used when dealing with attribute sets
- https://github.com/hamlet-io/engine/pull/1874
- None
- None
=> refactor: remove plural types on attribute set

aws/components/mta/setup.ftl
- Use get reference for rule associations in mta configuration
This ensures that dependencies are managed in the rules when they are deployed
Deployments failing when multiple rules are created at the same time
tested locally
- None
- None
- None
=> fix: mta rule references

aws/components/datapipeline/setup.ftl
- Ensures that extensions are always invoked if context processing is being used
This allows for defining default context values as part of the extension processing to reduce the configuration requirements across components
- None
- None
- None
=> refactor: always call invokeExtensions

aws/components/lambda/setup.ftl, aws/services/lambda/resource.ftl
- Adds support for defining layers for lambda functions
- Adds support for providing a jar file instead of a zip
This allows for broader lambda support with layers providing an easy way to install os level dependences if they are required. 
Tested locally and with active deployment
- None
- None
- None
=> feat(lambda): layers and jar file support

aws/components/ecs/setup.ftl
- Uses a combination of the container Id and component id when saving image pull details
Aligns with the changes outlined in https://github.com/hamlet-io/engine/pull/1899
tested locally
- None
- https://github.com/hamlet-io/engine/pull/1899
- None
=> refactor: containerregistry source details

aws/attributesets/attributeset.ftl, aws/attributesets/aws_s3_notification/id.ftl, aws/components/baseline/id.ftl, aws/components/s3/id.ftl, aws/services/vpc/resource.ftl
- Replaces global configuration and adds provider specific attributes
- Makes the configuration aligned with the idea of using attribute sets for shared configuration 
- Makes documentation easier from the reference 
- Moves some of the aws provider specific attributes from shared to the aws provider
Tested locally
- None
- None
- None
=> refactor: attribute sets for global configuration

aws/components/apigateway/setup.ftl, aws/components/cdn/setup.ftl, aws/components/lb/setup.ftl, aws/services/waf/resource.ftl
- Fixes a condition which prevented enabling logging for wafv1 on cdn
- Fixes the syntax used to enable waf logging in v2 
Logging resources deployed but logging is not be enabled on wafv1 
Tested locally
- None
- None
- None
=> fix(cdn): logging script for wafv1

aws/components/lb/setup.ftl
- Get logging profile for LB components
Template generation failing when log groups are required for WAF logging
- None
- None
- None
=> fix(lb): logging profile for WAF logs

aws/components/backupstore/setup.ftl
Rely on the encryption key configured in the baseline profile.
Implementation now reflects the intent of the baseline profile.
A different profile can be configured specifically on the backupstore if a different baseline key should be used for encryption.
- https://github.com/hamlet-io/engine/pull/1927
- None
- None
=> refactor: backup encryption key

aws/components/db/setup.ftl
- Fixes the id for the security group for ingress rules on db components
fixes https://github.com/hamlet-io/engine/issues/1928
- None
- None
- None
=> fix(db): ingress security group id

aws/components/datafeed/setup.ftl, aws/services/kinesis/resource.ftl
- Adds support for setting the compressionFormat for firehose
- Implements the compression formatting control for datafeeds
Allows for controlling how data is saved to s3 buckets using kinesis firehose
Tested locally
- None
- None
- None
=> feat(kinesis): compression support for firehose

aws/components/db/setup.ftl, aws/deploymentframeworks/cf/output.ftl, aws/services/rds/resource.ftl, awstest/modules/db/module.ftl
- Fixes an issue with multiple az references
- Makes the engine version value default to major minor concatenation
- Use getArn for all Arn Lookups
- Fixes the paramter for Snapshot restores in DB clusters
- Adds test case for DB cluster
Issues found when trying to deploy the current aurora db cluster
Tested locally
- None
- None
- None
=> fix(db): aurora cluster updates

aws/components/mta/setup.ftl
- Adds handling for enable and disable of rules within the MTA
Allows for debugging of rules without removing them from the solution. 
- None
- None
- None
=> feat(mta): add enable/disable handling on rules

aws/components/ecs/id.ftl, aws/components/ecs/setup.ftl, aws/components/ecs/state.ftl, aws/modules/runbook_run_task/module.ftl, aws/services/ecs/resource.ftl, aws/tasks/aws_ecs_run_task/id.ftl, aws/tasks/task.ftl
- Adds task to support executing an AWS task with container overrides
- Adds capacity provider state support for tasks
- Adds state for the required network resources to run tasks
Allows for the replacement and user customisation of running on demand container tasks on AWS ECS
- None
- None
- None
=> feat: add run ecs task support for runbooks

aws/components/adaptor/setup.ftl, aws/services/resource.ftl
- Adds support for alerts on adaptor components
- Fixes a fatal message context
Allows for creating alerts from nonstandard metrics 
Tested locally
- None
- None
- None
=> feat(adaptor): adaptor alert support

awstest/modules/healthcheck/module.ftl
- Updates testing templates to use engine instead of type to align with changes in core engine
Testing of aws provider failing
Tested locally
- None
- None
- None
=> fix(healthceheck): testing changes from type to engine

aws/components/db/state.ftl
- Fixes when the engine is looked up when dealing with secretstore for DB credentials
Template generation failing when linking to a secret instead of secret store. 
Tested locally
- None
- None
- None
=> fix(db): secret lookup for engine setup

.github/workflows/release.yml, aws/services/resource.ftl, engine.ini
Aligns the testing process with the latest install processes available for the hamlet engine
Aligns with latest processes to ensure that everything is aligned
- None
- None
- None
=> refactor: move to latest unicycle install process

aws/inputseeders/aws/id.ftl, awstest/modules/healthcheck/module.ftl
- Changes the segment seed to a fixed return value
- Updates the complex health check to align with new naming
Testing was failing for the complex healthcheck
Tested locally
- None
- None
- None
=> fix: segment seed fixture value

aws/components/ec2/setup.ftl, aws/components/ec2/state.ftl, aws/extensions/computetask_awswin_vpc_lb/extension.ftl
- Adds resource filter based on the Zone configuration option
AWS implementation of https://github.com/hamlet-io/engine/pull/1964
- https://github.com/hamlet-io/engine/pull/1964
- None
- None
=> feat(ec2): zone based control for instances

aws/components/cdn/setup.ftl
- Only include event handlers which have been enabled in the solution
Implementation of https://github.com/hamlet-io/engine/pull/1965
- https://github.com/hamlet-io/engine/pull/1965
- None
- None
=> feat(cdn): only add enabled event handlers

aws/components/bastion/setup.ftl, aws/components/cache/setup.ftl, aws/components/computecluster/setup.ftl, aws/components/datavolume/state.ftl, aws/components/db/setup.ftl, aws/components/db/state.ftl, aws/components/ec2/state.ftl, aws/components/ecs/setup.ftl, aws/components/ecs/state.ftl, aws/components/es/setup.ftl, aws/components/fileshare/setup.ftl, aws/components/filetransfer/setup.ftl, aws/components/filetransfer/state.ftl, aws/components/firewall/setup.ftl, aws/components/gateway/setup.ftl, aws/components/gateway/state.ftl, aws/components/lb/setup.ftl, aws/components/queuehost/setup.ftl, aws/inputseeders/aws/masterdata.json, aws/modules/privatebastion/module.ftl, aws/services/lb/resource.ftl, awstest/modules/cache/module.ftl
- Implements the migration of multiAZ to component configuration across AWS components that use it
- Remove RDS Upgrade configuration from the default segment layer
AWS implementation of https://github.com/hamlet-io/engine/pull/1969
- https://github.com/hamlet-io/engine/pull/1969
- None
- None
=> refactor: multiAZ migration to component configuration

aws/components/computecluster/setup.ftl, aws/extensions/computetask_awslinux_cfninit_asg/extension.ftl, aws/services/ec2/policy.ftl, aws/services/ec2/resource.ftl
- Moves IAM policy setup to ensure lb policies are included
- fix priority for cfn init command to use 3 numbers in line with other commands ( ordering is string based )
- include ec2messags:GetMessages for all instance types
- Allow for defining ports and lb configuration options
Minor fixes found when using compute cluster deployments that prevented the deployment from working or were raising errors in logs
- None
- None
- None
=> fix(computecluster): general fixes

aws/services/resource.ftl
- Checks for Value and hash region refs for getReference between components in the same deployment
When deploying components within the same deployment that used more complex ref vallues the template generation would fail 
- None
- None
- None
=> fix: include Value in getReference

aws/inputseeders/aws/masterdata.json, aws/services/cw/id.ftl, aws/services/cw/resource.ftl
- Changes the order for account level units to run iam before cmk
- Add support for CloudWatch Log resource policies
Fixes issues outlined in https://github.com/hamlet-io/engine/pull/1973 
- None
- None
- None
=> fix: log and account processing

aws/components/certificateauthority/setup.ftl, awstest/modules/certificateauthority/module.ftl, awstest/modules/correspondent/module.ftl
- Fix testcase lookup for correspondent
- Fix the authority Id used for authorising certificates
- Fix arn lookup for ca authority test case
Tests failing on lookups
- None
- None
- None
=> fix: testing updates

aws/components/lambda/setup.ftl, aws/services/lambda/resource.ftl
Support provisioned executions of versioned lambda functions.
Allow solutions to be configured to support production level workloads
- https://github.com/hamlet-io/engine/pull/1980
- None
- None
=>  feat(lambda): provisioned executions

aws/components/backupstore/setup.ftl, aws/components/baseline/setup.ftl, aws/components/cdn/setup.ftl, aws/components/configstore/setup.ftl, aws/components/externalnetwork/setup.ftl, aws/components/federatedrole/setup.ftl, aws/components/fileshare/setup.ftl, aws/components/firewall/setup.ftl, aws/components/gateway/setup.ftl, aws/components/lambda/setup.ftl, aws/components/lb/setup.ftl, aws/components/mobilenotifier/setup.ftl, aws/components/mta/setup.ftl, aws/components/network/setup.ftl, aws/components/router/setup.ftl, aws/components/secretstore/setup.ftl, aws/components/serviceregistry/setup.ftl, aws/components/topic/setup.ftl, aws/components/userpool/setup.ftl
- Adds a filter on occurrences to ensure they are enabled
This ensures that the enabled configuration is applied to both components and subcomponents. This is currently being ignored during processing of components.
Tested locally
- None
- None
- None
=> feat: only include enabled occurrences in suboccurrence processing

aws/components/network/setup.ftl
- reduce dependency requirements for network components
Had an issue where the ssh key could not be generated on baseline. This caused the vpc component deployment to fail which was not expected at all. 
Tested locally
- None
- None
- None
=> refactor(network): remove baseline components that aren't required

aws/components/adaptor/setup.ftl, aws/components/apigateway/setup.ftl, aws/components/cache/setup.ftl, aws/components/db/setup.ftl, aws/components/docdb/setup.ftl, aws/components/ecs/setup.ftl, aws/components/es/setup.ftl, aws/components/externalnetwork/setup.ftl, aws/components/globaldb/setup.ftl, aws/components/healthcheck/setup.ftl, aws/components/lambda/setup.ftl, aws/components/lb/setup.ftl, aws/components/mobilenotifier/setup.ftl, aws/components/queuehost/setup.ftl, aws/components/sqs/setup.ftl, aws/components/topic/setup.ftl
- Adds a filter on alerts to ensure the alert is enabled during deployment
Implementation of https://github.com/hamlet-io/engine/pull/1985 
- https://github.com/hamlet-io/engine/pull/1985
- None
- None
=> feat(alerts): add filter on alerts for enable status

aws/components/datafeed/setup.ftl, aws/components/datafeed/state.ftl, aws/components/datastream/id.ftl, aws/components/datastream/setup.ftl, aws/components/datastream/state.ftl, aws/services/kinesis/id.ftl, aws/services/kinesis/policy.ftl, aws/services/kinesis/resource.ftl, awstest/inputseeders/awstest/id.ftl, awstest/modules/datastream/module.ftl
- Uses AWS Kinesis data streams to implement the hamlet datastream component
- Includes AWS specific attributes used around data provisioning
Implementation of https://github.com/hamlet-io/engine/pull/1990 
- None
- None
- None
=> feat(datastream): aws implementation of data stream

aws/components/datavolume/state.ftl, aws/components/filetransfer/state.ftl
- minor updates from the transition between solution multiAZ and component MultiAZ 
Template generation failing
- None
- None
- None
=> fix: casing for MulitAZ attribute

aws/tasks/aws_secretsmanager_get_secret_value/id.ftl, aws/tasks/task.ftl
- Defines a task for getting the value of a secret from aws secrets manager
This allows for the use of secrets manager secrets during runbook exeuctions. 
Tested locally
- None
- None
- None
=> feat(task): add secrets manager get secret task

aws/components/db/setup.ftl, aws/services/rds/id.ftl, aws/services/rds/resource.ftl, awstest/modules/db/module.ftl, awstest/modules/docdb/module.ftl
Enable RDS Events via Role: publish links from RDS to SNS topic
A Role of "publish" will establish all events to the SNS topic. An optional comma delimited list of events can follow publish after a space. Interested in feedback as to whether there is a better solution to this
Fixes https://github.com/hamlet-io/engine/issues/140
Locally, deployed to AWS, testcases established
- https://github.com/hamlet-io/engine/pull/1991
- None
- None
=> feat(rds): event support

aws/components/bastion/setup.ftl, aws/components/computecluster/setup.ftl, aws/components/ec2/setup.ftl, aws/components/ecs/setup.ftl, aws/components/logstore/id.ftl, aws/components/logstore/setup.ftl, aws/components/logstore/state.ftl, aws/extensions/computetask_awslinux_cwlog/extension.ftl, aws/extensions/computetask_awswin_cwlog/extension.ftl, aws/services/cw/policy.ftl, awstest/inputseeders/awstest/id.ftl, awstest/modules/logstore/module.ftl
- Adds support for using logstore with ec2 based components that use the cloudwatch logs agent to collect file based logs from systems 
- Implementation of https://github.com/hamlet-io/engine/pull/1988  
- Supports controlling where log data collected on ec2 systems is forwarded to when it is collected
- None
- None
- None
=> feat: aws logstore implementation 

aws/components/globaldb/setup.ftl, aws/components/sqs/setup.ftl
- reinstate the dlq Name resource lookup
Some changes that shouldn't have been made during tagging updates
Tested locally
- None
- None
- None
=> fix(sqs): add dlqName back into setup routine

aws/components/datastream/id.ftl, aws/components/datastream/setup.ftl
- fixes a typo in the attribute name
It wasn't a word... 
Tested locally
- None
- None
- None
=> fix(datastream): typo in attribute name

aws/components/cdn/setup.ftl
- adds support for sorting cdn routes by priority
- fixes an issue with caching configuration not applying for http based backends
Implementation of https://github.com/hamlet-io/engine/pull/1999 
Fixes caching TTL controls for http backends
Tested locally
- None
- None
- None
=> feat(cdn): rule priority sorting

aws/components/computecluster/setup.ftl, aws/components/ec2/setup.ftl, aws/components/ecs/setup.ftl, aws/components/lb/id.ftl, aws/components/lb/setup.ftl, aws/components/lb/state.ftl, aws/extensions/computetask_awslinux_vpc_lb/extension.ftl, aws/extensions/computetask_awswin_vpc_lb/extension.ftl, aws/services/lb/resource.ftl, aws/services/vpc/resource.ftl, awstest/modules/lb/module.ftl
Adds support for lb backend subcomponents which create dedicated target groups that can be used across multiple load balancers and listener rules
Implementation of https://github.com/hamlet-io/engine/pull/2000 
Tested locally and also included test suites.
-  https://github.com/hamlet-io/engine/pull/2000 
- None
- None
=> feat(lb): backend support for application load balancers

aws/components/ecs/setup.ftl
Correct the reference to a suboccurrence when generating tags.
Template generation was failing
- None
- None
- None
=> fix(ecs): tags handling

.github/workflows/changelog.yml
- Standardise the change log process using a workflow stored in our hamlet .github repo
Makes it easier to manage the change log for all of our repos
- None
- None
- None
=> refactor(cd): move to using a reusable pipeline for changelogs

aws/components/apigateway/setup.ftl
Add a statement to the resource policy to provide an explicit ALLOW when the OPTIONS verb is requested and the response is
handled inline by the API Gateway.
If OPTIONS are handled inline by the API Gateway, they do not contribute the explicit ALLOW that an authorizer would normally provide. In this case, the resource policy must provide an explicit allow for the API Gateway authorization model to succeed.
Local template generation.
- None
- None
- None
=> fix(apigateway): OPTIONS handling with authorisers

aws/services/cw/resource.ftl
- Includes the details of the occurrence when creating the log role
Template generation failing
- None
- None
- None
=> fix(logs): fix tags applied to log subscription role

aws/services/ssm/resource.ftl
- Aligns tagging configuration with the getOccurrenceTags process
Tags provided through account console deployment failing as the tags are invalid
Tested locally
- None
- None
- None
=> fix(ssm): tag properties for ssm resourcs

aws/components/lb/setup.ftl, aws/components/lb/state.ftl
Use standard fatal error for invalid port mapping
Part of https://github.com/hamlet-io/engine/issues/1685
Locally
- None
- None
- None
=> fix(lb): standard error for invalid port mapping

aws/components/lb/setup.ftl
-Don't include conditions which aren't enabled 
Implementation of https://github.com/hamlet-io/engine/pull/2011
- https://github.com/hamlet-io/engine/pull/2011
- None
- None
=> feat(lb): add support for enabling/disabling conditions

aws/components/correspondent/id.ftl, aws/components/correspondent/setup.ftl, aws/components/correspondent/state.ftl, aws/services/pinpoint/id.ftl, aws/services/pinpoint/resource.ftl
- Adds support for defining channels for push notification services on pinpoint
Implementation of https://github.com/hamlet-io/engine/pull/2012  which allows for the configuration of push notification services in pinpoint 
Tested locally
- None
- None
- None
=> feat(correspondent): add support for AWS pinpoint channels

aws/components/apigateway/setup.ftl
With the introduction of the need for an IP Address Group to be explicitly provided, the generation of resource policies needs
to deal with the possibility that the IP address groups include public access.
Avoids an  always true statement in the resource policy.
- None
- None
- None
=> fix(apigateway): handle open ip address groups

aws/components/lb/setup.ftl, aws/components/lb/state.ftl
- Ensure alerts added to any occurrence in an lb are created
After adding the backend subcomponent adding alerts was missed
Tested locally
- None
- None
- None
=> fix(lb): create alerts across all occurrences

aws/extensions/runbook_image_push_result/extension.ftl, aws/extensions/runbook_registry_destination_image/extension.ftl, aws/extensions/runbook_registry_destination_image_tag/extension.ftl, aws/extensions/runbook_registry_destination_object/extension.ftl, aws/tasks/aws_ecr_docker_login/id.ftl, aws/tasks/aws_s3_download_object/id.ftl, aws/tasks/aws_s3_upload_object/id.ftl, aws/tasks/task.ftl
- Adds AWS specific tasks and extensions for managing images via runbooks
This includes the specific image management tasks required when working with AWS based registries 
Tested locally
- None
- None
- None
=> feat: adds extensions and tasks for image management

aws/components/healthcheck/id.ftl
- add the iam service to the setup routine to ensure the service macros are available
Template generation failing to run
Tested locally
- None
- None
- None
=> fix(healthcheck): add iam service to setup

aws/components/directory/state.ftl, aws/services/ds/resource.ftl
- Add default security group string to allow for configuration exceptions to be raised properly
- Fixes typos and alignment of variables used when setting up AD connectors
Template generation was failing and when trying to guess configuration I couldn't get exceptions on misconfiguration
Tested locally
- None
- None
- None
=> fix(directory): handle missing config connector

aws/components/lambda/setup.ftl, aws/components/lb/id.ftl, aws/components/lb/setup.ftl, aws/components/lb/state.ftl, aws/services/lambda/resource.ftl, aws/services/lb/resource.ftl
- Adds support for forwarding requests from an lb to a lambda function
This is a feature available for application load balancers that allows for you to generate a HTTP response using a lambda function
Tested locallly
- None
- None
- None
=> feat(lb): lambda backend support for lb

aws/components/baseline/setup.ftl
- Adds support for extensions and custom bucket policy on s3 buckets in baseline
Allows for the creation of custom bucket policies that can be applied across S3 buckets in baseline
tested locally
- None
- None
- None
=> feat(baseline): extension and policy support

aws/components/cache/setup.ftl, aws/components/db/state.ftl, aws/components/docdb/state.ftl
- When a component that uses an engine to find the port fails provide a better error message so you can determine the component that has caused the issue
Make it easier to figure out what's going on with these errors occur
- None
- None
- None
=> fix: error messages for port lookups

aws/components/dnszone/setup.ftl, aws/services/cw/resource.ftl, aws/services/efs/resource.ftl, awstest/modules/fileshare/module.ftl
Some minor updates across various AWS resources inline with deployment testing 
- Update the dependency management for cloudwatch log subscriptions
- Fix tagging for access points used in EFS 
- Deployment subset check for resources created in a DNS zone
Template deployments were failing
Tested locally and included test cases 
- None
- None
- None
=> fix: minor resource fixes

aws/components/image/setup.ftl
- replace the current registry script with one that uses the repository provisioned in the CFN template
Aligns with the expected process for managing images using the image component
TEsted locally
- None
- None
- None
=> fix(image): use container repository for images

aws/components/filetransfer/setup.ftl, aws/extensions/user_ses_smtp_permissions/extension.ftl, aws/inputseeders/aws/masterdata.json, aws/modules/ses_smtp_user/module.ftl
Some minor fixes found during day to day work 
- Remove the use of  the AppPublic attribute as it is no longer available 
- Fix log group configuration for filetransfer log subscriptions 
- Fix SES SMTP user module permissions
Fixing up issues found when running deployments
Tested locally
- None
- None
- None
=> fix: minor fixes for filetransfer and ses user

aws/components/globaldb/setup.ftl
- Adds support for enabling and disabling global indexes
Allows for control over how the global indexes are created
Tested locally
- https://github.com/hamlet-io/engine/pull/2041
- None
- None
=> feat(globaldb): add support for enabling indexes

aws/components/mobileapp/setup.ftl, aws/components/mobileapp/state.ftl, awstest/modules/mobileapp/module.ftl
- Aligns the BuildConfig generation process with the move to solution level configuration for mobile app updates
Aligns with the move from settings based mobile app configuration to solution level configuration 
Also includes better validation of values based on the supplied configuration to guide users in what they need to provide
Tested locally
- None
- https://github.com/hamlet-io/engine/pull/2044
- None
=> refactor(mobileapp): build configuration updates

aws/components/mobileapp/setup.ftl
- Copy and paste error in the firebase setup
Template generation failing
Tested locally
- None
- None
- None
=> fix(mobileapp): lookup for firebase properties

aws/services/waf/id.ftl, aws/services/waf/resource.ftl
- Adds support for dynamic values provided in WAFValue Sets 
- Fix support for AndStatement Detection when creating v2 rules
- Fix support for NotStatement when creating v2 rules
- Fixes resource type assignment when translating conditions into MatchSets when separate resources are required
- Adding output mappings for the different resources used in WAF
- Move all mappings for resource types from conditions into a single lookup function
- Replace references to setContext global vars for reference data over to using the reference data function
The main motivation here was to get WAF rule generation working as expected when adding in extra rules from the default. 
Dynamic value …
=> fix(waf): various fixes in WAF Handling

aws/components/directory/setup.ftl, aws/components/network/setup.ftl
- Select what is included in flow log prefixes based on the IncludeInPrefix attribute
AWS Implementation of https://github.com/hamlet-io/engine/pull/2050
Tested locally
- None
- None
- None
=> feat(network): add control over flowlog prefix

aws/components/network/state.ftl
Generate a fatal error if tier networks are not correctly configured.
- avoid ugly freemarker errors
- assist users in correct configuration
- None
- None
- None
=> refactor(network): checks for networked tiers

aws/components/userpool/setup.ftl
- Adds support for solution defined callback/logout urls for the aws userpool implementation
See core change
- None
- https://github.com/hamlet-io/engine/pull/2051
- None
=> feat(userpool): add solution callback urls

.github/workflows/changelog.yml, .github/workflows/release.yml
- Disable changelogs on tags as they can't be generated for detached heads
- use a shared workflow for building and pushing engine image
reduces the duplication across pipelines 
fixes a failing pipeline that isn't required to run 
- None
- None
- None
=> refactor: github action pipelines

aws/components/db/setup.ftl, aws/components/db/state.ftl, aws/components/docdb/setup.ftl, aws/components/docdb/state.ftl
- Adds a fix around zone lookups to enforce MFA if scaling policies are in place
- Check for enabled scaling policies instead of just checking for content
Removes array lookup which was failing and allows for control over enabling/disabling policies as required
Tested locally
- https://github.com/hamlet-io/engine/pull/2072
- None
- None
=> fix(db|docdb): scaling policy handling

aws/components/dnszone/state.ftl
- Fixes an issue where the domain configuration wasn't included properly even when it was detected
Could not control what was included in a domain for the domainzone
Tested locally
- None
- None
- None
=> fix(dnszone): add domain configuration if setup

aws/components/es/setup.ftl, aws/inputseeders/aws/masterdata.json, awstest/inputseeders/awstest/id.ftl, awstest/modules/es/module.ftl
- Update the ES log group setup to fix copy/paste error
Template generation failing when creating log group 
Adding tests help us keep up with maintaining ES components in the future
Tested locally
- None
- None
- None
=> fix(es): log group setup for occurrence

aws/services/ecs/resource.ftl
- When starting a task via an ECS service tag the task with tags assigned to the service
This allows you to use tags to find tasks related to a service
Tested locally
- None
- None
- None
=> feat(ecs): propagate service tags to tasks

aws/components/image/setup.ftl
- Typo in the case statement used to handle image sources
When a registry component was found for an image the process would fail
Tested locally
- None
- None
- None
=> fix(image): case handling for image sources

aws/components/es/setup.ftl, aws/components/es/state.ftl, aws/inputseeders/aws/masterdata.json, awstest/modules/es/module.ftl
- Fixes the format required for the LogPublishing in ES via cfn
- Adds account level deployment group for access policy
The CFN docs aren't too clear on the setup for log publishing, so this aligns with the expected configuration that is outlined in other documentation. 
Tested locally
- None
- None
- None
=> fix(es): logging configuration

aws/services/policy.ftl
- Adds support for the NotAction parameter on policies
- makes action and not action optional with a check that at least one is provided
Useful when creating user based policies where you might want to apply conditional restrictions based on where the user is coming from 
Tested locally
- None
- None
- None
=> feat(iam): add support for not actions on policies

aws/inputseeders/aws/masterdata.json, aws/services/cloudtrail/id.ftl, aws/services/cloudtrail/resource.ftl, aws/services/service.ftl
- Adds support for creating cloudtrail trails
- Adds an account level deployment to create a org or account level provider auditing trail
Supports creating cloudtrail trails to log and monitoring cloud provider activity in AWS 
closes https://github.com/hamlet-io/engine/issues/678
Tested locally and with test depoyment
- None
- None
- None
=> feat(cloudtrail): Add support for cloudtrail

aws/components/userpool/state.ftl
- Add support for enabling and disabling the hosted ui
Support for replacing the hosted ui setup when changing the hostname
- https://github.com/hamlet-io/engine/pull/2078
- None
- None
=> feat(userpool): control hosted ui setup

aws/services/s3/resource.ftl
- Adds the filter option for replication rules
- Adds priority rules for handling rule conflicts 
- Makes the prefix parameter optional 
- Allows for replication to multiple destinations as well as tag based filtering of objects
Tested locally
- None
- None
- None
=> feat(s3): add support for replication v2

aws/components/userpool/setup.ftl
- Allow for adding a defined email address when using SES for email handling
This supports using domain based identities as well as applying display names to the email addressed used in sending emails from cognito.
Tested locally
- None
- None
- None
=> feat(userpool): define email from address

aws/components/image/id.ftl, aws/components/image/setup.ftl, aws/services/ecr/resource.ftl, aws/services/image/resource.ftl
- Adds support for lifecycle policies, encryption at rest and tag immutability control on a repository
- Adds outputs for the image resource so that it can be used in format handling for output writing
The policies and configuration added in align with the best practices from AWS (Security Hub) around how containers should be managed within repositories
Tested locally
- None
- None
- None
=> feat(ecr): extended repository configuration

aws/components/secretstore/setup.ftl
- If the global component Description field is available apply it to the secret deployed into secrets manager
Makes it easier to understand what secrets are for when you are dealing with a lot of them
Tested locally
- None
- None
- None
=> feat(secretstore): add descriptions on secrets

aws/modules/baseline/module.ftl
- Adds a runbook which will just set the image reference for an image.
- Generally used when rolling back a deployment to a previous image
Tested locally
- None
- None
- None
=> feat(baseline): add image reference update runbook

aws/components/lb/state.ftl
Remove the version lookup on lb components for waf
Missed in removal of WAFv1
Tested locally
- None
- None
- None
=> fix: remove version from waf rule lookup

aws/components/lb/setup.ftl
- Removes an extra check for the version of WAF which is no longer supported
Missed in removal of WAF classic
Tested on deployments
- None
- None
- None
=> fix(lb): remove waf version lookup on lb

aws/modules/ses_mail_sender/module.ftl
- fixes the link to the baseline data bucket which was using the module param
Typo missed when finishing off the module
Tested locally
- None
- None
- None
=> fix(module): update link to basline component

aws/components/lb/id.ftl, aws/components/lb/setup.ftl
- Adds support for using a lambda as a target type for load balancer backends
- Fixes validation for backend that are the instance or ip type
Template generation was failing when trying to use a lambda function as a backend
Tested locally
- None
- None
- None
=> fix(lb): backend support for lambda

aws/modules/baseline/module.ftl
- Align the module baseline cmk extensions with the masterdata ones to ensure that the expected policies are applied by default
Using SES, SNS, SQS delivery with encrypted queues wasn't working
tested locally
- None
- None
- None
=> fix(baseline): add extra policies for cmk

aws/components/es/setup.ftl, aws/components/es/state.ftl, awstest/modules/es/module.ftl
- Adds configuration support node-to-node encryption
- Adds support for enforcing HTTPS at the ES cluster level
- Adds TLS profile configuration support
- Adds custom hostname support
Enables support for configuring the additional security options available in the ES CloudFormation resources and aligns with AWS Security best practices
Tested locally and included tests for validating the configuration. 
- None
- None
- None
=> feat(es): extend encrypotion config and custom endpoints

aws/components/cache/setup.ftl
- Switch to using a number based check for retention period instead of content
Makes it easier to understand and aligns with the AWS implementation
Tested locally
- https://github.com/hamlet-io/engine/pull/2095
- None
- None
=> fix(elasticache): Use number based logic for retention

aws/components/db/setup.ftl, aws/services/rds/resource.ftl
- Adds the ability to export logs generated by rds instances to Cloudwatch logs
While these logs are available from the RDS Console it's easier to query, manage and act on alerts sent through to CloudWatch.
Tested locally
- https://github.com/hamlet-io/engine/pull/2094
- None
- None
=> feat(rds): add support for cloudwatch log export

aws/extensions/runbook_registry_source_container/extension.ftl, aws/extensions/runbook_registry_source_object/extension.ftl
Fixes an issue in the registry pull scripts which wouldn't replace the value properly
Runbook generation would fail on container images
Tested locally
- None
- None
- None
=> fix: container image reference

aws/components/lb/state.ftl
fix from #729 which added support for arrays
attribute returned included default for base paths
Tested locally
- None
- None
- None
=> fix: lb path for state attribute

aws/extensions/runbook_image_pull_result/extension.ftl
- Use the reference provided when pulling an image as the output
The existing reference Id was being used instead of the reference for the image that was pulled
Tested locally
- None
- None
- None
=> fix(baseline): provide correct image for pull

aws/components/userpool/setup.ftl
- Allows controlling the attributes enabled for a schema
Since schema attributes can't be changed after the initial deploy this is useful for managing changes through environments. 
Tested locally
- https://github.com/hamlet-io/engine/pull/2105
- None
- None
=> feat(userpool): enable support for schema attr

aws/components/network/setup.ftl
- Adds errors when ports can't be found for network acl rules
network acls have to have some complexity in the way the ports are defined, at the moment providing the wrong port results in an exception, this moves to errors that are easier to follow
Tested locally
- None
- None
- None
=> fix(network): handling of missing port on acl

aws/services/sqs/policy.ftl
- Fixes lookup of region for sqs kms policy
Policy included Hamlet:Null as a region 
Tested locally
- None
- None
- None
=> fix(sqs): typo in sqs encryption policy

aws/components/apigateway/setup.ftl
Correct access to the the image registry type.
Dumb error
Testing via customer deploy - hence a dumb error slipping through
- None
- None
- None
=> fix(api): image registry type access

aws/components/cdn/setup.ftl
- Fixes the handling of links to custom cache policies
When using an instanced CDN the cachepolicy didn't work as expected 
Tested locally
- None
- None
- None
=> fix(cdn): link to cachepolicy

aws/components/s3/setup.ftl
- Handle links to the cdn component
- Use the baseline profile of the cdn for the oai
Makes it easier to give CDN access to an S3 bucket 
Tested locally
- None
- None
- None
=> fix(s3): inbound link permissions for cdn

aws/components/apigateway/setup.ftl
Use the image info to source the build format, build reference and tag.
Deployments currently failing
Post merge customer site testing
- None
- None
- None
=> fix(api): build info sourcing

aws/components/secretstore/setup.ftl
- Handles a missing cmk for secret store deployments that have been included in a solution before the baseline has been created
Exceptions raised when running a new deployment with a defined solution
Tested locally
- None
- None
- None
=> fix(secretstore): handle missing cmk

aws/components/ecs/setup.ftl, aws/components/ecs/state.ftl, aws/services/ecs/resource.ftl
- Adds support for disabling the creation of EC2 based ecs hosts if you only want to use fargate
Security hardening, only adds EC2 based configuration if you need it  
Tested locally
- (https://github.com/hamlet-io/engine/pull/2113)
- None
- None
=> feat(ecs): control if ec2 asg should be created

aws/components/lb/setup.ftl
- handle default and _default as priority options
- Mixup between the docs and what is implemented that meant that the priority wasn't picked up
tested locally
- None
- None
- None
=> fix(lb): handle the documented lb default priority

aws/components/mta/setup.ftl
Implementation of https://github.com/hamlet-io/engine/pull/2116
Makes rule handling easier to understand
Tested locally
- None
- None
- None
=> feat(mta): stop after match

aws/components/user/setup.ftl
Add ability to limit IP addresses from which requests can come for a user.
- tighter security policies for IAM users
- https://github.com/hamlet-io/engine/pull/2120
- None
- None
=> feat(user): source IP filtering

aws/components/datafeed/setup.ftl
Ensure all fatal errors are wrapped in a check for the subset.
The lg pass was failing if the datafeed couldn't be deployed.
- None
- None
- None
=> fix(datafeed): support subset passes

aws/components/userpool/setup.ftl, aws/components/userpool/state.ftl, aws/services/waf/id.ftl, aws/services/waf/resource.ftl
- Add userpool association for WAF
- Add support for CAPTCHA and CHALLENGE WAF actions
- Fixes some ARN lookups and output id saving for waf
AWS implementation of https://github.com/hamlet-io/engine/pull/2122
Tested locally and on native deployment
- None
- None
- None
=> feat(waf): enable waf and add challenges

aws/components/topic/setup.ftl
AWS implementation of https://github.com/hamlet-io/engine/pull/2127
Make it easier to setup subscriptions 
Tested locally
- None
- None
- None
=> feat(topic): add fixed endpoint subscriptions

aws/components/lb/setup.ftl
Adds support for registering instances with a load balancer using a static target
Makes it easy to work with instance type load balancing
Tested locally
- None
- None
- None
=> feat: instance type support for lb

aws/extensions/cmk_sqs_access/extension.ftl
Add SQS KMS key access that was added before but the extension wasn't added in 
Gives SQS access to the cmk for SSE KMS
Tested locally
- None
- None
- None
=> fix(baseline): add sqs extension

aws/components/correspondent/setup.ftl
Makes sure correspondent resources aren't included in resource sets
Extra resources being added into resource set deployments
tested locally
- None
- None
- None
=> fix(correspondent): only deploy for right template type

.github/workflows/changelog.yml, .github/workflows/release.yml
Updates the shared github workflows used to the latest version
Resolves a bug in the changelog generation and moves to using the latest nodeJS version in the actions
- None
- None
- None
=> chore: update actions pipelines

.github/workflows/changelog.yml
Updates the shared github workflows used to the latest version
Resolves a bug in the changelog generation and moves to using the latest nodeJS version in the actions
- None
- None
- None
=> fix: changelog pipeline

.github/workflows/release.yml, aws/services/cf/resource.ftl
Minor fix to correctly process ConnectionTimeout attribute in Origin configuration for CloudFront.
Locally
- None
- None
- None
=> fix: connectionTimeout attribute

aws/services/waf/resource.ftl
Allows for the creation of WAFv2 IP Sets that use IPV6 as well as the existing IPV4 configurations.
To use this, it is expected that a unique IPAddressGroup is defined for IPv6 addresses, separate to IPv4 addresses.
I need to whitelist a series of IPV6 CIDRs in an existing project, and it needs to be a non-breaking change so as to not impact other solutions.
It has not been tested.
n/a
- None
- None
- None
=> feat: waf service to support IPV6 CIDRs
