aws/components/userpool/setup.ftl
minor fix to the userpool alias syntax which wasn't compatible freemarker.
We hadn't seen this before as it only occurs when the email alias isn't used in a userpool. Which is pretty uncommon
generated user pool test
none
=> <fix> userpool alias syntax

aws/components/apigateway/setup.ftl, aws/components/network/setup.ftl, aws/components/template/id.ftl, aws/components/template/setup.ftl, aws/components/template/state.ftl, aws/deploymentframeworks/cf/output.ftl, aws/services/cfn/id.ftl, aws/services/cfn/resource.ftl, aws/services/service.ftl, aws/services/vpc/resource.ftl
Part of: https://github.com/hamlet-io/engine/pull/1281
Companion PR https://github.com/hamlet-io/engine/pull/1281  
This PR introduces the template component to the aws core plugin. It allows you to integrate a predefined cloudformation template into the hamlet delpoyment process. 
You can define the parameters for the template using either solution level configuration or you can use the standard settings,links and fragment configuration option. **Note** all default settings are disabled by default 
The source template is treated like a code unit and is expected to be packaged using the scripts aretefact/registry type. When deployed the scripts are copied to the opsdata S3 bucket and then deployed using a nested template that we generate in Hamlet. 
This approach allows us to define the …
=> <feature> template resource

aws/components/network/setup.ftl
minor fix to restrict when  the subnet list outputs are included in templates
Without this PR the ouputs were being added to all segment level outputs not just the network one
tested in local deployment
=> <fix> only add subnet outputs in network component

aws/components/cdn/state.ftl
Minor fix to the CDN Route URL attribute
The url was being formatted as an absolute path so included a slash at the start. This is an invalid URL 
Tested in local deployment 
- [X ] Bug fix (non-breaking change which fixes an issue)
=> <fix> CDN Route attribute formatting

aws/services/cfn/resource.ftl
Always add the ref output to the cfn Netsted template resource
Since our processing assumes that at least one resource in a component will have an output we need to make sure that Nested templates always have one. This is important since the rest of the outputs are dynamic so in some templates you might not want to map any of the outputs 
tested on local deployment with links enabled ( See https://github.com/hamlet-io/engine/pull/1289 for the link fix)
=> <fix> default output for template resource

aws/components/apigateway/setup.ftl, aws/components/cdn/setup.ftl, aws/services/waf/resource.ftl
Add support for blacklisted and whitelisted geo matches in WAF configurations.
This will permit regional APIs to to geoblocked.
Via deployment
=> <feature> WAF GeoMatch support

aws/components/template/state.ftl
Fixes the mapping setup for template outputs to attributes
only returning the ref attribute
Tested locally
=> <fix> template output mapping to attributes

aws/components/baseline/setup.ftl
OAIs can now list buckets so that S3 returns 404 not 403 for missing objects.
If a cloudfront distribution for an SPA needs to be whitelisted, the logical apporach is to use WAF. However while WAF will return a 403, this is converted to a 200 and content displayed if an error page against a 403 code is configured. 
At present we configure the 403 by default for error pages because of the default S3 behaviour.. By giving the OAI additional permissions, S3 will return a 404 not a 403, the error page need only be configured for a 404, and WAF will work as expected.
=> <refactor> Expand the S3 permissions given to OAI

aws/components/db/setup.ftl
When generating templates for hibernation we need to remove all references to the database. This PR ensures that alarms don't get Ref lookups
Allows templates to be conformant with Cloudformation requireemnts 
TEsted in a deployment
=> <fix>remove reference lookup on hibernate templates

aws/components/db/setup.ftl
Use the name of the RDS instance when creating alerts for hibernated  db instances. 
This allows for alarms to be retained during hibernation activities 
tested locally
=> <fix>db use name for hibernated alerts

aws/components/userpool/setup.ftl, aws/components/userpool/state.ftl
use spaces as separators for user OIDC scopes instead of ',' 
This aligns with the standard and what Cognito expects for its configuration.  Not sure why this was found earlier, but maybe we haven't used multiple scopes
=> <fix> userpool scope seperators

aws/components/userpool/setup.ftl
Only call the cfResource macro during component subset for userpool resources 
Deploying in other subsets was overriding and breaking the userpool configuration
Tested with product deployment
=> fix: check component subset for cfn resources

aws/services/ec2/resource.ftl, test/run_aws_template_tests.sh
Minor fix to create directories before they are used by other boot strap scripts
Found that logging on the other bootstrap scripts were failing because /var/log/codeontap was missing. Turns out it was being created after the boostrap process was run.
Tested on an active deployment
=> fix: init configuration ordering for ec2

aws/components/userpool/setup.ftl, aws/services/cognito/resource.ftl, test/run_aws_template_tests.sh
Add support for userpool federation with the public based identity providers, Google, Apple, Facebook and Amazon 
Extends the login configuration support which is a lot easier now that cfn supports them all 
Tested with a pass of the userpool for syntax, have not tested with these providers as  I didn't have an app which was configured with the providers
=> feature: public identity providers

aws/components/userpool/setup.ftl
- Use contentIfContent so correct selection of provided values occurs
- Preference environment values to solution values
- Use concatenate to generate environment keys to support SettingsPrefix being an empty string.
- authorise_scopes examples show a space separated list not an array. An array doesn't work well with environment provided values either.
Bug fixes
=> fix: Auth provider configuration defaulting logic

aws/components/userpool/setup.ftl, aws/components/userpool/state.ftl
Adds support for saving the user pool client secret as an encrypted pseduo stack so that the can be provided to other components 
Allows for secure storage of the userpool client secret so that it can be used by other components
=> feature(userpool): get client secret on deploy

aws/components/gateway/setup.ftl, aws/components/gateway/state.ftl, aws/components/network/setup.ftl, aws/services/vpc/id.ftl, aws/services/vpc/resource.ftl
Adds support for link based network gateways using the `endpoint` engine type 
Adds support for all of the routing endpoints supported through Cloudformation Ec2:Routes using link based components. This allows them to be deployed manually via the console while still integrating with the hamlet deployed network
Allows for integration of complex network component setups like peering which are difficult to cooridinate with infrastructure as code deployments as they require two parties to setup the infrastructure at the same time. With the endpoint engine the details of the peering connection can be provided through an external component attribute. This can also be extended to support linking to other components which offer routing services such as vm instances or network interfaces
Tested on …
=> feature(gateway): link based gateway support

aws/components/es/setup.ftl, aws/components/gateway/setup.ftl
A couple of fixes 
- lookup for service role when not using subsets in ES Cognito integration 
- Add exception based on gateway engine type for missing configuration
- ES failing to deploy using current cognito configuration when not using a subset 
- Other gateway endpoints failing to generate as the gateway configuration requried the endpoint specific configuration
Tested on deployment
=> Gateway endpoint es role

aws/components/cdn/setup.ftl, aws/components/mobileapp/state.ftl
Supports OTA updates for mobile apps on an CDN to follow the path of the CDN route rather than defining its own path 
Currently the mobile app to CDN route uses the S3 component which requires you to use the core relative path of the mobile app to serve the OTA content. The OTA currently locks the path the OTA is available on to the core relative path of the mobile app. This means that you can't use the CDN route paths to control where the OTA is served from publically
Tested on a live deployment
=> feat(mobileapp): OTA CDN on Routes

aws/components/cdn/setup.ftl
Removes overriding the S3 origin endpoint when an S3 component has website hosting enabled. 
This isn't actually supported by CloudFront and the deployment fails
Tested on deployed environment
=> fix(cdn): dont use s3 website endpoint in s3 backed origins

aws/components/cdn/setup.ftl
Each CDN route requires at least one behaviour to link the frontend to the origin. This adds a behaviour for the mobile ota link
CDN route wasn't working
=> fix(cdn): add behaviour for mobile ota

aws/components/apigateway/setup.ftl
Adds support for configuring the security policy on a custom domain name on API Gateways. Also aligns setup with https://github.com/hamlet-io/engine/pull/1320 to show that there are two HTTPS profiles on an API Gateway
When using regional API without CloudFront you still need to be able to set the Security Profile. This also ensures that if you are using CloudFront the link between the API Gateway and the Cloudfront distribution is secured as required
=> feat(apigatewa): add TLS configuration for domain names

aws/components/configstore/setup.ftl, aws/components/globaldb/id.ftl, aws/components/globaldb/setup.ftl, aws/components/globaldb/state.ftl, aws/services/dynamodb/resource.ftl
AWS Implementation of https://github.com/hamlet-io/engine/pull/1325 
Supports the provisioning of globalDbs using the AWS DynamoDB service 
Allows for the deployment and control of system level configuration of DyanmoDB Tables 
Tested locally using active deployment
=> feat(globaldb): initial support for the globalDb component

aws/services/ecs/resource.ftl
Adds support for udp based port mappings in task definitions
The default is to use tcp and didn't allow for setting udp based port mappings
=> feat(ecs): support udp based port mappings

aws/components/gateway/id.ftl, aws/components/gateway/setup.ftl, aws/components/gateway/state.ftl, aws/components/network/setup.ftl, aws/components/network/state.ftl, aws/components/router/id.ftl, aws/components/router/setup.ftl, aws/components/router/state.ftl, aws/services/resourceaccess/id.ftl, aws/services/resourceaccess/resource.ftl, aws/services/service.ftl, aws/services/transitgateway/id.ftl, aws/services/transitgateway/resource.ftl, aws/services/vpc/id.ftl
AWS support for https://github.com/hamlet-io/engine/pull/1327 
Adds the router component based on the AWS Transit Gateway service. The router deployment itself is a single transit gateway with a single route table. 
The attachment and routing of networks on the Transit gateway is managed by the gateway service. The gateway service should link to a router and based on this the gateway will attach to the transit gateway, route propagation is enabled by default to reduce the configuration required for the networks. 
Adds support for using AWS Resource Access Manager which allows for sharing specific resources between AWS accounts, in this case allows sharing the router between different accounts to form a network mesh between different AWS account VPCs
Supports routing between different AWS …
=> Router component

aws/components/router/setup.ftl, aws/services/transitgateway/resource.ftl
Always specify the BGP ASN for a transit gateway regardless if BGP is enabled or not
When deploying a transit gateway if you don't specify the BGP ASN the default ASN is assigned. This ASN happens to be the same ASN assigned on Customer gateways which AWS doesn't support and so using the defaults causes the deployment to fail
Tested on local active deployment
=> fix(router): Always set ASN on transit gateway

aws/components/mobileapp/state.ftl, aws/components/userpool/setup.ftl
A couple of fixes to permit an iam or lg pass when componets are yet to be created.
iam and lg subsets are often run before their corresponding components are created.
=> fix: Permit iam/lg pass for uncreated components

aws/components/apigateway/setup.ftl, aws/components/spa/setup.ftl
Tweak apigateway and spa so iam/lg passes can be run before component are created.
iam and lg passes need to berun before components are created.
=> fix: Permit iam/lg passes before component created

aws/services/transitgateway/resource.ftl
Reduces tags on transit gateway down to name only
This has been done for a couple of reasons
- Updates to tags actually replace the transitgateway components ( why??? ) 
- There is a known issue ( confirmed with support case ) where tag updates to transit gateways in change sets cause the stack update to fail 
We currently include the configuration reference ( jenkins job number if run on Jenkins ) 
=> fix(transitgateway): remove dynamic tags from cfn updates

aws/components/gateway/setup.ftl
Replace route propagation for transit gateway links to VPC with a static route 
An account who has had a transit gateway shared with it can create attachments and routes on the transit gateway but cannot create propagations 
This approach moves to using static network routes instead. Since we have the localnet IP address group this is easy to manage and if required finer grain subnets can be configured using this approach as well
=> Static transit routes

aws/components/gateway/setup.ftl, aws/components/gateway/state.ftl, aws/components/router/id.ftl, aws/components/router/setup.ftl, aws/components/router/state.ftl
Implements https://github.com/hamlet-io/engine/pull/1331 for AWS 
To implement this you need to create a couple of things 
In the client account:
- An external service with the transitGateway Id set as the TRANSIT_GATEWAY_ID attribute 
- A Gateway using the router engine with a link to this external service 
This will attach the client VPC to the Transit Gateway 
In the owner account:
- A router component 
- An external service with the transitGateway Attachement from the client Id as TRANSIT_GATEWAY_ATTACHMENT attribute 
- An IP address group which represents the client VPC Network 
- A Static Router on the router which links to the external Service for the transit gateway attachment
Allows for transit gateways shared between two AWS accounts, the account who has received the transit …
=> feat(router): support for static routes

aws/components/lb/setup.ftl, aws/services/lb/resource.ftl
Adds support for TLS offload on Network load balancers. 
This allows you to use a network load balancer for limited HTTPS communication along with TCP communication. Really helpful for services which are offered by a privateservice as they only support Network Load Balancers 
=> feat(lb): Support for Network load balancer TLS offload

aws/components/privateservice/setup.ftl
Minor fix to only check for load balancers during the private service subset
Allows for iam and lg subsets to work when components haven't been deployed
Tested locally
=> fix(privateservice): only error during subset

aws/components/gateway/setup.ftl
Adds support for controlling DNS private zone creation on a per gateway basis ( implements https://github.com/hamlet-io/engine/pull/1333 )
When using customer created vpc endpoints that require acceptance the DNS private zone cannot be created until the endpoint has been accepted. I guess its a security thing as this could potentially expose who or what a service is that you might not be allowed to access
=> feat(gateway): private dns configuration

aws/components/lb/setup.ftl, aws/services/lb/resource.ftl
Implements routing to static endpoints defined in https://github.com/hamlet-io/engine/pull/1334
When a LB Port links to an external service endpoint it uses the IPAddressGroups and Port defined on the endpoint to create a fixed target in the load balancer Target group. This is support for both application and network load balancers
CIDR ranges will be converted to individual hosts - this can be useful if you have floating addresses, you will get quite a few failed endpoints though 
When using Private Services you might want to offer an on-premis service to other Networks. This allows you to define this external service as a target in the Network load balancer used to offer the the private service. This removes the need for a proxy service deployed in the VPC which proxies this traffic. …
=> feat(lb): static targets

aws/components/gateway/setup.ftl, aws/components/gateway/state.ftl, aws/inputsources/shared/masterdata.ftl, aws/masterData.json
Implements https://github.com/hamlet-io/engine/pull/1335 for aws 
- Support for both the vpcendpoint and privatesevice engines 
- Prefer using privateservice instead of vpcendpoint
- Create security groups ingress rules for private services based on the specified destination ports 
- More understandable naming of gateway engine type
- Security focussed control of security groups
=> feat(gateway): add support for destination port configuration

aws/components/lb/setup.ftl
minor fix on the param naming for static targets
Was failing as the param name was wrong
Tested locally
=> fix(lb): minor fix for static targets

aws/components/gateway/setup.ftl
Minor fix to allow routes for shared transit gateways to be created when there is an external transit gateway
I think this was a copy and paste issue while I was setting it up. Routes on the VPC should always be created
=> fix(gateway): remove local route check for adding VPC routes

aws/inputsources/shared/masterdata.ftl
Sets the default vpcendpoint port list to http and https
Minor hardening fix to set the ports for the default vpcendpoint to http and https only. This also applies a workaround to a recent change to the security group ids which meant that the ingress rule for any port was removed 
tested on local deployment
=> fix: set destination ports for default private service

aws/services/s3/resource.ftl
Minor fix to the generation of the bucket encryption configuration on S3 
Buckets were failing to generate without encryption as the variable wasn't available for the bucketencryption config
Tested locally
=> fix(s3): fix for buckets without encryption

aws/components/lambda/setup.ftl
Ensure that no environment variables are added to a lambda@edge function.
Make the text of a couple of error messages more explicit.
If all the macros controlling output of environment variables weren't explicitly set in the lambda@edge function fragment, some variables could still be set.
=> fix: Force lambda@edge to have no environment

aws/components/baseline/setup.ftl, aws/components/bastion/setup.ftl, aws/components/computecluster/setup.ftl, aws/components/datafeed/setup.ftl, aws/components/ec2/setup.ftl, aws/components/ecs/setup.ftl, aws/components/s3/setup.ftl, aws/components/s3/state.ftl, aws/services/kms/policy.ftl, aws/services/s3/resource.ftl
AWS provider specific implementation of https://github.com/hamlet-io/engine/pull/1347 
Adds support for enabling S3 encryption on baseline data buckets, and s3 components 
Updates s3 link policies and baseline policies to provide the appropriate permissions required by clients to access the KMS key for CMK based encryption
This supports security hardening best practices which is to enable encryption at rest on services where possible
Tested locally on a new deployment
=> feat: S3 Bucket encryption

aws/components/bastion/setup.ftl, aws/components/bastion/state.ftl, aws/components/cache/setup.ftl, aws/components/cache/state.ftl, aws/components/computecluster/setup.ftl, aws/components/computecluster/state.ftl, aws/components/datapipeline/setup.ftl, aws/components/datapipeline/state.ftl, aws/components/db/setup.ftl, aws/components/db/state.ftl, aws/components/ec2/setup.ftl, aws/components/ec2/state.ftl, aws/components/ecs/setup.ftl, aws/components/ecs/state.ftl, aws/components/efs/setup.ftl, aws/components/efs/state.ftl, aws/components/es/setup.ftl, aws/components/es/state.ftl, aws/components/externalnetwork/state.ftl, aws/components/gateway/setup.ftl, aws/components/gateway/state.ftl, aws/components/lambda/setup.ftl, aws/components/lambda/state.ftl, aws/components/lb/setup.ftl, aws/components/lb/state.ftl, aws/inputsources/shared/masterdata.ftl, aws/masterData.json, aws/services/rds/resource.ftl, aws/services/vpc/id.ftl, aws/services/vpc/resource.ftl
This PR implements network Profiles as outlined in https://github.com/hamlet-io/engine/pull/1346 and also provides solution level control of ingress and egress rules for components which have security groups and are part of a VPC 
All security groups are now created to explicitly deny inbound and outbound connections, by default AWS restricts inbound access but denies outbound access. 
To create rules in the security group there are 3 methods 
- Network profile - this sets global security group rules that are applied across all components configured to use a given profile. The default profile allows all outbound access and also allows inbound access to all services from the default bastion instance
- Links/Roles - All components with a security group now have an inbound and outbound …
=> Network Profiles and Ingress/Eggress Security Groups

aws/services/vpc/resource.ftl
Minor fix to filter empty content from Security group and CIDR Arrays
When linking to a component which hasn't been deployed you can still access the role information. This role information could contain an empty string as most roles are populated with getExistingReference 
Tested locally
=> fix(vpc): Check network rule array items for content

aws/components/efs/state.ftl
Minor fix in EFS mounts to lookup the networkacl roles from the parent.
It was borked
Tested locally on deployment
=> fix(efs): networkacl lookup from parent

aws/components/computecluster/setup.ftl, aws/components/ec2/setup.ftl, aws/components/ecs/setup.ftl
A minor fix for passing the groupId to ingress rule creation
With the recent changes in #73 we have now split the groupId references and the CIDR ranges to separate parameters. This wasn't caught in some of the places we use the ingress rule macro 
Tested locally
=> fix: security group references for security groups

aws/components/bastion/setup.ftl, aws/services/rds/resource.ftl
A couple of minor fixes in bastion component and rds service 
- bastion: set a default for publicRouteTable so that it works in all subsets
- bastion: remove duplicate allocation of EIP script 
- rds service: support string or in in RDS size setting
Minor fixes to support subsets and quality of life settings
Tested locally
=> Fixes: bastion and RDS

aws/components/cache/setup.ftl
Minor fix on cache security group to remove the networkProfile parameter
Shouldn't be specified, this is a bug from #73 
Tested locally
=> fix(cache): remove networkprofile param from security group

aws/components/lambda/setup.ftl
Minor fix on lamda security groups created from links to to check vpc access flag first
Shouldn't be specified, this is a bug from #73
=> fix(lambda): check vpc access before creating security groups from links

aws/services/vpc/resource.ftl
Force the port range to the AWS required one when using the all protocol
Our port objects require a port range, however if you use the all protocol AWS needs the range to be specified as -1 to -1. This change enforces it to align with our port objects
There also seems to be a weird bug in cloudformation where if you pass the IPProtocol as -1 and specify ports the rule is added then removed 
Tested locally on deployment
=> fix(vpc): support any protocol sec group rules

aws/components/computecluster/setup.ftl, aws/components/datapipeline/setup.ftl, aws/components/db/setup.ftl, aws/components/ec2/setup.ftl, aws/components/ecs/setup.ftl, aws/components/efs/setup.ftl, aws/components/es/setup.ftl, aws/components/gateway/setup.ftl, aws/components/lambda/setup.ftl, aws/components/lb/setup.ftl, aws/services/vpc/resource.ftl
Implements https://github.com/hamlet-io/engine/pull/1351 to provide a way to disable egress rule creation and instead rely on the implicit rules added by AWS ( allow any/any ) 
There is some strange behaviour in AWS with Cloudformation Egress rules 
- Create an egress rule with explicit rules ( IP, Port etc ) 
- AWS will remove the default egress rule they automatically add ( 0.0.0.0/0 any ) 
- Add an explicit egress rule which allows all outbound access ( 0.0.0.0/0 any ) 
- Add another rule as an extra egress rule to the group
- The explicit egress global rule for global outbound access will be removed 
This kind of makes sense since the 0.0.0.0/0 rule wins over all the other rules, and since this is provided by default why would you want add this explicitly with other egress rules ( Sec …
=> Outbound Network Profile control

aws/components/ecs/setup.ftl, aws/components/s3/state.ftl, aws/services/cw/resource.ftl
Some fixes for naming in ecs and S3 components 
- S3 - Only allows s3 buckets to be 63 characters long - since we append the segment seed to the end of the bucket we have some room to truncate bucket names so they fit into this while still being unique 
- Cloud watch alarms 
- change formatting a little to try and make the alarm names easier to follow 
- When creating a scaling alarm include the name of the resource that is being scaled along with the resource that its tracking. This ensures alarm names are unique 
=> fix: naming fixes for large deployments

aws/components/lb/state.ftl
Truncate the name for the load balancer if it doesn't meet the AWS requirements
AWS load balancer names are currently limited to 32 characters, since we form names based on the full occurrence structure and the name has to be unique to region and account this can be hard to know as a requirement until you deploy the load balancer and it fails. If you need to shorten the name you sometimes end up redeploying the whole segment since the name might need to be shortened 
Load balancers still support tagging so you can use a proper name here, this is just the name property
Tested locally
=> fix(lb): ensure lb name meets aws requirements

aws/components/bastion/setup.ftl, aws/components/ecs/state.ftl, aws/components/gateway/setup.ftl
Only error on network not existing when deploying the resources which require a network
Currently we throw an error if the network doesn't exist for an overall component. The network not be available is only a problem when you deploy resources which require it. If you try to do subset deployments while these components are defined in a solution but there isn't a network the subset will fail to generate
Tested locally
=> fix(segment): network deployment state lookup

aws/components/ecs/state.ftl
Replace the name state for the ecs service with ARN
Name wasn't working as expected
Tested locally
=> fix(ecs): name state for ecs service

aws/services/ssm/policy.ftl
Minor fix on SSM policies which don't use a KMS key that we manage for S3 access logging
Access was being denied for SSM sessions
Tested locally
=> fix: s3 encrypted bucket policy for ssm

aws/components/lb/state.ftl
Adds a network acl role for the lb network engine based on the tier based subnet lookup added in https://github.com/hamlet-io/engine/pull/1359 
AWS Network load balancers don't support the standard security group references in network security group rules which permit access to the load balancer. So instead for egress rules we need to provide the subnets the load balancer lives on for access
Tested locally
=> feat(lb): add networkacl support for network engine

aws/components/baseline/setup.ftl, aws/components/s3/id.ftl, aws/components/s3/setup.ftl, aws/components/sqs/setup.ftl, aws/components/sqs/state.ftl, aws/services/sqs/id.ftl
A collection of fixes for SQS and S3 Notifications
- Moves all resource policies for SQS into the queue, we had some policies created by other components, mostly S3 notifications 
- creates a single resource creation for the SQS policy containing all statements 
- Some subset fixes for creating S3 notifications on baseline S3 buckets
This introduces a breaking change, when using S3 notifications to an SQS queue either from baseline or the s3 component the queue you are linking the notification to needs to have an inbound link configured to allow the S3 bucket to send messages to the queue.
To manage the change a configuration parameter must be set on each notification  `aws:QueuePermissionMigration` to acknowledge that the queue policy has been applied
E.g. 
**Bucket**
```
"quarantine-s3" …
```
=> fix(sqs): move policy management for a queue into the component

aws/components/lb/state.ftl, aws/services/lb/resource.ftl
Adds support for monitoring and autoscaling using the LB Targetgroup
A recommend metric for autoscaling web containers is `RequestCountPerTarget` which lets you see how many requests on average each target is seeing. In order to support this we need to make the metric dimensions avaialble
Tested locally
=> feat(lb): add LB target group monitoring dimensions

aws/components/s3/setup.ftl
Fix alerting for notification configuration to only happen in the template
We should alert on a pass that you can fix it on 
Tested locally
=> fix: only alert on notifications in S3 template

Jenkinsfile
Enabled concurrent builds and removed wait trigger on triggering docker build 
in the downstream job we now cancel existing jobs when a new one is triggered. This means we can always trigger the latest builds of master plugins and the docker build will restart and use the latest commit
Will test in deplloyment
=> fix: enable concurrent builds and remove build wait

aws/components/userpool/setup.ftl, aws/services/cognito/resource.ftl
Support the configuration of a custom sender email address for cognito.
There is a hard limit of 50 validation emails a day using Cognito's own email address. To go beyond this, a customer domain must be used.
=> Cognito email sender address configuration

aws/components/cdn/setup.ftl
Adds support for a CDN To use a load balancer instead of a load balancer port as an origin
When linking to a load balancer port you can't pass through the same host name from the CDN to the load balancer as the forwarding rules won't line up and the DNS names would point to the same location
When using the load balancer as the origin the internal AWS hostname is used allowing you to forward through to any port rule that has been applied
=> feat(cdn): support links to load balancers

aws/components/ecs/setup.ftl
Adds support for link based ingress rules on ECS tasks and services
For containers which aren't deployed with a load balancer you might want to allow direct access to the container. This allows you to do this using link based rules
Tested with local template generation
- engine: https://github.com/hamlet-io/engine/pull/1370
- engine-plugin-aws: https://github.com/hamlet-io/engine-plugin-aws/pull/110
=> feat(ecs): support ingress links for security groups

aws/components/apigateway/setup.ftl, aws/components/cdn/setup.ftl, aws/components/datafeed/id.ftl, aws/components/datafeed/state.ftl, aws/components/lb/setup.ftl, aws/services/waf/resource.ftl
Implementation of https://github.com/hamlet-io/engine/pull/1366  which enables log forwarding for WAF enabled services
To setup WAF logging you need 
- A datafeed component deployed with a backend configured ( for s3 no lambda transfromation is required, for Elasticsearch this may be required ) 
- The datafeed also needs to be configured as a WAFLogFeed using the `aws:WAFLogFeed` configuration attribute. This changes the name of the deployed firehose to align with WAF setup requireemnts 
- A logging profile which links to this datafeed component 
- Assign this logging profile under the WAF configuration `WAF.Profiles.Logging` 
**note:** if using the same datafeed for multiple WAF endpoints the log files will be stored together, they include a GUID in their file name so this should be safe …
=> feat(waf): enable log waf logging for waf enabled services

aws/components/ecs/setup.ftl, aws/components/es/setup.ftl, aws/inputsources/shared/masterdata.ftl, aws/masterData.json, aws/services/ec2/id.ftl, aws/services/iam/id.ftl, aws/services/iam/resource.ftl
Aligns the current component setups with the new Service Linked roles in https://github.com/hamlet-io/engine/pull/1368 
- Adds support for creating service linked roles via cloudformation
- Refactors exising service linked role support to align with this process 
- Adds KMS key id for volume encryption 
To standardise and control how service linked roles are setup in accounts and remove the need for each component to check that the role exists if it is required
Tested locally
=> Service linked roles

aws/components/lambda/setup.ftl
Fix macro parameter for lambda log watchers
Was broken with recent changes to log subscriptions #87 
Tested locally
=> fix(lambda): log watcher subscription setup

aws/components/userpool/setup.ftl, aws/services/cognito/resource.ftl
AWS implementation of https://github.com/hamlet-io/engine/pull/1380 to allow for control over OAuth on user pool app clients
When configuring an identity pool you must provide at least one client, this allows you to create a client for the identity pool without having to specify oauth configuration 
=> feat(userpool): disable oauth on clients

aws/inputsources/shared/masterdata.ftl
Minor bug fix to enable the iam segment resource set. 
It was disabled during testing and I forgot to turn it back on 
Tested locally
=> fix: enable segment iam resource set

aws/components/dataset/state.ftl, aws/components/ecs/setup.ftl, aws/inputsources/shared/masterdata.ftl, aws/masterData.json
AWS Implementation of https://github.com/hamlet-io/engine/pull/1381
Includes the deployment group as part of the occurrence filtering on ecs subcomponents
Allows for user controlled deployment groups to handle ordering deployments 
- Requires : https://github.com/hamlet-io/engine/pull/1381
=> feat(ecs): use deployment group filters on ecs subcomponents

Jenkinsfile, awstest/scenarios/lb.ftl, test/run_aws_template_tests.sh
Updates the AWS test template generation script to use the new unit list format based on the provided management contract format. Now that we know the deployment group that all units belong to also remove the `|| true` return on template generations so we know when template generation fails
The introduction of the management contract provides better understanding of the units available in a deployment. This allows us to generate test templates in a more  efficient way. It should also allow us to catch problems when they occur at any stage in template generation
- Depends on -  https://github.com/hamlet-io/executor-bash/pull/87
=> Fix testing

aws/services/ecs/resource.ftl
AWS implementations of https://github.com/hamlet-io/engine/pull/1396 
- Adds support for setting the container hostname 
- Fixes the docker volume configuration to align with user control over the volume
- Adds support for [placement constraints](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-placement-constraints.html) Which allow you to restrict where a task is placed based on the labels assigned to either the ecs host or the task. For example `attribute:ecs.availability-zone == ap-southeast-2a` would only allow the task to be placed on an ec2 ecs host in ap-southeast-2a
Provide greater control over ECS tasks definitions
- https://github.com/hamlet-io/engine/pull/1396
=> Ecs advanced features

aws/components/federatedrole/setup.ftl
Minor fix to use the right component type when checking for subset deployment
Noticed it while debugging another issue
Tested locally
=> fix(federatedrole): fix deployment subset check

aws/components/apigateway/setup.ftl
Copy the api specification to a subpath of the settings for any lambda authorizers used.
The authorizer relies on a copy of the openapi specification to determine various attributes of methods such as scopes and acr.
It thus needs a new copy of the api spec each time it is changed by the api. To achieve this, copy the spec to a specific subpath of the authorizer settings as part of the api deployment.. A subpath ensures other mechanisms such as asFile or config do not interfere with the copied spec.
=> feat: sync authorizer openapi spec with api

aws/components/lambda/setup.ftl
When syncing asFiles to S3, ignore any reference files provided by other deployments.
The initial use case is to permit the openapi.json file provided by the api gateway to not be affected by redeployments of the lambda authorizer.
=> fix: don't delete authorizer openapi.json file

aws/components/spa/state.ftl
Ensure the spa state routine can handle the situation where the baseline component has not yet been deployed.
With changes to the way units are grouped, all unit state routines are called as part of component flow. Thus their state routines need to be able to cope with their dependencies not yet being created.
=> fix: spa state handles no baseline

aws/components/baseline/setup.ftl, aws/components/baseline/state.ftl, aws/components/s3/setup.ftl
Enables replication of the baselinedata buckets to a linked s3 component. 
Also removes an error if both buckets are in the same region as AWS have removed this requirement.
It is sometimes desirable to be able to backup or consolidate the data types that are intended for these buckets.
Local template generation and deployment.
* Change will require schema's to be regenerated.
=> Feat - Baseline DataBucket Replication

aws/components/apigateway/setup.ftl
Thus copy the definition and the extended versions of the api spec to the authorizer reference area.
Also improve error detection when publishing specs.
The authorizer needs to know the scopes on methods, but the extended spec needs these removed to comply with AWS constraints.
=> feat: copy openapi definition file to authorizers

aws/components/apigateway/setup.ftl
Use the utility method that formats the definition filename to copy the definition file for authorizers.
This is to ensure consistency with where it is stored in the cmdb.
=> fix: formatting of definition file

aws/components/apigateway/state.ftl, aws/components/lambda/setup.ftl, aws/services/apigateway/resource.ftl
Add an authorize inbound role to the api gateway and support for this role in the lambda component.
The format of the sourcearn for an authorizer is different to that for invoking a lambda from an api call.
=> feat: authorizer lambda permissions

aws/components/bastion/state.ftl, aws/components/cache/state.ftl, aws/components/computecluster/state.ftl, aws/components/datapipeline/state.ftl, aws/components/db/state.ftl, aws/components/ec2/state.ftl, aws/components/ecs/setup.ftl, aws/components/ecs/state.ftl, aws/components/efs/state.ftl, aws/components/es/state.ftl, aws/components/filetransfer/state.ftl, aws/components/lambda/state.ftl, aws/components/lb/state.ftl
Changes the reference value provided for security groups provided the networkacl role. The security group will now be provided as the resource Id instead of the evaluated output provided by getExistingReference
When linking between two components in the same deployment unit the references returned were of the groupId for an existing deployment. As a result of this the deployment would fail if the group ids changed during a deployment or wouldn't return correctly in a new deployment
Tested locally on a development deployment
=> fix(networkacl): use the id instead of existing ref for lookups

awsdiagrams/services/ecs/id.ftl
Minor fix to the diagram service mapping for the ECS component type 
Was set to the EC2 component which meant that ecs component types wern't being mapped to the ecs service diagram class and the ec2 components were using the wrong class 
Tested locally
=> fix: diagram mapping for ecs

aws/inputsources/shared/masterdata.ftl, aws/masterData.json
Minor fix to set the description for service linked roles to align with the description assigned to the default service linked roles created by AWS. 
This allows for cloudformation to "create" the service linked roles and to to take over roles which have already been created in an account. This is important as service linked roles in most cases are automatically created by AWS and can't be easily deleted. 
=> fix: add descriptions to service linked roles

aws/components/ecs/setup.ftl, aws/components/ecs/state.ftl, aws/inputsources/shared/masterdata.ftl, aws/masterData.json, aws/services/ec2/resource.ftl, aws/services/ecs/resource.ftl
Adds initial support for compute providers as part of the ecs host in line with https://github.com/hamlet-io/engine/pull/1442 
This initial support only sets the default capacity provider for an ECS host which is used when a capacity provider or launch type have not been explicitly set, which should maintain compatibility with our existing deployments 
By default all ECS clusters will have 3 capacity providers available, FARGATE, FARGATE_SPOT and one based on the EC2 Autoscale group which is provisioned as part of the component. 
The default ComputeProvider uses the EC2 Autoscale group for container placements, this is inline with the standard behaviour we have now. Some extra ComputeProvider profiles have been included ( fargate, fargate-add-spot, fargatespot ) have been added to show …
=> feat: add compute provider support to ecs host

aws/components/bastion/setup.ftl, aws/components/network/state.ftl
Update setup macro lookups which use layer data to support configuration data provided by composite object building added in https://github.com/hamlet-io/engine/pull/1448 
Layers are now defined using the composite object process for documentation and validation
Tested locally
=> refactor: align setup macros with layer data changes

aws/components/lambda/setup.ftl, aws/modules/cloudwatchslack/module.ftl
AWS implementation of https://github.com/hamlet-io/engine/pull/1456 
Also includes a reference module `alarmslack` which uses this feature to provide a shared cloudwatch alarm -> slack notification service. This setup has been used across a number of products and can now be loaded as a module
Also includes a reference module 
Allows for images built and hosted from external services to be included as part of the hamlet deployment process
Tested locally
=> Lambda external url

aws/components/apigateway/setup.ftl
Makes the base path mapping deployment in an apigateway depend on the base stage deployment
When deploying a complex stage which includes access logging setups and extra required resources the basepath mapping will be deployed before the stage is deployed. This causes an error during the deployment. 
Tested on local template generation
=> fix(apigateway): fix new deployments without stage

aws/components/apigateway/setup.ftl, aws/services/waf/resource.ftl
Make waf association dependent on the stage 
Required for deployments where the stage takes time to deploy
Tested locally
=> fix(apigateway): waf depedency on stage

aws/inputsources/shared/masterdata.ftl, aws/masterData.json
Add a lifecycle rule for WAF logs in line with other logs in the operations bucket.
By default, WAF logs are now stored in the ops bucket so they need to be lifecycled like other operational logs.
=> feat: WAF logs lifecycle rule

aws/components/bastion/setup.ftl, aws/components/computecluster/setup.ftl, aws/components/ec2/setup.ftl, aws/components/ecs/setup.ftl, aws/inputsources/shared/masterdata.ftl, aws/masterData.json, aws/services/ec2/resource.ftl
aws implementation of  https://github.com/hamlet-io/engine/pull/1470 
- Supports configuration of patching schedule and updates in solution 
- Moves the patching process to an init script which allows for failing the instance init process if the patching fails
- Includes update log in cloudwatch log forwarding
Provides user control to the patching process and also provides better error handling when there are issues with patching. I.e. fail the instance startup when patching can't be applied 
Tested locally
=> feat: patching via init script

aws/services/ec2/resource.ftl
Implements https://github.com/hamlet-io/engine/pull/1471  and also adds process suspension during cloud formation updates 
When cloudformation applies updates to an autoscaling group it will scale the cluster to meet the configuration parameters in the template ( min, max desired ) If other scaling events are triggered during the update the cfn stack becomes stuck in the UPDATE_IN_PROGRESS stage until it times out ( around 1-2 hours ). This is really difficult to balance as the roll back takes the same amount of time 
Suspending services which can cause instance count changes during cloudformation updates is the recommended approach to fixing this 
https://aws.amazon.com/premiumsupport/knowledge-center/auto-scaling-group-rolling-updates/ 
Tested locally
=> feat: autoscale replacement updates

aws/modules/consolidatelogs/module.ftl
Some minor fixes to the consolidate logs module 
- Update permissions required by lambda to refeed the kinesis firehose 
- Extend timeout and memory allocation on lambda to allow for extended processing 
- Predefine lambda log processor cloudwatch log group and set a no foward profile on the lambda to avoid infinite loops  
- Update description 
Fixes from testing deployment 
Tested locally
=> module: consolidatelogs lambda fixes

aws/components/baseline/state.ftl, aws/components/datafeed/setup.ftl, aws/components/s3/state.ftl, aws/modules/consolidatelogs/module.ftl
- Disable log forwarding for the datafeed component
- Determine s3 at rest encryption for a datafeed destination based on the destinations encryption configuration
- Support KMS lookup from baseline data to kms key - This allows for passing the appropriate policy to the data feed 
- Infinite loop prevention 
With our current role implementation the permissions are supplied by the linked resource, as a result of this enabling encryption on the datafeed doesn't necessarily provide the appropriate permissions required to perform encryption on the s3 destination. So instead we need to check the based component for its s3 config 
The KMS lookup is a bit of a weird lookup to allow for the "sibling" components to perform lookups between each other. It relies on the fact that the parent …
=> fix(consolidatelogs): disable log fwd for datafeed

aws/modules/consolidatelogs/module.ftl
Removes the logwatcher support from the consolidatelogs module
We currently have two supported methods for integrating logs with the data feed component 
- Pull Approach - On the data feed you can use the LogWatchers configuration to link to components you want to collect logs from. In this approach the datafeed component needs a link to all components that it wants logs for 
- Push Approach - Using a LogProfile each component creates the log subscription as part of logging components deployment. In this approach you just need to create a logprofile and use this profile for the components which need to log to this datafeed 
From a module perspective the push approach is far more maintainable than the pull approach. 
TEsted locally
=> refactor(consolidatelogs): remove logwatcher support

aws/components/bastion/setup.ftl
Ensure the eip is created as part of an eip subset.
The logic to detect a public network (and hence the need for an eip), did not take into account an eip subset pass. It now explicitly checks for this.
Fixes #179.
=> fix: bastion eip subset

aws/components/baseline/setup.ftl, aws/components/s3/setup.ftl, aws/services/s3/policy.ftl, aws/services/s3/resource.ftl, awstest/modules/s3/module.ftl
- Adds support for bucket replication to external services, including buckets outside of the account 
- Test cases for bucket replication
- Refactor on S3 policy generation to handle bucket details provided as ARN's 
External bucket replication is a common pattern for log consolidation and backups. This allows for a bucket to be defined as a bucket replication destination which isn't part of the hamlet deployment and isn't part of the deployment AWS account 
Tested locally
=> feat(s3): bucket replication to ext services

aws/inputsources/shared/masterdata.ftl, aws/masterData.json
Set the default encryption service for the opsdata bucket to use the S3 SSE encryption service instead of the KMS - CMK method 
The ops data bucket is our logging destination for Load balancer logs which do not support the KMS-CMK encryption method for bucket encryption. They only support the S3 SSE method. Each object can define its own encryption process and if no default method is set load balancers still encrypt data using S3 SSE. This is a known issue with AWS and no know fix 
Tested locally
=> fix(baseline): use s3 encryption for opsdata

aws/inputsources/shared/masterdata.ftl
Minor fix and refactor for the components in the aws master data 
- Updates the NAT Gateway deployment priority to ensure its deployed after the igw 
- Uses the new deployment:Unit formatting to start the migration to the new naming format
When using management contract deployments the unit ordering is defined as part of the solution. Most components use their component priority default, but igw and nat are both gateways, since the nat depends on the igw we need to set a specific priority for the nat. A the moment the deployment run fails when running through the segment components
Tested locally
=> fix: set nat gateway priority for mgmt contract

aws/components/apigateway/setup.ftl, aws/components/cdn/setup.ftl, aws/components/datafeed/setup.ftl, aws/components/lb/setup.ftl, aws/modules/consolidatelogs/module.ftl, aws/services/kinesis/resource.ftl
- Implements https://github.com/hamlet-io/engine/pull/1483 for datafeeds 
- Adds a fixed set of deployment prefixes to the datafeeds created for component specific logging - This ensures account id and full path are always included in the s3 prefix 
- Adds support for the prefix paths in consolidatelogs module
Breaking change: this will change the path for existing log consolidation modules to include the Account Id after the initial prefix 
Removes the risk of collisions when store logs from multiple accounts in a central store 
Tested locally
=> Datafeed based logging deployment prefixes

aws/components/datafeed/setup.ftl
Remove trailing slashes from the user defined bucket prefix for datafeeds
We use a join to create the datafeed s3 prefix which can include deployment specifc paths, if a user defines a trailing / this will be duplicated as part of our prefix generation
Tested locally
=> fix(datafeed): clean prefixes for s3 destinations

aws/components/datafeed/setup.ftl
Silly fix after fixing the prefix formatting
Error logs were being sent to actual logs 
Tested locally
=> fix(datafeed): use error prefix for errors

aws/components/secretstore/id.ftl, aws/components/secretstore/state.ftl, aws/services/secretsmanager/id.ftl, aws/services/secretsmanager/resource.ftl, aws/services/service.ftl
Initial support in aws for the secrets store component 
- Allows components to use the secret store to define generated secrets for system credentials ( root passwords for managed services ) 
- Adds a dummy implementation of a component for the secrets manager secret store which doesn't require any infrastructure to actually create secrets 
- Ref support for resolving secrets in cloudformation templates 
The primary motivation for this PR is to support the generation of admin passwords which are required for services like RDS or amazonMQ which require an initial root user to be defined in the cloudformation template. We currently set a generated password as an epilogue script. which does lead to an interruption to the service while the password is reset 
Tested locally
=> feat(secretstore): secrets manager support

aws/components/apigateway/setup.ftl, aws/components/cache/setup.ftl, aws/components/db/setup.ftl, aws/components/ecs/setup.ftl, aws/components/es/setup.ftl, aws/components/lambda/setup.ftl, aws/components/lb/setup.ftl, aws/components/mobilenotifier/setup.ftl, aws/components/sqs/setup.ftl, aws/components/topic/setup.ftl
AWS implementation of https://github.com/hamlet-io/engine/pull/1490 which allows for metric dimensions to be assigned through component configuration or settings
Note: the current implementation uses the finalEnvironment of a component to determine the settings to use, this isn;t available on all components as some don't support settings
To create custom alerts based on business level metrics
TEsted locally
=> feat(alerts): get metric dimensions from blueprint

aws/services/s3/resource.ftl
Minor fix to the S3 resource lookup Id when using cross account replication to align with the Provider Id value in #169  
Template generation was broken. This change was implemented just after the provider changes were merged so was just a missed timing
Tested locally
=> fix: prodiver id migration cleanup

aws/components/s3/setup.ftl
Only include the necessary policies to allow s3 replication read access to the source bucket if replication is enabled.
Otherwise, the role always gets created even if replication is not configured. It also makes review of the templates more confusing as they contain unnecessary resources.
=> refactor: s3 encryption replication role creation

aws/components/mta/setup.ftl, aws/components/mta/state.ftl, aws/services/ses/id.ftl
Refactor the inbound MTA support to recognise that only one ruleset can be active for an account/region, meaning that it needs to be shared across environments and created at the account level.
Implements hamlet-io/engine#1499
Refactor due to constraints of SES support for receive rule sets.
Local template generation.
=> refactor: inbound mta support

aws/services/dynamodb/policy.ftl
Minor fix to support query and scan permissions for the globaldb component
Query and scan are important parts of the dynamdb permissions when using dynamodb in most application contexts. This provides them to both the consume and produce roles 
Tested on deployment
=> fix(dynamodb): query scan permissions for read access

aws/components/lambda/setup.ftl
Adds the VersionDependencies attribute to the context so that it can be updated as required using extensions
Lambda functions which use the LambdaAttributes extension macro but don't set the VersionDependencies value are failing
Tested locally
=> fix: add lambda attributes to context

aws/components/userpool/state.ftl
A fix to the creation of the userpool UI url which was using the region for a deployment instead of the components region
This fixes an issue where you have a multi region deployment where a component links to a userpool in another region. Since the hosted UI url was using the `region` global variable, this didn't reflect where the userpool was deployed to. Instead we now use the placement region for the userpool component
Tested locally
=> fix(userpool): set userpool region for multi region deployments

aws/services/kms/policy.ftl, aws/services/s3/name.ftl
AWs provider support for https://github.com/hamlet-io/engine/pull/1508 
- Add standard naming for account level s3 buckets 
- Allow for regional KMS key permissions for bucket replication on encrypted at rest buckets 
Supports the use of multi region registry deployments 
Tested locally
=> Account s3 replica

aws/components/ecs/setup.ftl
AWS implementation of https://github.com/hamlet-io/engine/pull/1495
Allows for external images to be provided for ecs tasks or services. The image is pulled from the public repository and copied to the hamlet registry 
Allows for the use of utility docker containers or for images built outside of the product CI/CD pipeline 
Tested locally
=> feat(ecs): external image sourcing

aws/components/cdn/setup.ftl
Adds support for using an external service as a CDN origin. The external service must have 2 attributes defined, FQDN which sets the host name of the origin endpoint and PATH which can be used to define an origin path override 
This allows for external URLs to be routed through a CDN or to allow for the creation of dummy origins used in combination with Lambda@Edge functions
Tested locally
=> feat(cdn): add support for external service origins

aws/components/queuehost/id.ftl, aws/components/queuehost/setup.ftl, aws/components/queuehost/state.ftl, aws/deploymentframeworks/cf/output.ftl, aws/services/amazonmq/resource.ftl, awstest/inputsources/shared/blueprint.ftl, awstest/modules/queuehost/module.ftl
Initial support for the queue host component using AmazonMQ in aws.
he queue host component is intended to support managed queue broker services which offer a platform to host queues as opposed to instances of queues like we have with Sqs already 
Tested locally
=> feat(queuehost): support for rabbitmq as queuehost

aws/components/apigateway/setup.ftl, aws/components/externalnetwork/setup.ftl, aws/components/externalnetwork/state.ftl, aws/services/cw/resource.ftl, aws/services/vpngateway/resource.ftl
Adds support for configuring Cloudwatch alerts on external network connections ( VPN Connections ) as part of the solution deployment 
Includes some minor fixes for alert related code 
Required to monitor the state of a VPN connection which has been having some connection issues 
Tested locally
=> Externalnetwork alerts

aws/components/apigateway/id.ftl, aws/components/datafeed/id.ftl, aws/components/ecs/id.ftl, aws/components/efs/id.ftl, aws/components/mta/id.ftl, aws/components/router/id.ftl, aws/components/secretstore/id.ftl
Updates AWS-specific attributes that are a part of the composite object data model to use the attribute `Types` instead of the singular `Type`
AWS Provider implementation of hamlet-io/engine#1514
Tested successfully alongside corresponding engine PR.
=> Refactor: Composite Object Data Types

aws/components/apigateway/id.ftl
Update sole provider usage of global links variable to use Links `attributeset`
https://github.com/hamlet-io/engine/pull/1502
Local schema generation alongside engine changes
=> refactor: define links as attributesets

aws/components/globaldb/state.ftl, aws/services/dynamodb/policy.ftl
Where a globaldb is defined to have secondary indexes, linking to a globaldb will also grant access to the secondary indexes.
This fix required some refactoring of the dynamodb policy support to correctly support permissions on secondary indexes. The changes were made to be backwards compatible, but this did result in a degree of inconsistency in the ordering of parameters to some methods that previously didn't accept a list of secondary indexes.
=> fix: permission on globaldb secondary indexes

aws/inputsources/shared/masterdata.ftl, aws/masterData.json
Remove the `Enabled` attribute for baseline opsdata and rely instead on the explicit `Enabled` attribute in the configuration data.
As there is now an explicit `Enabled` attribute for `baselinedata` encryption with a default of `false`, there is no need for this attribute to be included in the masterdata.
Removing the explicit value from the masterdata will also mean it is controllable via deployment profiles. At present, the masterdata is incorporated into the blueprint so can only be overridden in the solution and not via a deployment profile.
=> fix: better control of opsdata encryption

aws/services/kinesis/resource.ftl
Broaden encryption policy to cover both logs and errors.
This also avoids issues with passing an object to the s3Encryption functions which expect the prefix to be a string.
=> fix: firehose encryption policy

aws/components/s3/setup.ftl, aws/services/lambda/resource.ftl
Some minor fixes around S3 events triggering lambda 
- Update the S3 event lambda permission configuration to use a formatted Arn rather than a get reference to avoid circular dependencies on the bucket ARN
- Update the resource lookup to determine the lambda Id
- Allow for formatted ARNs in lambda Permissions
template generation was failing 
tested locally
=> fix(s3): s3event to lambda fixes

aws/components/s3/setup.ftl, aws/services/s3/resource.ftl
AWS implementation of s3 inventory reports. Supports using S3 and Baseline data ( baseline buckets ) as destinations
Allows for the generation of S3 bucket listings. Can be used for s3 batch operations or for reporting and auditing 
Tested locally
=> feat(s3): inventory report support

Jenkinsfile, aws/components/s3/setup.ftl, awstest/modules/queuehost/module.ftl, awstest/modules/s3/module.ftl, test/run_aws_template_tests.sh
A collection of changes to aws template testing 
- Move to using hamlet cli commands for all output generation and testing 
- include Junit output in reports and collect it in the jenkins pipeline 
- Fix queuehost output in testing
Makes testing easier and more detailed in how it handles failed results
Tested locally
=> Test run fixes

aws/components/baseline/setup.ftl, aws/extensions/cmk_cloudfront_access/extension.ftl, aws/extensions/cmk_s3_access/extension.ftl, aws/extensions/cmk_ses_access/extension.ftl, aws/inputsources/shared/masterdata.ftl
- AWS implementation of https://github.com/hamlet-io/engine/pull/1533 which adds extension support to the baselinekey component. Initial support is to control the CMK policy which can be defined in extensions like we do for IAM policies. 
- migrates the existing policies with the exception of the root principal over to extensions
- Adds a new extension policy for S3 access when creating Inventory Reports 
Allows for customisable KMS key policies to align with deployment requirements and service integration
Tested locally
=> feat: baselinekey extensions and policy migration

aws/components/s3/setup.ftl, aws/components/s3/state.ftl, aws/services/s3/policy.ftl
Adds the bucket policy required for s3 inventory reports to deliver the reports to the inventory destination bucket
Policy was missing as part of the existing inventory report configuration which meant reports weren't being delivered 
Tested locally and on development deployment
=> feat(s3): adds bucket policy for inventory

aws/extensions/cmk_ses_access/extension.ftl
Updates the permissions SES receives for KMS key access to align with the various recommendations form aws
AWS has a little too much documentation on the KMS policy required for SES 
- The KMS Docs outline the following policy  - https://docs.aws.amazon.com/kms/latest/developerguide/services-ses.html 
- The SES Docs outline a slightly different policy for large email handling - https://docs.aws.amazon.com/ses/latest/DeveloperGuide/receiving-email-permissions.html 
The updated policy puts them together which should in theory be right
Tested locally
=> fix(baselinekey): update permissions for SES

aws/components/apigateway/setup.ftl, aws/components/contentnode/setup.ftl, aws/components/contentnode/state.ftl
AWS provider updates to align with https://github.com/hamlet-io/engine/pull/1537 
Allows for more flexible control over the path attributes and moves to using attribute set for shared config references
Tested locally
=> refactor: migrate to context paths

aws/inputsources/mock/stackoutput.ftl, aws/inputsources/shared/stackoutput.ftl, aws/inputsources/whatif/stackoutput.ftl
AWS implementation of https://github.com/hamlet-io/engine/pull/1538 
Adds AWS support for the whatif provider which combines the mock and composite provider behaviour to work on existing CMDBs
Tested locally
=> feat: whatif input provider

aws/components/apigateway/setup.ftl
Workaround for #237 
Minor fix to allow for a missing path or verb when setting up API GW throttling
Template generation failing
Tested locally
=> fix(apigateway): throttle handling for apigw

aws/modules/no_master_resourcesets/module.ftl, aws/modules/no_master_vpc/module.ftl
Adds two new modules to the AWS provider 
- no_master_vpc - Which disables all VPC related components added by the masterdata
- no_master_resourcesets - Which disables the resource sets added by the masterdata
The AWS master data currently creates a collection of deployments for VPC and resource sets. In simpler deployments these are often not required. These modules simply disable what is added as deployments from the master data. This maintains compatibility with existing deployments
Tested locally
=> feat(modules): add no_master modules

aws/inputsources/shared/masterdata.ftl, aws/masterData.json
Fixes incorrect placement of the lambda function extension attribute in masterdata.
Incorrect placement was discovered through the testing of the validation entrance [here](https://github.com/hamlet-io/engine/pull/1548)
Validates
=> bugfix: relocate configuration attribute in masterdata

aws/components/userpool/setup.ftl, aws/services/cognito/resource.ftl
Adds support for configuring attribute constraints on userpool schema
components.
If not provided the default action is to use the AWS specified defaults
closes https://github.com/hamlet-io/engine-plugin-aws/issues/228
Tested locally
=> feat(userpool): adds constraints for schema

aws/components/sqs/setup.ftl, aws/components/sqs/state.ftl, aws/services/sqs/resource.ftl
Adds support for enabling FIFO queues on SQS queues
- Adds the basic configuration parameter to the CFN resources
- Changing from standard queue to FIFO requires replacement and named
queues must include renaming. So added replace alternatives and naming to handle replacing when there is only the queue resource in the template ( can't remove it since that can make the template empty ) 
- Truncates the queue name to ensure that the special fifo suffix .fifo is always included in the name
Add support for handling different queue ordering processes
closes https://github.com/hamlet-io/engine-plugin-aws/issues/257
Tested locally and on test deployment
=> feat(sqs): ordering configuration for queues

aws/deploymentframeworks/cf/output.ftl, aws/services/ssm/resource.ftl
Adds support for adding parameters to cloudformation templates
The main reason for adding this is to support Public SSM Parameter Store
entries which can only be provided to templates via parameters
Tested locally
=> feat: Cloudformation parameter support

aws/components/baseline/state.ftl
Adds the policy details to allow for inbound links to s3 based data buckets
Allows for inbound links from resources which S3 based components can invoke such as sqs queues which have a single policy document
=> feat(baseline): add invoke inbound policy for data

aws/components/template/setup.ftl
Move to using the virtual hosted s3 url path instead of the path style s3 sytnax which is on the way to deprecation
AWS are planning on deprecating the path syntax for s3 links and move to virtual host paths instead. This also makes the error returned from cloudformation slightly different ( moves from a weird service error to a 403 ) when the file can't be found
Tested locally
=> fix(template): change to virtual hosted s3 path

aws/components/bastion/setup.ftl
Previously in order to configure ip access to a bastion
the configuration was applied via the segment object.
This change aligns the bastion component with other IP
address group implementations on the component in the
solution.
Existing functionality is maintained, but deemed deprecated
Closes hamlet-io/engine#1559
=> refactor: bastion ipaddressgroups on component def

aws/deploymentframeworks/cf/output.ftl, aws/inputseeders/aws/masterdata.json
Support composite templates to be provided via a filename or via the content being directly included. Switch to the content based input variable for composite accounts rather than the filename based variable.
As part of moving to dynamic input loading, reliance on pre-assembled content needs to be removed. This change starts the process by using the `?interpret` builtin internally to avoid use of the `[#include]` directive if the content appears to be freemarker markup.
=> refactor: composite template inclusion

aws/modules/privatebastion/module.ftl
Create a bastion that is only accessible via SSM.
If no possibility of access from outside the vpc is desired, this module disables the bastion that is included in the masterdata and replaces it with a private bastion. The tier specified needs to be private.
=> feat: private bastion

aws/components/bastion/setup.ftl, aws/computetasks/computetask.ftl, aws/extensions/computetask_awscli/extension.ftl, aws/extensions/computetask_awslinux_cfninit/extension.ftl, aws/extensions/computetask_awslinux_cwlog/extension.ftl, aws/extensions/computetask_awslinux_ecs/extension.ftl, aws/extensions/computetask_awslinux_efsmount/extension.ftl, aws/extensions/computetask_awslinux_eip/extension.ftl, aws/extensions/computetask_awslinux_ospatching/extension.ftl, aws/extensions/computetask_awslinux_sshkeys/extension.ftl, aws/extensions/computetask_awslinux_ssm/extension.ftl, aws/extensions/computetask_awslinux_vpc_lb/extension.ftl, aws/extensions/computetask_linux_filedir/extension.ftl, aws/extensions/computetask_linux_hamletenv/extension.ftl, aws/extensions/computetask_linux_scriptsdeployment/extension.ftl, aws/extensions/computetask_linux_userbootstrap/extension.ftl, aws/extensions/computetask_linux_volumemount/extension.ftl, aws/services/ec2/resource.ftl
- Adds compute task definitions and extension implementations to replace the existing InitConfig scripts that we currently use in the AWS provider. 
- Adds  a new task which installs and starts the SSM agent. This is required to make SSM session manager available for ECS hosts 
- Adds a standard userdata script which calls cfn-init and uses cfn-signal to notify cloudformation of the cfn-init status
- Includes a fix to this script to ensure that the script doesn't exit at any failure to allow for quick feedback to cloudformation on the failure of an instance
Mostly covered in https://github.com/hamlet-io/engine/pull/1629  but the idea is to allow for pluggable configuration of instances used as part of components. Extensions also …
=> feat: aws compute task implementations

aws/attributesets/attributeset.ftl, aws/attributesets/aws_computeimage/id.ftl, aws/attributesets/aws_ecs_computeimage/id.ftl, aws/attributesets/aws_operatingsystem/id.ftl, aws/components/bastion/id.ftl, aws/components/bastion/setup.ftl, aws/components/bastion/state.ftl, aws/components/computecluster/id.ftl, aws/components/computecluster/setup.ftl, aws/components/computecluster/state.ftl, aws/components/ec2/id.ftl, aws/components/ec2/setup.ftl, aws/components/ec2/state.ftl, aws/components/ecs/id.ftl, aws/components/ecs/setup.ftl, aws/components/ecs/state.ftl, aws/services/ec2/id.ftl, aws/services/ec2/resource.ftl
- Refactor
Adds support for configuring the AMI image of ec2 based components using
the image source configuration options.
Adds two AWS specific image source attributes to handle more explicit configuration options
- Source:AMI - Allows a user to explicitly define an AMI Id to use at the component level
- Source:SSMParam - Allows the user to define an SSM Parameter that holds the Image Id. The default value for these options is the AWS public parameters which list the latest recommended version of AWS provided AMI Images.
The default behaviour is to use the current AMI Ids defined in the
Region objects
Adds support and migrates all instance bootstrap configuration over to compute tasks to provide modular reusable configuration …
=> feat:  ComputeTask and ImageSource Support

aws/extensions/computetask_awslinux_ecs/extension.ftl, aws/extensions/computetask_awslinux_ssm/extension.ftl, aws/inputseeders/aws/masterdata.json, aws/services/ec2/resource.ftl
- Adds a deployment profile `_awslinux2` will uses the latest aws linux 2 AMI through SSM parameter store and set OS configuration for extensions to use. This can be applied either on components  or layers based on user requirements to migrate ec2 based components to awslinux2
- Updates extensions to support some of the differences between awslinux and awslinux2
- Fixes a bug in the storage setup which was not including block devices
The ECS storage profile has been updated to reflect the update to the AMI storage which now hosts everything on the root volume. If the device is specified in the block devices with a size larger than the ami on initial boot the file system will be resized to fit the size of the volume which …
=> feat: awslinux2 support for ec2 instances

aws/components/bastion/id.ftl, aws/components/bastion/setup.ftl, aws/components/bastion/state.ftl, aws/components/computecluster/id.ftl, aws/components/computecluster/setup.ftl, aws/components/computecluster/state.ftl, aws/components/ecs/id.ftl, aws/components/ecs/setup.ftl, aws/components/ecs/state.ftl, aws/computetasks/computetask.ftl, aws/extensions/computetask_awslinux_cfninit_asg/extension.ftl, aws/services/ec2/policy.ftl, aws/services/ec2/resource.ftl, aws/services/resource.ftl
- Adds support for autoscale lifecycle hooks focussing on the startup process. This is similar to CFN init but handles the startup instances as part of scaling activities. The instance will be started and if a failure occurs or 10 minute timeout the scaling event will terminate the instance and start again
- Adds a default lifecycle hook for startup events with the ability to override that if required.
- Adds IAM policy to allow the instances to query the ASG they belong to and send the event
The primary motivation is to ensure that instances startup correctly with the configuration that has been given to them via cloud tasks. 
Tested locally
=> feat(ec2): adds support for autoscale lifecycles

aws/components/ec2/setup.ftl
fixes the location used to lookup compute tasks for ec2 components
Failing during template generation
Tested locally
- None
- None
- None
=> fix(ec2): compute task lookup location

aws/inputseeders/aws/id.ftl
Ensure masterdata does not trigger layer attribute failures during intermediate passes of config pipeline processing.
Testing of cmdb processing showed layer processing was incorrectly reporting missing attributes.
Local template generation. The test suite has also been run
- Engine - https://github.com/hamlet-io/engine/pull/1663
- None
- None
=> fix: dynamic cmdb loading

aws/components/ecs/id.ftl
Moves provider specific attributes to the provider. Uses the shared prefix to ensure backwards compatibility for existing deployments
Makes the configuration options tidier for the shared provider and removes the need for other providers to handle the aws values 
- https://github.com/hamlet-io/engine/pull/1660
- https://github.com/hamlet-io/engine/pull/1661
- None
- None
=> refactor(ecs): move provider attributes

aws/components/ec2/id.ftl, aws/components/ec2/setup.ftl, aws/extensions/computetask_awslinux_vpc_lb/extension.ftl, aws/extensions/computetask_linux_volumemount/extension.ftl, awstest/inputseeders/awstest/id.ftl, awstest/modules/ec2/module.ftl
- fixes the function call order for compute task lookups
- fixes typos in computetask extensions which are only used in ec2
- adds ec2 base testing to catch this stuff
Fixes issues in the ec2 components and makes sure they don't happen again 
Tested locally and with new test cases 
- None
- None
- None
=> fix(ec2): param options for compute tasks

aws/components/healthcheck/id.ftl, aws/components/healthcheck/setup.ftl, aws/components/healthcheck/state.ftl, aws/services/cw/id.ftl, aws/services/cw/resource.ftl, aws/services/route53/id.ftl, aws/services/route53/resource.ftl, aws/services/service.ftl, awstest/extensions/healthcheckcomplexbase/extension.ftl, awstest/inputseeders/awstest/id.ftl, awstest/modules/healthcheck/module.ftl
Implements simple and complex healthchecks as part of the healthcheck component.
The simple check is performed by Route53 and runs distributed basic HTTP checks against a single endpoint. The check has to be run from at least 3 regions that support healthchecks and uses our standard port configuration to define the configuration of the check. A link to a destination is required for the check to work.
The simple check must be deployed to us-east-1 as cloudwatch metrics are sent to us-east-1 in a similar way to lambda@edge functions, which are run across all regions but metrics are stored in us-east-1 
The complex health check uses CloudWatch canary monitoring which uses lambda to perform scripted synthetic transactions using …
=> feat: adds support for healthchecks

aws/components/computecluster/id.ftl, aws/extensions/computetask_awslinux_vpc_lb/extension.ftl
A context object already [contains a link target](https://github.com/hamlet-io/engine-plugin-aws/blob/78ba39eaf8864744ad26b97b37bd861bae599e73/aws/components/ec2/setup.ftl#L91), so no need to call getLinkTarget method again in the extension.
Fixes template generation for ec2 component with a non-empty Link object.
Tested locally.
- None
- None
- None
=> fix: link processing in awslinux vpx lb extension

aws/components/mta/setup.ftl
To avoid triggering errors on an lg pass for the MTA component (mainly due to the cludgy way we deal with multiple regions right now), wrap setup processing on a deployment unit check. There is nothing to do if not executing the template pass.
Customer deployments blocked.
- None
- None
- None
=> fix: MTA component SES config detection

aws/components/computecluster/setup.ftl, aws/components/ec2/setup.ftl, aws/components/ecs/setup.ftl, aws/components/healthcheck/state.ftl, aws/extensions/computetask_linux_hamletenv/extension.ftl
A set of minor fixes for ec2 and healthcheck 
- Rework the env setup configuration to allow for sourcing the environment and also including it in bashrc so that non-login shells can access the env vars
- Setup defaultPolicies for ec2 components to allow for user scripts to access these features
- Set a monitoring resource on the canary to make it easier to setup alerts
Minor fixes from testing and using in real life
Tested locally
- https://github.com/hamlet-io/engine/pull/1670
- None
- None
=> Various fix

aws/components/adaptor/setup.ftl, aws/components/db/setup.ftl, aws/components/lambda/setup.ftl, aws/components/sqs/setup.ftl
Some minor features/refactors 
- Add support for setting the config as file output as a yaml file instead of json 
- For the db and sqs components use the more specific configuration option as replace templates are only required for template subsets
Yaml support allows for integrating with lambda functions or services which can't be modified for json support
Tested locally
- https://github.com/hamlet-io/engine/pull/1672
- None
- None
=> yaml config support and alternatives 

aws/components/apigateway/setup.ftl, aws/components/lb/id.ftl, aws/components/lb/setup.ftl, aws/components/lb/state.ftl, aws/services/apigateway/id.ftl, aws/services/apigateway/resource.ftl
- adds support for VPC links on apigateways. This allows the apigateway to access backends which are only hosted within a VPC.  A network load balancer can be shared across apigateways but the vpclink can only be defined once per load balancer. So to use this an inbound link from the network load balancer to an apigateway must be configured before an API gateway can link to one of the load balancers port mappings 
- adds support for defining or modifying open api spec as part of a fragment/extension ( https://github.com/hamlet-io/engine/pull/1675 ) 
- Refactors a cleanup script we run as part of load balancer deployments which was running when it didn't need to. 
VPC link allows for APIGateways to be the only public facing …
=> feat: lb vpc link to apigateway

aws/components/ecs/setup.ftl
fixes the selection process for determining when capacity providers can be used. This ensures that the ecs host can update the provider usage without running into dependency issues
Capacity providers have been through a few different updates within hamlet and the AWS cloudformation support. As a result we have some inconsistent usage of the capacity providers which cause issues when updating the ecs solution component. This change ensures that only the latest implementation triggers  services to use capacity providers 
- None
- None
- None
=> fix(ecs): service capacity provider usage

aws/components/computecluster/setup.ftl, aws/components/computecluster/state.ftl
Removes cloudformation wait resources that wern't required in the compute cluster component
Fixes an issue in template generation as the cloudformation service isn't included in the compute cluster 
Regression in #296 
- None
- None
- None
=> fix(computecluster): remove wait resources

aws/components/globaldb/setup.ftl, aws/components/globaldb/state.ftl, aws/services/dynamodb/policy.ftl
- Adds support for enabling streams on dynamo db tables which provide a stream of updates that have been made to the table
- Adds stream read policy for the tables and includes them as part of state if streams are enabled
Extends the feature support between hamlet and whats available in hamlet. Streams are useful for triggering events based on changes to a table
- https://github.com/hamlet-io/engine/pull/1683
- None
- None
=> feat(globadb): support for change streams

aws/components/apigateway/setup.ftl
Fixes the lookup of the certificate authority to use the correct link
Lookup was using the last link in the link target list 
Tested locally
- None
- None
- None
=> fix(apigateway): use correct link for CA lookup

aws/components/computecluster/setup.ftl, aws/components/ec2/setup.ftl, aws/extensions/computetask_awslinux_vpc_lb/extension.ftl
Fixes some bugs from the extension migration for ec2 registration with
load balancers.
- remove an old call to the old config set scripts
- fix ip address group setup for network load balancers
Ec2 instance generation process was failing when using a load balancer 
- None
- None
- None
=> fix(ec2): fix load balancer registration for ec2

aws/components/globaldb/setup.ftl, aws/services/dynamodb/resource.ftl
removes provisioned throughput configuration on secondary indexes if the billing mode is not provisioned
cloudformation was rejecting a deployment where the table was using pay per use billing and the secondary index had provisioned throughput configured 
Tested locally
- None
- None
- None
=> fix(globaldb): handle secondary indexs pay per use

aws/components/ecs/setup.ftl, aws/components/ecs/state.ftl, aws/services/ecs/resource.ftl
fixes issue with output mapping in capacity provider association which was preventing capacity provider usage
Generation and deployment were successful but services couldn't check that the association was in place 
- None
- None
- None
=> fix(ecs): capacity provider association output

aws/components/mobileapp/setup.ftl, awstest/inputseeders/awstest/id.ftl, awstest/modules/mobileapp/module.ftl
Adds support for retrieving a mobile app source bundle from an external source 
Adds basic testing for mobile app component
This provides users with the ability to use their own build processes but integrate with our deployment process.
Part of https://github.com/hamlet-io/engine/issues/1486
Tested locally
- https://github.com/hamlet-io/engine/pull/1686
- None
- None
=> feat(mobileapp): external image source support

aws/components/contentnode/setup.ftl, awstest/inputseeders/awstest/id.ftl, awstest/modules/contentnode/module.ftl
Adds support for providing your own image for contentnodes 
adds basic template generation as a test for the component
Part of https://github.com/hamlet-io/engine/issues/1486 which makes it possible for users to manage their images outsidef ot hamlet 
Tested locally
- None
- None
- None
=> feat: Contentnode image source

aws/components/ecs/setup.ftl
fixes an issue where tasks started through events wern't starting as they didn't have a launch config set.
This configuration was removed as part of the migration to capacity providers, however tasks haven't quite caught up to that yet. 
Tested locally
- None
- None
- None
=> fix(ecs): set launch type on scheduled tasks

aws/components/datapipeline/setup.ftl, awstest/inputseeders/awstest/id.ftl, awstest/modules/datapipeline/module.ftl
- Adds support for pulling a pipeline image from an external url instead of using a push to the registry 
- Adds basic tests for the datapipeline component
https://github.com/hamlet-io/engine/issues/1486 is the main motivation which aims to standardise the way we manage images for components which need them
Tested locally and using tests added in PR 
- https://github.com/hamlet-io/engine/pull/1688
- None
- None
=> feat(datapipeline): support for external image sources

aws/components/lambda/setup.ftl, aws/services/lambda/resource.ftl
Generate a warning and fatal error when the size of the lambda environment approaches and exceeds the AWS limit of 4k.
Fixes #317 
Local template genertaion
- None
- None
- None
=> feat(lambda): check env size

aws/services/s3/policy.ftl
adds a wildcard default  for the s3 list permissions so that sync and list actions work as expected
Using the aws cli s3 sync command was failing when run from a container on a prefix that the container had access to
- None
- None
- None
=> fix(s3): list permissions for s3 buckets

aws/services/lambda/resource.ftl
Reinstates the Variables subobject for lambda function environment configuration which was removed as part of a refactor
In https://github.com/hamlet-io/engine-plugin-aws/pull/320 we removed the Variables section of the configuration it turns out we had a mistake in the structure of the attributeIfContent function when making this decision. The 3rd parameter sets the value if defined and the lambda cloudformation template requires Environment.Variable
Tested locally
- None
- None
- None
=> fix(lambda): revert environment variable refactor

aws/services/lb/resource.ftl
Updates the certificate validation logic to only apply on ports which specifically require a certificate. This prevents failures when a hostname is setup but the certificate isn't required
Template generation was failing when an http redirect was configured on a load balancer which had custom domain logic on one of its port mappings
- None
- None
- None
=> fix(lb): only validate cert when required

aws/components/bastion/setup.ftl, aws/components/bastion/state.ftl, aws/components/computecluster/setup.ftl, aws/components/computecluster/state.ftl, aws/components/ec2/setup.ftl, aws/components/ec2/state.ftl, aws/components/ecs/setup.ftl, aws/components/ecs/state.ftl, aws/extensions/computetask_linux_docker_compose/extension.ftl
- Implements Management ports for all Ec2 based components in the AWS provider. This allows for the use of ports other than ssh for management 
- Adds support for configuring a startup timeout on the ec2 component inline with the other ec2 based components which use auto scale groups 
- Adds a minor feature to symlink the docker-compose install to align with the recommended install location and what is available on the awslinux2 PATH 
Main motivation is for quality of life improvements when working with ec2 instances to make them as flexible as possible
Tested locally
- https://github.com/hamlet-io/engine/pull/1698
- None
- None
=> Management ports timeout

aws/components/userpool/state.ftl
Provides the OIDC issuer url in the state of the user pool. This is specific URL that AWS generates and its used for accessing the OIDC configuration including the .well-known endpoints
This is required for clients that use the well-known endpoint process to find the OIDC details of the userpool and saves having to configure all the different endpoints
- None
- None
- None
=> feat(userpool): add issuer url in state attributes

aws/components/apigateway/state.ftl, aws/components/cdn/setup.ftl, aws/components/cdn/state.ftl, aws/components/filetransfer/setup.ftl, aws/components/filetransfer/state.ftl, aws/components/lb/setup.ftl, aws/components/lb/state.ftl, aws/components/mta/setup.ftl, aws/components/mta/state.ftl, aws/components/serviceregistry/state.ftl, aws/components/userpool/state.ftl
Remove all usage of the `segmentQualifier` global variable.
With input pipeline processing performing qualification, there is no longer a need for component code to explicitly handle qualification.
BREAKING CHANGE: Move any LB port specific certificate configuration to the affected port configuration rather than qualifying it at the LB level.
- https://github.com/hamlet-io/engine/pull/1695
- None
- Refactor solutions to place port specific certificate configuration on load balancers on the individual ports rather than using port qualifiers on the LB level certificate object.
=> refactor!: remove use of segmentQualifier

aws/components/template/setup.ftl, aws/services/secretsmanager/resource.ftl
- adds support for parameters defined as part of the context along with settings 
- makes the KMS key optional on secrets components to align with the cloudformation defaults 
Implement https://github.com/hamlet-io/engine/pull/1701 and to make it easier to implement parameters for template components
- https://github.com/hamlet-io/engine/pull/1701
- None
- None
=> feat: template parameters

.github/workflows/test.yml, aws/components/es/setup.ftl
- Uses the ES_COMPONENT_TYPE for storage profile lookups
- Removes codeontap as the data volume name and replaces it with an easier to understand data volume name
Using the component type has become the standard for typed profiles and now that we have alternate names on the storage profiles we can use this. Updating the data volume also allows for this to be easier to understand
Tested locally
- https://github.com/hamlet-io/engine/pull/1706
- None
- None
=> refactor(es): rename storage profile config

aws/services/secretsmanager/resource.ftl
Aligns the secret string configuration with the CFN schema to allow for generating empty secrets
When creating secrets manager secrets you sometimes want to create empty secrets that you populate manually this allows you to keep all secret content away from the CMDB and allows for different teams to handle creating the secret store vs the secret itself.
Tested locally
- None
- None
- None
=> fix(secretsmanager): make secret string optional

aws/components/bastion/setup.ftl, aws/components/computecluster/setup.ftl, aws/components/ec2/setup.ftl, aws/components/ecs/setup.ftl, aws/extensions/computetask_linux_volumemount/extension.ftl, aws/inputseeders/aws/masterdata.json, aws/services/ec2/resource.ftl
- Uses the context StorageProfile to align with its use in extensions
- Adds support for configuring volume types and Iops on block devices
- Fixes volume state handling in the volume mount extension
- Fixes types in the masterdata to align the configuration schema
fixes #338 
This adds better handling inline with the configuration provided by the component schema. Some properties in the Storage Profile don't appear to have been implemented 
Adds enabled checks on volumes to ensure they are handled as described 
- https://github.com/hamlet-io/engine/pull/1712
- None
- None
=> refactor: volume handling on ec2 instances

aws/components/adaptor/setup.ftl
- Adds a copy script to make asFile settings available in the operationsBucket for use by an adaptor
- Adds template to the supported subsets to allow for resources to be created as part of adaptors
The copy script makes it easy to consume asFile settings from an adaptor 
The template subset makes it possible to generate your own templates based on hamlet resources
- None
- None
- None
=> fix(adaptor): asfile settings handling

.github/workflows/changelog.yml, .github/workflows/package.yml
Adds a the hamlet cli command to inject build details into the code repo this will then be read by the hamlet cli to give detailed info about engine sources
When bundling the source code into a shared container its hard to know where the code came from. Injecting this into the container images allows us to always find the details as we need. This can also be used to inject other information in the future
Tested locally and will be tested with this pipeline 
- None
- None
- None
=> feat: include build details in container image

aws/components/apigateway/setup.ftl, aws/components/cdn/setup.ftl, aws/components/datafeed/setup.ftl, aws/components/datapipeline/setup.ftl, aws/components/db/setup.ftl, aws/components/externalnetwork/setup.ftl, aws/components/gateway/setup.ftl, aws/components/mobilenotifier/setup.ftl, aws/components/objectsql/setup.ftl, aws/components/spa/setup.ftl, aws/components/user/setup.ftl, aws/services/cw/resource.ftl, aws/services/waf/resource.ftl
Replace references to the command line option `region` with references to the `regionId` global variable set in setContext.
There is a mix of use of `region` and `regionId` reflecting the fact that the composite assembly process initialises `region` while
`getContext` populates regionId.
With dynamic loading, references to region need to be made more dynamic so removal of direct references to the input value is the first step in preparing for this.
Once all known uses are modified, the variables used to pass in the layer values will be changed which will hopefully flush out any unidentified uses via null/missing exceptions.
The change is straightforward but the most efficient way to confirm is …
=> refactor: remove direct references to region

aws/components/lb/state.ftl
Catch and handle the condition of a missing routetable link in the load balancer state calculation.
The code currently assumes it has a route table which fails when migrating installations that precede the changes made to the support for network gateways.
Add a default value so the state generation still proceeds, allowing earlier segment level components to be updated.
- None
- None
- None
=> fix(lb): missing route table link

aws/extensions/computetask_awslinux_sshkeys/extension.ftl, aws/inputseeders/aws/masterdata.json
- update the deployment priority of the vpcendpoint to remove security group dependency betwen bastion and vpcendpoints when deleting stacks
- Use arrays for ssh key handling to make it easier to follow
Help with deployment cleanups 
Tested locally
- None
- None
- None
=> fix: minor updates - vpcendpoint and ssh keys

aws/components/ecs/setup.ftl
fixes an issue where the parent profile was looked up instead of the subcomponent for logging and network profiles
regression when profiles were moved under a central function 
tested on local deployment
- None
- None
- None
=> fix(ecs): fix profile lookup for subcomponents

aws/components/sqs/setup.ftl, aws/services/sqs/resource.ftl
Sets a default value for retention parameter of createSQSQueue macro to a maximum value of 1,209,600 seconds (14 days).
Fixes typo in visibilityTimeout parameter name.
Resolves hamlet-io/engine#1228
Tested locally.
- None
- None
- None
=> feat: set larger default value for SQS MessageRetentionPeriod

aws/components/template/setup.ftl
Adds support for additonal outputs based on the IdSuffix value provided for template attributes
Allows for handling multiple outputs as part of template generation
Tested locally
- None
- None
- None
=> feat: support output suffixes on template setup

aws/inputseeders/aws/masterdata.json
- Adds all of the possible legacy account units as ResourceSets within the account deployment group. To support the legacy account setup we use Resource sets but disable the group filter.
- Defines a district for the account deployment group to control filtering of deployments
Allows for the discovery of account units without having to read through the code or copy from existing products
Tested locally
- https://github.com/hamlet-io/engine/pull/1737
- None
- None
=> feat: add all account units

aws/inputseeders/aws/masterdata.json
- sets the cmk resource set to not be a group deployment unit
- 
Template generation was failing as it was checking for cmk that is created during this unit
- None
- None
- None
=> fix: account cmk deployment scope

aws/components/bastion/setup.ftl
Ensure the bastion has been enabled at the segment level before generating an eip for it.
eip was being generated even though the bastion was disabled at the segment level
- None
- None
- None
=> fix: bastion eip

aws/components/lb/setup.ftl, aws/components/lb/state.ftl, aws/services/acm/id.ftl
refactor the certificate and fqdn process for load balancers
This allows for deploying load balancers when domains or certificates have not been defined in a CMDB. When this is the case you can still use the HTTP endpoints which was currently being stopped. 
- None
- https://github.com/hamlet-io/engine/pull/1748
- None
=> refactor: lb cert state

aws/components/cache/setup.ftl, aws/components/db/setup.ftl, aws/components/queuehost/setup.ftl, aws/components/secretstore/state.ftl, aws/services/amazonmq/resource.ftl, aws/services/cache/resource.ftl, aws/services/rds/resource.ftl, awstest/inputseeders/awstest/id.ftl, awstest/modules/apigateway/module.ftl, awstest/modules/cache/module.ftl, awstest/modules/db/module.ftl, awstest/modules/queuehost/module.ftl
Support MaintenanceWindow in AWS RDS
Handle AEST as a timezone in queuehost MaintenanceWindow
Support MaintenanceWindow in AWS cache
Fixes https://github.com/hamlet-io/engine/issues/159
Fixes https://github.com/hamlet-io/engine/issues/1664
Locally
- https://github.com/hamlet-io/engine/pull/1741
- None
- Optionally add MaintenanceWindow specifying the starting block for the maintenance window
=> Add MaintenanceWindow support in AWS RDS

aws/components/cache/setup.ftl, aws/deploymentframeworks/cf/output.ftl, aws/services/ec2/resource.ftl, aws/services/rds/resource.ftl
adds a set of AZ lookup and parameter reference functions which can be used to create the parameters with default values and to reference them in the template that they are being used in
cfnlint doesn't recommended hard coding AZ values in templates. While we use generated templates we should try and comply with what cfn lint says and to allow for other cfn lint tests to pass
Tested on local template generation and with test suite
- None
- None
- None
=> refactor: use paramters for az - cfnlint

aws/components/cdn/setup.ftl, aws/components/lb/state.ftl, aws/services/cf/resource.ftl
- includes protocol information on lb components
- updates the HTTP origin for cloudfront to support http or https origins
- updates the cdn component to support the protocol changes in the resource
Allows for creating CDN frontends for http backends. This is useful when you want to create https endpoints without having to manage certificate generation and creation 
Tested locally
- None
- None
- None
=> feat: add support for http backends on cdn

aws/components/lb/setup.ftl
Handle missing FQDN for LB
Encountered this issue when testing for hamlet-io/engine-plugin-aws#254
Local generation and deployment to AWS
- None
- None
- None
=> fix(lb): handle missing fqdn

aws/components/lb/state.ftl, awstest/modules/lb/module.ftl
Updates the portmapping state to handle hostname configuration on any protocol if it has been provided
On the load balancer the Certificate configuration is also used to determine the hostname used on the port mapping. This is used on load balancer rules as a condition to use the rule which means that it supports both http and https usage. This aligns the this expectation with our implementation
tested locally and test cases update
- None
- None
- None
=> fix(lb): allow hostname config on http and https

aws/components/apigateway/state.ftl
adds handling for domain processing which returns an empty value when looking up the domain
Handles deployments when API domains aren't provided or cannot be found
- None
- None
- None
=> fix: handle empty domain names on api gateway

aws/components/cdn/state.ftl
include the internal fqdn as part of the cdn attributes. This allows for it to be easily found by users from the hamlet cli
When creating DNS records you need both the internal cloudfront provided DNS name along with the primary alias. This allows for you to query these values through the hamlet cli
Tested locally
- None
- None
- None
=> feat(cdn): include internal fqdn in state

aws/components/correspondent/id.ftl, aws/components/correspondent/setup.ftl, aws/components/correspondent/state.ftl, aws/components/firewall/setup.ftl, aws/services/pinpoint/id.ftl, aws/services/pinpoint/policy.ftl, aws/services/pinpoint/resource.ftl, aws/services/service.ftl, awstest/inputseeders/awstest/id.ftl, awstest/modules/correspondent/module.ftl
This PR adds an initial support for AWS Pinpoint component creation as a service for the shared correspondent component.
To support push notifications for mobile applications AWS Pinpoint project needs to be created and its projectID shared with mobile apps and notifications services providers. Also, Amplify requires Cognito setup with identity roles providing the access to AWS Pinpoint project.
Tested locally, on development deployment and with test cases
- hamlet-io/engine#1793
- None
- None
=> Feat aws pinpoint

aws/components/lb/setup.ftl, aws/services/lb/resource.ftl, awstest/modules/lb/module.ftl
- Adds support for configuring the default action on a listener - this aligns with any of the standard rules actions available for the listener rules ( forward, fixed, redirect etc ) 
- Removes the default target group that was included to act as a dummy endpoint and instead sends a fixed response by default 
- Removes the creation of a target group that will never be used within hamlet 
- Allows for integration with template deployments which create their own listener rules and rely on the default for the base actions 
Tested locally and on a development deployment 
- None
- None
- None
=> refactor(lb): support for default rule control

aws/components/baseline/setup.ftl, aws/components/baseline/state.ftl
- Updates the ssh key handling to support the ssh-key format for public certs
- refactors the script formatting to remove escaping requirements
- Adds handling for new ssh keys added to the baseline component
AWS don't appear to support providing PEM files for ec2 key pairs anymore 
formatting updates make it easier to follow what is happening in the script 
- https://github.com/hamlet-io/executor-bash/pull/276
- None
- None
=> fix(baseline): handle aws required ssh key format

aws/components/firewall/setup.ftl, aws/components/network/setup.ftl
- Handles missing network for firewalls when deployment segment resource sets
- Handle missing routetable or networkacls on subnets
Some minor updates around segment level component handling
Tested locally
- None
- None
- None
=> fix(network): handling missing network on segments

aws/components/apigateway/setup.ftl, awstest/modules/apigateway/module.ftl
Remove the addition of a `Tags` property on API Gateway deployment resources.
API gateway deployments report errors due to the presence of the Tags attribute.
Fixes https://github.com/hamlet-io/engine/issues/1800
- None
- None
- None
=> fix: API Gateway deployment tags

aws/components/firewall/setup.ftl, aws/services/networkfirewall/resource.ftl
- Adds generation of a unique sid for statefull tuple rules when they are added
- Handle any port ranges for statefull rules
Template generation failing if sid is missing
Tested locally on test deployment
- None
- None
- None
=> fix(firewall): include sid for statefull rules

aws/components/queuehost/setup.ftl
fixes an invalid reference to a security group id
Template generation would have failed if this routine was called
- None
- None
- None
=> fix(queuehost): reference to wrong sec group id

aws/components/firewall/setup.ftl
- fixes an issue where stateful firewall rules were not being applied to the firewall policy
firewall policy not being applied as expected 
- None
- None
- None
=> fix(firewall): missing reference for stateful rule

aws/components/firewall/setup.ftl, aws/components/firewall/state.ftl
- Adds state for the firewalldestination subcomponent
- Adds setup implementation of firewall destination based on the vpc endpoints offered by the firewall
Implementation of https://github.com/hamlet-io/engine/pull/1803 which defines routing for firewalls in a similar way to gateways 
tested locally
- None
- None
- None
=> feat(firewall): destination route support

aws/components/cache/setup.ftl, aws/components/cache/state.ftl
- fixes the lookup of the zone configuration parameters to align with the use of Parameters for regions
- Adds support for the new .x versions of redis elasticache versions
- Removes defaulting engine versions inside of setup macro and instead relies on the configuration for version being mandatory
Fixes a bug where the zone parameter lookup was looking at the wrong value.
Removing the version defaulting in the setup macro and make it mandatory removes reliance on hamlet maintaining the version
- None
- None
- None
=> fix(cache): zone lookup configuration and version handling

aws/components/firewall/setup.ftl, aws/components/firewall/state.ftl
- fixes an issue where firewall routes were routing asymmetrically and overriding each other.
- Raises an exception if a route for zone endpoint can not be found for the firewall
Routing for firewall traffic not working as expected 
Tested locally and with active deployment with instance connectivity now confirmed
- None
- None
- None
=> fix(firewall): align routes to AZ endpoints

aws/components/bastion/setup.ftl
Fixes an issue where an EIP script was being run if the EIP wasn't required
Autoscaling group for bastion host was failing to complete its lifecylce activity when the bastion is deployed to a private subnet
- None
- None
- None
=> fix(bastion): fix eip allocation

aws/components/federatedrole/setup.ftl
A minor fix for a check for an assignment type of a federated role assignment.
A correct trusted policy statement is required to use federated roles in scenarios like mobile integration with AWS Pinpoint service.
Tested locally.
- None
- None
- None
=> fix: check for assigment type

aws/extensions/computetask_awslinux_cfninit_asg/extension.ftl, aws/extensions/computetask_awslinux_cfninit_wait/extension.ftl, aws/extensions/computetask_awswin_cfninit_asg/extension.ftl
Add cfn-hup support for linux 
Fix bug in cfn-hup support for win asg
Note changes in ASG cause new instance creation in most cases (bypassing requirement for cfn-hup)
Incorporate the cfn-hup support for awswin into awslinux
Locally generated and deployed to AWS (but the functionality testing of cfn-hup limited to confirming updates to scripts)
- None
- None
- None
=> feat(linux): cfn-hup support for linux

aws/components/cdn/id.ftl, aws/components/cdn/state.ftl, aws/components/dnszone/id.ftl, aws/components/dnszone/state.ftl, aws/components/hostingplatform/id.ftl, aws/components/hostingplatform/state.ftl, aws/components/subscription/id.ftl, aws/components/subscription/state.ftl, aws/services/organizations/id.ftl, aws/services/route53/id.ftl, aws/services/service.ftl
Add minimal implementations of `subscription`, `hostingplatform` and `dnszone` components. They support the importing of externally created resources.
While commented out, there is also the start of support for dns entry creation for the CDN component for testing of additional resource groups on components.
Minimal support for associated resource types/services has also been added.
Part of [ADR0007](https://github.com/hamlet-io/architectural-decision-log/blob/main/adr/0007-placement-support.md) implementation.
- https://github.com/hamlet-io/engine/pull/1810
- None
- None
=> feat: new components

aws/components/lb/setup.ftl, aws/services/lb/resource.ftl, awstest/modules/lb/module.ftl
- Adds support for advanced conditions on port mappings mostly around HTTP traffic details
- Updates the condition template syntax to align with the newer conditions requirements
Allows for more complex routing requests on the application load balancers to allow for things like CDN fronting an LB and using an http header to filter access from the CDN vs other locations
Tested locally and with test cases
- https://github.com/hamlet-io/engine/pull/1826
- None
- None
=> feat(lb): support for advanced conditions

aws/components/externalnetwork/setup.ftl, aws/components/gateway/setup.ftl, aws/services/vpngateway/resource.ftl
- Adds support for defining the tunnelinsideCIDR range on VPN connection  tunnels
This configuration is used by some VPN peers to exchange BGP routes between the VPN gateways instead of requiring an IP on the remote network 
- https://github.com/hamlet-io/engine/pull/1840
- https://github.com/hamlet-io/executor-bash/pull/291
- None
- None
=> feat: vpn inside tunnel config

aws/inputseeders/aws/masterdata.json
Adds the s3replica account deployment into the account level resource groups
The s3replica unit wasn't available when running list-deployments on the account district
- None
- None
- None
=> feat: add s3 replica to account deployments

aws/components/lb/setup.ftl
when lbports don't have alerts provide an empty object
Template generation failing on missing alerts
Tested locallly
- None
- None
- None
=> fix(lb): handle missing alerts on lbport

aws/inputseeders/aws/id.ftl, awstest/inputseeders/awstest/id.ftl, awstest/modules/apigateway/module.ftl, awstest/modules/apiusageplan/module.ftl, awstest/modules/apiuser/module.ftl, awstest/modules/bastion/module.ftl, awstest/modules/cache/module.ftl, awstest/modules/cdn/module.ftl, awstest/modules/computecluster/module.ftl, awstest/modules/correspondent/module.ftl, awstest/modules/datapipeline/module.ftl, awstest/modules/db/module.ftl, awstest/modules/directory/module.ftl, awstest/modules/ec2/module.ftl, awstest/modules/ecs/module.ftl, awstest/modules/filetransfer/module.ftl, awstest/modules/firewall/module.ftl, awstest/modules/healthcheck/module.ftl, awstest/modules/lb/module.ftl, awstest/modules/mobileapp/module.ftl, awstest/modules/network/module.ftl, awstest/modules/queuehost/module.ftl, awstest/modules/s3/module.ftl, awstest/modules/service/module.ftl, awstest/modules/sqs/module.ftl, awstest/modules/task/module.ftl, awstest/modules/topic/module.ftl, awstest/modules/userpool/module.ftl
- Adds a cfn-lint default test case in the awstest masterdata
- Adds the testcase to all current test profiles
- Adds arn and naming for resources which are matched on policy
closes https://github.com/hamlet-io/engine/issues/1816 
Tested locally and will be tested in PR
- None
- None
- None
=> feat: enable cfn-lint on all test profiles

aws/components/directory/id.ftl, aws/components/directory/setup.ftl, aws/components/directory/state.ftl, aws/services/ds/resource.ftl, aws/services/route53/id.ftl, aws/services/route53/resource.ftl
- Adds support for resolver endpoints and rules in the route53 service
- Adds support for adding resolver endpoints when deploying a directory component
- Fixes some bugs where missing configuration caused a stack trace
fixes https://github.com/hamlet-io/engine/issues/1824
When deploying an AD directory component the DNS hosting for the AD environment isn't integrated with the default DNS resolver. To use the AD directory you either need to update the DHCP dns options to use the AD servers as the DNS resolvers or manually configure the specific servers you want to use the Ad environment. 
Using the outbound resolvers makes this available for all services on the VPC and removes …
=> feat: add route53 resolver for AD domain

aws/components/lb/setup.ftl, aws/components/lb/state.ftl
- Fixes the naming of the network load balancer target group in state
- Adds subset check for deployment to ensure the target group isn't included in resource sets
Template generation was failing and resource Id was empty
- None
- None
- None
=> fix(lb): target group id lookup

aws/inputseeders/aws/masterdata.json
- renames the ses account deployment unit to sesruleset used to create the default rule set to align with the legacy deployment fragment
fixes https://github.com/hamlet-io/engine/issues/1857
Tested locally
- None
- None
- None
=> fix: ses account deployment unit name

aws/components/mta/setup.ftl, aws/components/mta/state.ftl, aws/services/ses/id.ftl, aws/services/ses/resource.ftl, awstest/inputseeders/awstest/id.ftl, awstest/modules/mta/module.ftl
Add outbound functionality on MTA component to setup ConfigSets for email logging
Relates to https://github.com/gs-dawr/exdoc-mail-aws/issues/55
Locally and deployed to AWS
- https://github.com/hamlet-io/engine/pull/1858
- None
- None
=> feat: outbound mta

aws/components/datafeed/state.ftl, aws/services/cw/resource.ftl, aws/services/kinesis/resource.ftl
- when a delivery stream destination is an S3 bucket, ensure that the encryption configuration aligns with that of the bucket
- name processing log streams to better reflect their function
- correct an issue where creation of log subscriptions in an lg subset was failing because the iam resources needed to access a delivery stream were not being created.
- Template processing was failing
- Log consolidation was failing due to the presence of KMS encrypted objects
- None
- None
- None
=> fix: Kinesis delivery stream S3 permissions

aws/components/gateway/state.ftl, aws/inputseeders/aws/regions.json
Correct defaulting logic to ensure vpc endpoints are defined in all defined zones.
Also add the kinesis firehose vpc endpoints for ap-southeast-2.
The missing value operator was being too greedy resulting in the ignoring of code to detect when vpc endpoints are being created.
- None
- None
- None
=> fix: per AZ vpc endpoints

aws/components/baseline/setup.ftl, aws/components/mta/setup.ftl, aws/components/mta/state.ftl, aws/components/s3/setup.ftl, aws/components/topic/setup.ftl, aws/components/topic/state.ftl, aws/services/sns/policy.ftl
- Moves the topic policy creation from the linking components to the topic component itself
- Adds support for providing a Sid on SNS topic policy statements
- Adds warnings and fatal exceptions for topic links that used the old policy approach
While the SNS topic policy is a separate resource to the topic the policy resource can only be applied to a single topic once. Any further use of the topic policy overrides the existing policy. 
This update moves to defining a single policy on the topic component and requires permissions for topics to be set on the topic through inbound links instead of as part of the component sending data to the …
=> refactor(topic): move sns topic policy to topic

aws/components/datafeed/setup.ftl, aws/services/kinesis/resource.ftl
Add support for appending delimiters to Kinesis records.
When writing to S3, firehose does not include a delimiter by default but does provide a processor to enabled this to occur.
While a lambda processor could add delimiters, it seems cleaner and more consistent to use the delimiter processor.
All delivery streams targetting S3 will now add a linefeed delimiter.
- None
- None
- None
=> fix: kinesis firehose s3 record delimiters

aws/components/ecs/setup.ftl, aws/components/ecs/state.ftl
- Adds support for the aws: prefix when using awsvpc mode as well as supporting the default prefix
When using the aws: prefix for awsvpc mode the template generation fails
Tested locally
- None
- None
- None
=> fix(ecs): support aws prefix for awsvpc

aws/components/ecs/setup.ftl, aws/components/ecs/state.ftl, aws/components/secretstore/id.ftl, aws/components/secretstore/state.ftl, aws/services/ecs/resource.ftl, aws/services/secretsmanager/policy.ftl
- Updates the execution role processing for ECS tasks to support the permissions required to access secret manage secrets
- Adds outbound roles when linking to a secret for read permissions
- Adds the configuration required in Task Definitions to reference secrets
-  Adds policies for Secrets manager secret access
This allows for secret manager secrets to be referenced in task definitions within ECS. When a new task starts up ECS will retrieve the specified secret value and set it as an environment variable 
Tested locally
- https://github.com/hamlet-io/engine/pull/1864
- None
- None
=> feat(ecs): secret injection support

aws/components/apigateway/id.ftl, aws/components/apigateway/setup.ftl, aws/components/datafeed/id.ftl, aws/components/datafeed/setup.ftl, aws/services/kinesis/resource.ftl
- add solution configuration to permit configuration of the use of dynamic partitioning
- check conditions where partitioning should/shouldn't be enabled
- explicitly add line endings to firehose records for the api gateway, removing the need to use delimiters and partitioning if just directing logs to S3
- add config to the API gateway to permit control over the syntax used to format log records (text/json) - this applies to cloudwatch and firehose logs
- set defaults so existing  firehose deployments don't break, noting that partition settings can only be set when a firehose is …
=> feat(kinesis): Finer grained partition control

aws/components/db/setup.ftl, aws/components/db/state.ftl, aws/components/directory/state.ftl, aws/components/queuehost/state.ftl, aws/services/secretsmanager/resource.ftl, awstest/modules/db/module.ftl
- Adds the provider and CMK key id for secrets generated as part of components
- Adds support for create a secrets manager secret as part of the db component build
- Adds support for using different settings for settings based root credentials
- Refactors state routine to add to a standard set of resources, attributes and roles
Adding support for AWS secrets manager allows for deeper integration between AWS services including ECS which has native support for secrets manager integration and allows for easy discovery of secrets when required by teams who need access to the db
Tested locally
- …
=> feat: db secretstore support

aws/components/datafeed/setup.ftl
Add the ability to include the year, month, day and hour in the prefix.
While the time path is added automatically when not using partitioning, it must be explicitly added when partitioning is used.
- None
- None
- None
=> feat(kinesis): Prefix time path control

aws/components/datafeed/setup.ftl
Add ability to explicitly include error type in prefix.
This only applies to the error prefix. For partitioning the error type must be present in the error prefix.
The error type has been put after the time path to maintain consistency with the good data path. Investigations also tend to focus on what happened at a particular time so having the error types after the time path collects all error types under a single point.
- None
- None
- None
=> feat(kinesis): ErrorType in prefix

aws/components/datafeed/setup.ftl
Rework the logic to ensure prefixes end with a trailing slash.
The previous logic generated a double slash which then turns up as a path component in s3.
- None
- None
- None
=> fix(kinesis): double slash in prefixes

aws/services/vpc/resource.ftl
- Adds outputs for key vpc based resources to ensure deployment checks pass for subcomponents
When generating segment level components the VPC route table components weren't creating outputs which meant that none of the resources in the RouteTable subcomponent were considered deployed. This created warnings that could not be resolve by users
Tested locally
- None
- None
- None
=> fix(network): add outputs for key vpc resources

aws/components/apigateway/setup.ftl, aws/components/apigateway/state.ftl
Support subscriptions and retention control on the execution log.
The primary driver for this change is to permit the inclusion of execution logs in the log consolidation process via a log subscription.
Because the api gateway does not permit control over the execution log group name and includes the api id in the name it creates, special logic is required to control log group retention (normally set when creating the log group) and to create log subscriptions on the log group, for instance for log consolidation.
The change creates a pseudo stack for the execution log group and sets its retention according to the operational expiration setting.
In order that subscription processing works the same as if the execution log group …
=> feat(apigateway): Execution Log Control

aws/components/directory/setup.ftl, aws/components/directory/state.ftl
- Allows the use of the username root for directory components to align with legacy deployments
- Uses the username provided to form the id of the secret generated if that is being used
Directory was being replaced when the new Admin credentials were being used
Tested locally and with generated deployment
- None
- None
- None
=> fix(directory): handle the rename of root to Admin

aws/components/baseline/setup.ftl, aws/components/s3/setup.ftl
- Adds support for checking the enabled state of s3 notifications
Required to work with the deployment dependencies that are setup between SNS topic policies and S3 notification configurations
tested locally
- https://github.com/hamlet-io/engine/pull/1873
- None
- None
=> fix(s3): allow for notifications to be disabled

aws/services/ec2/resource.ftl
- Fixes the zone Id used when determining the AWS availability zone to use for an ebs volume
Template generation was creating a template with an invalid parameter lookup
tested locally
- None
- None
- None
=> fix: ebs volume zone lookup

aws/components/lambda/setup.ftl, aws/extensions/cfredirect/README.md, aws/extensions/cfredirect/extension.ftl, aws/services/lambda/resource.ftl
- Adds the ability to include the runId as part of inline code
- Moves the cfredirect extension over to the aws provider
- Adds support for a fixed path when performing redirects
- Sets the deletion policy for lambda versions to retain
The main motivation around these changes is to handle updates to lambda@edge functions that are deployed using inline code.
- Including the run Id in inline zip files ensures that a new version can be created when version on deploy is used
- Moving cfredirect aligns with the extension being for cloudfront/ lambda@edge only
- The fixed path is for redirects between different services where paths might …
=> feat: ensure inline code changes on update

aws/components/s3/setup.ftl
Because of the location of the configuration controlling versioning of the s3 bucket, if versioning is turned on, the bucket will automatically be lifecycled.
To permit versioning without lifecycle management, support a separate versioning attribute.
The Versioning attribute on Lifecycle will be deprecated to avoid lifecycle management as an unwanted side effect of enabling versioning.
- https://github.com/hamlet-io/engine/pull/1884
- None
- None
=> fix: s3 versioning without lifecycle management

aws/components/apigateway/setup.ftl, aws/components/apigateway/state.ftl
- Gets the api id from the cloudformation stack so that it can be found on create actions
- fixes an issue where the wrong id lookup was used on v2 waf lookups
Deployments failing on initial setup as the log group doesn't exist until the api is invoked 
tested locally
- https://github.com/hamlet-io/executor-bash/pull/302
- None
- None
- None
=> fix(apigateway): execution log lookup and waf Id

aws/components/bastion/setup.ftl, aws/components/bastion/state.ftl
- Adds alternative subsets to bring instances down before running an update replace
- Include the Public IP in attributes to easily find the IP for ssh access to the bastion
This allows for the elastic IP allocation startup script to run which  only works when one instance is running. When running some replacements the ASG creates a new instance before the other one can be shutdown 
Tested locally
- None
- None
- None
=> fix(bastion): hanlde replacement for ec2 instances

aws/components/lambda/setup.ftl
- Add the Layers to context to ensure that null detection does not include a value
template generation was failing to deploy template with Hamlet:Null in the layers field
- None
- None
- None
=> fix(lambda): ensure layers is not null

README.md, aws/components/apigateway/id.ftl, aws/components/apiusageplan/state.ftl, aws/components/externalnetwork/setup.ftl, aws/components/gateway/setup.ftl, aws/components/lambda/setup.ftl, aws/components/mobileapp/state.ftl, aws/components/network/setup.ftl, aws/components/sqs/state.ftl
- remove code to handle missing attributes where they are now part of what composite object produces
- use `isPresent` when checking for configured and enabled features
Part of https://github.com/hamlet-io/engine/issues/1894
Not all components have been exercised but expecting the test suite to pick up the less commonly used ones. This will require the prerequisite PR to have been merged,
The bulk of the correction were detected by the extra code in `isPresent()` which reports where it has been called from
so makes it straightforward to identify where remediation is required.
- https://github.com/hamlet-io/engine/pull/1898
- None
- None
=> refactor: removal of implicit Enabled attribute

.github/workflows/release.yml
- Removes the junit reporter to reduce false error reporting due to PR permissions
The reporting tool was raising warnings on PRs as PRs only have write access to repos and can't create new checks that are required by the reporter. 
It also isn't too useful for hamlets testing approach which tests outputs rather than the code itsself
Will be tested as part of PR
- None
- None
- None
=> cd: remove junit reporting from testing pipeline

aws/components/baseline/setup.ftl, aws/components/baseline/state.ftl
- Saves the local ssh private key as an attribute on the baselinekey component
- Adds the private key contents as an attribute on the baselinekey
- Adds the encryption scheme on the private key if required
Allows for providing ssh keys to other components that can decrypt them 
Tested locally
- https://github.com/hamlet-io/engine/pull/1901
- None
- None
=> feat(baseline): add ssh key as an attribute

aws/modules/ssh_bastion/module.ftl, aws/tasks/aws_decrypt_kms_ciphertext/id.ftl, aws/tasks/task.ftl
- Adds a public ssh based bastion module that includes 
- the bastion itself 
- a runbook to open an ssh session using the default baseline ssh key
- a deployment mode to enable the bastion instance
- Adds a task to decrypt kms based cipher text with support for encryption prefixes and base64 encoded content
This is an initial implementation and proof of concept for https://github.com/hamlet-io/engine/pull/1900 to show how they can be used and what is possible with them 
Creating a module of the bastion also allows for it to be easily enabled and disabled 
- https://github.com/hamlet-io/engine/pull/1900
- https://github.com/hamlet-io/engine/pull/1901
- https://github.com/hamlet-io/engine-plugin-aws/pull/493
- None
- None
=> feat: bastion module with ssh runbook

aws/components/db/state.ftl, aws/modules/runbook_rds_pgdump/module.ftl, aws/modules/ssh_bastion/module.ftl
- Adds a runbook module that uses an ssh bastion host to create a pg_dump of a postgres based db component and copy the file to the local machine
- The runbook ensures that the latest postgres client is installed, installs it if not ( for awslinux2) then runs a pgdump and uses ssh(sftp) to copy the file to the local path provided as an input
The primary motivation for this module is to support development teams who want to work from a local copy of a development database when developing new features. This can also be used for scheduled datatbase backup tasks where you don't want to use the AWS provided backups
- https://github.com/hamlet-io/engine/pull/1904
- None
- None
=> feat: runbook module for pg_dump

aws/components/cdn/setup.ftl, aws/services/cf/resource.ftl
- Adds support for setting the connection timeout for an origin
- Adds support for controlling the TLS protocol used for HTTP based backends
Allows for greater control of origin network connections 
- None
- None
- None
=> feat(cdn): add support for origin connection timeouts

aws/components/network/state.ftl, aws/extensions/runbook_get_ec2_ip/extension.ftl, aws/extensions/runbook_get_vpc_id/extension.ftl, aws/modules/runbook_service_console/module.ftl, aws/modules/ssh_bastion/module.ftl, aws/tasks/aws_ec2_select_instance/id.ftl, aws/tasks/aws_ecs_run_command/id.ftl, aws/tasks/aws_ecs_select_task/id.ftl, aws/tasks/task.ftl
A collection of changes to support runbook based access to vpc based resources
- Adds tasks to select from active ec2 intsances and ecs tasks
- Adds the vpcid as an attribute of vpc
- Extends the bastion runbook to incldue a runbook for accessing active instances within the vpc through the bastion as a gateway host
- Adds a new module which adds support for using ecs exec to directly access a running container as a root user
This allows for simple access to all running containers and instances within a deployment without having to go into the AWS console or know the details of running tasks or active instances
- https://github.com/hamlet-io/engine/pull/1908
- https://github.com/hamlet-io/engine/pull/1907
- None
- …
=> feat: extended runbooks for access

aws/components/s3/setup.ftl
- fixes a typo in deploymentMode details lookup used for validation
- Disables validation of S3 replication checking unless we are in the s3 subset
Template generation for subsets was failing and could not be fixed until other deployments completed
Tested locally
- None
- None
- None
=> fix(s3): replication validation checking

aws/modules/baseline/module.ftl, aws/modules/runbook_rds_pgdump/module.ftl, aws/modules/ssh_bastion/module.ftl, aws/tasks/aws_kms_decrypt_ciphertext/id.ftl, aws/tasks/aws_kms_encrypt_value/id.ftl, aws/tasks/task.ftl
- Adds a baseline module that includes runbooks for encrypting and decrypting secrets using the kms key generated as part of the baseline
- fixes some typos in existing runbook modules
- renames the encrypt runbook task to include the service before the action
This allows for migrating the way that operational tasks are performed to runbooks instead of external scripts and allows for these tasks to be used for other purposes in runbooks
Tested locally
- None
- None
- None
=> feat: add baseline encryption module

aws/components/apigateway/setup.ftl, aws/components/bastion/setup.ftl, aws/components/cdn/setup.ftl, aws/components/clientvpn/setup.ftl, aws/components/computecluster/setup.ftl, aws/components/datafeed/setup.ftl, aws/components/ec2/setup.ftl, aws/components/ecs/setup.ftl, aws/components/es/setup.ftl, aws/components/firewall/setup.ftl, aws/components/lambda/setup.ftl, aws/components/lb/setup.ftl, aws/components/mobilenotifier/setup.ftl, aws/components/network/setup.ftl, aws/extensions/cmk_logs_access/extension.ftl, aws/modules/log_encryption/README.md, aws/modules/log_encryption/module.ftl, aws/services/cw/policy.ftl, aws/services/cw/resource.ftl, aws/services/kinesis/resource.ftl, aws/tasks/aws_encrypt_kms_ciphertext/id.ftl, aws/tasks/task.ftl
- Documentation (new or update to existing)
- Adds support accross all components for at-rest encryption of logs stored in CloudWatch Logs
- Adds an extension for the baselinekey component to add the required KMS policy for Cloudwatch to encrypt logs. This is not included by default 
- Adds a module to highlight the configuration required for enabling logging encryption
- Uses the logging profile assigned to the component to control the service
- Adds a task to encrypt a value using AWS KMS 
This …
=> feat(logs): add support for at rest encryption of cw logs

aws/components/cdn/setup.ftl
- Adds logging profile to support setting up logging for waf to cloudwatch
Template generation failing when cloudwatch logging used for WAF
Tested locally
- None
- None
- None
=> fix(cdn): missing logging profile for waf logging

aws/components/backupstore/setup.ftl, aws/components/backupstore/state.ftl, aws/services/backup/resource.ftl
- separate out conditions from targets
- add an "All" target option to support the use case where everything in a solution should be considered as a candidate target.
- remove the specific logic in the AWS Backup service support for adding the resource wildcard so it can be applied in a broader range of cases, and move control of it to the backupstore component.
When adding backup to the baseline module for a customer, the need for more flexibility in the configuration options was exposed.
- https://github.com/hamlet-io/engine/pull/1926
- None
- None
=> refactor(backup): Configuration options

aws/components/globaldb/setup.ftl, aws/components/globaldb/state.ftl
- Add support for monitoring dynamodb tables with cloudwatch alarms
Allows for monitoring tables 
Tested locally
- None
- None
- None
=> feat(globaldb): cloudwatch alarms

aws/components/topic/state.ftl, aws/services/sns/policy.ftl, aws/services/sns/resource.ftl
- Adds role policy support for encrypted topics which require the caller to have KMS access to the key used to encrypt the topic
Publish actions failing when a component attempted to publish to a queue with at rest encryption enabled
Tested locally
- None
- None
- None
=> fix(sns): add support for encrypted topics

aws/extensions/computetask_awslinux_efsmount/extension.ftl
- escaping and freemarker formatting for the efsId that was provided as part of the template script
Script was failing to run on ec2 instances
Tested locally
- None
- None
- None
=> fix: efs mount script formatting

aws/components/s3/setup.ftl, aws/services/s3/resource.ftl
- add ability for an S3 bucket to be included in backups via a link to a backup regime. This results in it receiving the tag associated with the regime.
- remove the limitation on the tags per bucket. There is a limit of 10 tags per bucket object, but a bucket itself can have
up to 50 tags (https://docs.aws.amazon.com/general/latest/gr/aws_tagging.html).
Allow backups to cover S3 buckets in cases where components affected by backups are explicitly targetted.
Local template generation.
The ability to add more than 10 tags per bucket was tested through the console.
- None
- None
- None
=> feat(s3): backup support

aws/components/directory/setup.ftl, aws/components/directory/state.ftl, aws/inputseeders/aws/masterdata.json
- Adds support for forwarding logs from a managed AD directory service to CloudWatch
- Adds directory deployment to aws masterdata for legacy deployment support
Allows for capturing and auditing security events occurring in the managed ad environment
tested locally and on test deployment
- None
- None
- None
=> feat(directory): log forwarding support

aws/tasks/aws_encrypt_kms_ciphertext/id.ftl
- fixes the required paramters for encrypting values with kms as a task
The implementation in runbooks and the python cli were expecting different parameters to what was used in the privder.
Tested locally
- None
- None
- None
=> fix(task): kms encrypt parameters

aws/services/waf/resource.ftl
Add missing geomatch and ipmatch for WAFv2
Recommendation: When WAFv1 ceases being used within Hamlet, should refactor WAF service
Fixes https://github.com/hamlet-io/engine/issues/1932
Locally and deployed
- None
- None
- None
=> fix: ipmatch and geomatch for wafv2

aws/extensions/computetask_awswin_antivirus/extension.ftl
- Removes the isPresent checks as the default configuration creates empty lists and removes the need for checking the presense
Template generation failing with exceptions based on use of isPresent without explicit enabled attribute. In this case the default is empty arrays anyway so no need for an enabled check
Tested locally
- None
- None
- None
=> fix: remove use of isPresent for AV setup

aws/components/baseline/setup.ftl, aws/components/s3/setup.ftl, aws/services/s3/resource.ftl
- uses getReference to get the bucket name for bucket policies
A complicated process was being used to find the bucket name along with a fixed dependency. Using the reference ensures the dependency is met and that cfn_lint is happy
Tested locally
- None
- None
- None
=> refactor(s3): use references for bucket policy

aws/components/bastion/setup.ftl, aws/components/computecluster/setup.ftl, aws/components/datapipeline/setup.ftl, aws/components/ec2/setup.ftl, aws/components/ecs/setup.ftl, aws/components/federatedrole/setup.ftl, aws/components/healthcheck/setup.ftl, aws/components/lambda/setup.ftl, aws/components/user/setup.ftl, aws/services/ecs/resource.ftl, aws/services/iam/policy.ftl
- Documentation (new or update to existing)
- Moves the standard IAM policies from the shared provider to aws
- Adds support for the FullRelativePath and the FullRawRelativePath to handle the move of asFile settings
- Removes the globalAdministratorAccess permission as it shouldn't be used and isn't used in the plugin
- Updates the standardPolices function to use the standard naming for policy resources
- Move ecs container setup from commonApplication to the aws ecs provider
This aligns with the …
=> refactor: iam standard policies and ecs container migration

aws/components/spa/setup.ftl
In order to ensure browsers don't excessively cache the spa config.json file, give it a max-age in s3 which will
flow through CloudFront to the browser.
Because the config.json typically contains the version information displayed by the spa, it needs to be fetched
when new code is loaded to avoid the appearance that no update has ocurr.
- Local template generation to confirm additional switches are added to the script that sync's the config.json.
- Customer deployment once merged
- https://github.com/hamlet-io/engine/pull/1953
- None
- None
=> feat(spa): force max-age for config

aws/components/healthcheck/state.ftl
- Changes the name used for the health check to always include the segment seed and use snippets of each section of the occurrence
When creating instances of the same healthcheck the naming was conflicting between the instances due to using the truncated name
Tested locally
- None
- None
- None
=> fix(healthcheck): add more entropy to naming of health checks

aws/modules/runbook_rds_snapshot/module.ftl, aws/modules/runbook_run_task/module.ftl, aws/tasks/aws_ecs_run_task/id.ftl, aws/tasks/aws_lambda_invoke_function/id.ftl, aws/tasks/aws_rds_create_snapshot/id.ftl, aws/tasks/task.ftl
- Adds invoke lambda function task
- Adds rds snapshot task
- Adds module for rds snapshot to create a snapshot of a linked instance
Continues the migration of run* bash executor scripts into a more standard contract and cmdb based approach
Tested locally
- None
- None
- None
=> feat: add additional runbook tasks and modules

aws/components/lb/id.ftl, aws/components/lb/setup.ftl, aws/services/lb/resource.ftl, awstest/modules/lb/module.ftl
- Adds support for using an application load balancer as a network load balancer fixed target
- Updates healthchecks to support using HTTP or HTTPS protocol when using TCP as the target protocol
This is an awsism for load balancing and is useful when you need some advanced networking features such as 
- Private Link sharing of applications between VPCS 
- Static IP Addresses for application load balancers ( NLB gets fixed IP's assigned to them ) 
See details on why here https://docs.aws.amazon.com/elasticloadbalancing/latest/network/application-load-balancer-target.html 
Tested locally
- None
- None
- None
=> feat(lb): add support for alb as a network target

aws/components/cdn/setup.ftl
- Adds a fatal exception to outline that logging can only be enabled if the CDN is deployed to us-east-1. the firehose stream must be in us-east-1
Stops from deployments happening where logs are required but the CDN has already been deployed
- None
- None
- None
=> feat(cdn): add error for wrong logging region

aws/tasks/aws_s3_download_bucket/id.ftl, aws/tasks/aws_s3_empty_bucket/id.ftl, aws/tasks/task.ftl
- Adds support for s3 based runbook tasks for backup and emtpying
Adds standard tasks that can be used in runbooks for backing up and emptying s3 buckets
- None
- None
- None
=> feat: add s3 runbook tasks

aws/components/datavolume/setup.ftl, aws/components/datavolume/state.ftl, aws/extensions/computetask_awswin_volumemount/extension.ftl, aws/extensions/computetask_linux_volumemount/extension.ftl
- Removes support for creating SSM based snapshots of datavolumes 
- Supports zone based filtering defined in https://github.com/hamlet-io/engine/pull/1966
- Updates the compute extensions for ec2 components using datavolumes to allow for zone based filtering
Simplifies the datavolume implementation, and standardises the backup process to align with the backup component
Tested locally
- None
- None
- None
=> refactor(datavolumes: zone based control and remove backups

aws/components/ec2/setup.ftl, aws/services/ec2/resource.ftl
- Add ref output for ec2 instance id when using ec2 component
- Don't replace network interfaces when running replace1/replace2
The ec2 Id can be used in management tasks that are part of other deployments to manage the instance 
Removing the eni from the replacement process preserves the IP addresses used for a given ec2 instance in a zone.
Tested locally
- None
- None
- None
=> feat: ec2 resource outputs and replace updates

aws/components/backupstore/setup.ftl, aws/services/backup/resource.ftl, awstest/modules/backup/module.ftl
- Adds the required resource tag to selection conditions
- Fixes the tag value used to align with our current standard tags
Deployment fails when using tag based conditions as the values aren't quite right. 
Cloudformation doco doesn't reference the format but an error is raised and it is outlined in 
https://docs.aws.amazon.com/aws-backup/latest/devguide/assigning-resources.html 
Tested locally and added test suite
- None
- None
- None
=> fix(backupstore): tag based conditions

aws/components/lambda/setup.ftl, aws/services/iam/resource.ftl
Any role, user or group association should be provided when requesting the creation of the policy rather than being derived from (now removed) information in the policy set.
Inline policies were not being associated with a role.
- None
- None
- None
=> fix(iam): inline policy creation from policy set

aws/components/apigateway/state.ftl
- Documentation (new or update to existing)
If mutual TLS is required for the api, add an attribute to this effect to the state. 
Consumers can use this attribute to drive the logic to facilitate mutual TLS connections.
`hamlet describe-occurrence` requests with and without mutual TLS enabled.
- None
- None
- None
=> feat(apigateway): mutual TLS attribute

aws/services/iam/resource.ftl
Apply a 5% margin of error when calculating policy sizes.
It is unclear exactly what AWS includes in its limit calculations so err on the side of caution when triggering the splitting logic.
- None
- None
- None
=> refactor(iam): limits used for policy splitting

aws/components/certificateauthority/id.ftl, aws/components/certificateauthority/setup.ftl, aws/components/certificateauthority/state.ftl, aws/services/acm/resource.ftl, aws/services/acmpca/id.ftl, aws/services/acmpca/resource.ftl, aws/services/service.ftl, awstest/inputseeders/awstest/id.ftl, awstest/modules/certificateauthority/module.ftl
- Adds service and resources for ACMPCA
- Adds component implementation of the certificate authority using the ACMPCA services
Implementation of https://github.com/hamlet-io/engine/pull/1970 
Creates a managed PKI chain that provides access to the private certificates and the ability to control the full authority chain
- https://github.com/hamlet-io/engine/pull/1970
- None
- None
=> feat(certificateauthority): intial support with ACMPCA

aws/components/secretstore/state.ftl, aws/services/kms/policy.ftl, aws/services/secretsmanager/policy.ftl, aws/services/secretsmanager/resource.ftl
- Adds readwrite role for secrets manager secrets
- Adds additional access restriction on the use of the KMS key for encryption and decryption when using secrets manager
- Adds region to resource to allow for cross region secrets
Read write role to allow for automated access to secrets from components that need to write generated secrets or content
Tested locally
- None
- None
- None
=> feat(secretsmanager): add read write support fo secrets

aws/components/network/id.ftl
- Moves the getSubnet function from global setContext to aws provider
Part of https://github.com/hamlet-io/engine/pull/1978 
Tested locally
- None
- None
- None
=> refactor: network subnet function

aws/components/dnszone/id.ftl, aws/components/dnszone/setup.ftl, aws/components/dnszone/state.ftl, aws/services/route53/id.ftl, aws/services/route53/resource.ftl, aws/services/vpc/resource.ftl, awstest/inputseeders/awstest/id.ftl, awstest/modules/dnszone/module.ftl, awstest/modules/segment/module.ftl
- Adds support for creating Route53 Hosted zones
- Updates dnszone to support network profile configuration to enable vpc based zones
- Adds testing for private hosting
- Adds region attribute to VPC 
Allows for creating private DNS zones within route53 to support split DNS zones
Tested locally
- https://github.com/hamlet-io/engine/pull/1979
- None
- None
=> feat(dnszone): add support for private vpc zones

aws/components/lb/setup.ftl
- ensures the appropriate occurrence is used when linking to static targets
- Adds external configuration check to allow  for forwarding to static targets within the VPC
Template generation failing when using links from subcomponent instances and relying on the local instance for link behaviour 
Using static target forwarding is helpful in situations where you might have fixed IP's but changing instances or multiple target groups are required for a particular service. 
Tested locally
- None
- https://github.com/hamlet-io/engine/pull/1981
- None
=> fix(lb): use suboccurrence for static forwardning

aws/components/ec2/setup.ftl
Support both the Port and LB configuration options on a port
- allows for multiple access methods to a given port depending on the service requirements
Tested locally
- None
- None
- None
=> feat(ec2): support IPAddress groups and LB on same port

aws/tasks/aws_ses_smtp_password/id.ftl, aws/tasks/task.ftl
- Defines a task that generates the required Sig4 signed password used by the SES smtp service
The new password required for SES smtp services is a hash encoded sig4 signature. This is much more complex than the original approach and AWS guidance requires the use of a script like python to handle this. 
Tested locally with cli.
- None
- None
- None
=> feat(task): add ses smtp password generation task

aws/components/ecs/setup.ftl, aws/services/ecs/resource.ftl
- Ensure that subnets is always an array on service definitions
- Ensure that capacity provider weights are numbers
Fixes a minor bug when deploying a service to a single AZ
Tested locally
- None
- None
- None
=> fix(ecs): paramter types for templates

aws/extensions/user_ses_smtp_permissions/extension.ftl, aws/modules/ses_smtp_user/module.ftl
- Adds a module to define a standard SES SMTP
- Includes extension for setting SMTP email permissions
- Includes runbook for getting the SES SMTP password
With updates to the way that SES handles authentication for SMTP the process is now a bit more complicated. This module helps to reduce the complication and make a standardised way to manage SMTP based mail users for SES
Tested locally
- None
- None
- None
=> feat: add SES SMTP user module

aws/components/ecs/setup.ftl
When using singleAZ make sure that the subnets returned are a list
Template generation failing when in single AZ mode
- None
- None
- None
=> fix(ecs): ensure subnets are always treated as an array

aws/services/ec2/resource.ftl
- Uses a list map to get the actual priority as a number
When using CFN init scripts the ordering of tasks was determined by sorting on strings.  This meant that the ordering was based on same values rather than the number order of the priority. 
- None
- None
- None
=> fix(ec2): fix ordering for cfn init commands

aws/modules/cloudwatchslack/module.ftl
Allow for lambda runtime to be set with a parameter for alertslack
alertslack v1.2.0 has changes for python3.9 as the runtime. This is to allow it to be controlled via parameters
Locally
- None
- None
- None
=> feat(alertslack): allow setting runtime with param

aws/components/lambda/setup.ftl
When a new version is created on each deploy, provide control over whether the old versions are deleted or retained.
The default is to retain in line with the previous hard coded value.
The need to delete has become more relevant as versioned lambdas are needed to preprovision lambda instances.
Local template generation. Customer deployments.
- https://github.com/hamlet-io/engine/pull/1989
- None
- None
=> feat(lambda): versioned lambda retention policy

aws/modules/runbook_run_task/module.ftl
- Make it easier to read the outcome of the task
When running the task runbook the JSON output provided by the ecs task was hard to read as it was a compressed JSON output
Tested locally
- None
- None
- None
=> fix: format json content for run task module

aws/components/lambda/id.ftl, aws/components/lambda/setup.ftl, aws/services/lambda/resource.ftl
- Adds support for controlling the message batches for sqs when using lambda event sources
Adds support for controlling the message size, batch maximum wait time and handling individual record failures
Tested locally
- None
- None
- None
=> feat(lambda): sqs batch control

aws/components/s3/setup.ftl
- Fixes an issue where s3 can't validate a notification endpoint because the resource policy isn't applied on the notification endpoint
Handles adding 
Tested locally
- None
- None
- None
=> fix(s3): handle notifications for endpoints already deployed

aws/components/apigateway/id.ftl, aws/components/apigateway/setup.ftl
Support additional model values for the case of IP filtering in combination with a lambda authorizer. Also rename the config attribute to more correctly reflect its purpose in controlling authorization rather than authentication.
When used with a lambda authorizer, the default value of "IP" incorrectly provides an explicit ALLOW rather than relying on it to come from the policy provided by the authorizer. By providing explicit values to be used with the authorizer, the configuration can be validated as appropriate.
- https://github.com/hamlet-io/engine/pull/1995
- None
- None
=> refactor(apigateway): authorization models

aws/components/datafeed/id.ftl, aws/components/datafeed/setup.ftl, aws/components/datastream/state.ftl, aws/services/kinesis/resource.ftl, awstest/inputseeders/awstest/id.ftl, awstest/modules/datafeed/module.ftl
- Adds support for using a kinesis datafirehose as a kinesis data stream consumer
This is an AWS specific implementation which allows you to essentially have a serverless managed consumer of kinesis datastreams using the firehose service and its integration with services like lambda. 
Tested locally and added test cases
- None
- None
- None
=> feat(datafeed): add support for data streams as a source

aws/components/datastream/id.ftl, aws/components/datastream/state.ftl, aws/extensions/cmk_sns_access/extension.ftl, aws/inputseeders/aws/masterdata.json, aws/services/kms/policy.ftl
- Adds KMS support for datastream consumers and producers
- Adds S3 policies for SNS SQS kms access
- Adds SNS kms policy for dealing with encrypted topics
- Fixes an issue in S3 KMS policies which removes the requirement for the ViaService policy
Found during further testing of using encryption for various services
Tested locally and using policy deployments
- None
- None
- None
=> fix(kms): policies for kms encryption from via services

aws/components/lb/setup.ftl, aws/components/lb/state.ftl
- moves to using a component level security group for access control into backends 
- application load balancers have a limit of 5 security group attachments. If you have more than 3 backends defined this will blow the limit ( if you have two listeners http and https, they each get a sec group ) 
Tested locally
- None
- None
- None
=> refactor(lb): use shared security group for backends

aws/components/ec2/setup.ftl, aws/services/ec2/resource.ftl
- Ensures that computer based formatting is used for numbers in ec2 templates
Allows for numbers greater than 999 to be used in startup timeouts and priority for tasks
Tested locally
- None
- None
- None
=> fix(ec2): number formatting for priorities

aws/dynamicvalues/aws_secret/dynamicvalue.ftl, aws/dynamicvalues/dynamicvalue.ftl
- Adds support for providing a reference to a secretstore secret
- Transforms the secret into the appropriate cloudformation ref
This allows for providing sensitive content in solution configuration that is evaluated at runtime and injected when it needs to be. 
This method is available across some components already but requires explicit configuration. Using this approach allows for a more standardised approach that can be used when the user chooses to.
- None
- None
- None
=> feat(dyanmicvalues): add support for aws secrets as dynamic values

aws/components/apigateway/setup.ftl
If backing lambdas are versioned, include the lambda version in the stage variable so the correct version of the lambda is invoked.
Note that due to the format of lambda alias arns, this fix will also work for lambda aliases when introduced.
- None
- None
- None
=> fix(apigateway): reference versioned lambdas

aws/components/lambda/setup.ftl, aws/components/lambda/state.ftl, aws/services/lambda/id.ftl, aws/services/lambda/resource.ftl
When deploying a fixed lambda version, provide the option of a lambda alias to avoid the need to update references when a new version of the lambda is created.
Provisioning is also applied to the alias if configured in order that it moves to the latest version of the lambda.
- simplify deployment sequencing and dependency management
- https://github.com/hamlet-io/engine/pull/2015
- None
- None
- None
=> feat(lambda): lambda aliases

aws/components/ecs/setup.ftl
Permit the lg pass to proceed regardless of whether the ecs cluster has been deployed or not.
At present, the lg pass will fail is the ECS cluster hasn't already been created. In complicated dependency 
scenarios such as those involving log consolidation, it is necessary to run the application lg 
pass before the ECS cluster has been created.
- None
- None
- None
=> refactor(ecs): lg pass handling

aws/components/lambda/setup.ftl
Only check environment size if generating the lambda specific templates - ignore for subsets.
- better contextualise the size error 
- None
- None
- None
=> fix(lambda): size checking

aws/components/db/setup.ftl
Add backups tags to aurora clusters. They are managed differently to other rds database types.
- consistency of implementation
- functionally correct
- None
- None
- None
=> fix(db): aurora cluster backups

aws/components/apigateway/state.ftl, aws/components/cdn/state.ftl, aws/components/lb/state.ftl, aws/services/waf/id.ftl, aws/services/waf/resource.ftl
- Includes the v2 version in WAF resource Ids to allow for CFN to perform migrations of WAF resources when the resource type changes
When updating an existing deployment to use WAF v2 instead of WAF classic CloudFormation couldn't change the Type of a resource with the same Id. This would result in the deployment failing and meant that you had to do a stopstart deployment to perform the migration
Tested locally
- None
- None
- None
=> fix(waf): support v1 -> v2 migrations

aws/modules/baseline/module.ftl
- Adds a baseline runbook used to push images to a registry
This runbook supports pushing images from a local source to a defined image. The runbook supports providing a set of link parameters along with the source image details and references and the image will be pushed to the registry
Tested locally
- None
- None
- None
=> feat(runbook): add push_image runbook for images

aws/components/lb/setup.ftl, aws/components/sqs/setup.ftl, aws/components/topic/setup.ftl, awstest/modules/lb/module.ftl
- Allow for extending queue and topic policies through extensions
- Fixes testing for the lb component to ensure that the lb port is considered deployed. This was changed recently to only treat a target enabled if the actual port has been deployed. 
- Fixes an issue in the Lb component which was attempting to access a global variable instead of using the helper function
Useful for integrating with services that require a specific policy applied or need to add additional security policies around how the resource can be used
Tested locally
- None
- None
- None
=> feat: queue topic permission extensions

aws/extensions/computetask_awswin_cfninit_asg/extension.ftl, aws/extensions/computetask_awswin_cfninit_wait/extension.ftl, aws/extensions/computetask_awswin_hamletenv/extension.ftl, aws/extensions/computetask_awswin_scriptsdeployment/extension.ftl
- Use the powershell new-item command with -Force to handle re-running the cfn-init commands without failure
- Removes the initial directory setup script for windows as it only creates one directory that we no longer need
Noticed during re-runs of cfn-init commands that the directory creation was raising errors. This uses force to create the directory which will handle the existing directory. 
Tested locally
- None
- None
- None
=> fix(computetask): windows directory creation

aws/components/lb/setup.ftl
- Fixes the process used to set the default action for a network load balancer when forwarding traffic
The default action wasn't passed correctly from the port mapping building through to the listener creation
Tested locally
- None
- None
- None
=> fix(lb): action lookup for network load balancer

aws/components/lb/setup.ftl
- Allow for the SSL protocol to be used for network load balancers
- Move the lambda check to ALB only
When using the SSL offload service on NLB template generation would fail to complete
Tested locally
- None
- None
- None
=> fix(lb): protocol checks for nlb

aws/components/lb/state.ftl
- Use a broader permission to allow for the registration process for lambda to alb which requires the lambda allows the connection before it works
Makes it easier to provision the LB and lambda components with the different permissions requirements
tested locally
- None
- None
- None
=> fix(lb): expand permissions for lambda invoke

aws/components/dnszone/setup.ftl, aws/components/dnszone/state.ftl
Updates state support in dnszone to align with what is current available
- Allows for creating a DNS zone without the network profile
- Supports creating the zone then adding the network later
Tested locally
- None
- None
- None
=> fix: support dns zone creation without network

aws/components/apigateway/state.ftl, aws/services/acm/id.ftl
Raise non-stopping fatal error when api gateway domain name does not include at least one dot combines with more general https://github.com/hamlet-io/engine/pull/2008
Fixes https://github.com/hamlet-io/engine/issues/1665
Couldn't see how to set up a failure case to test - any advice
- https://github.com/hamlet-io/engine/pull/2008
- None
- None
=> fix(cert): raise error on invalid FQDN

aws/components/lambda/setup.ftl
- Use the requiredOccurrences function to filter lambda functions when using different deployment:Unit for the subcomponent functions
issue when using multiple deployment:Unit values across the functions under a component. This would cause all of the funcitons to be be included in all deployments
Tested locally
- None
- None
- None
=> fix(lambda): check deployment units on function

aws/components/datafeed/setup.ftl, aws/services/cw/resource.ftl, aws/services/kinesis/policy.ftl
- Adds dependency on the policy for creating the log subscription to ensure that test messages work ok
- Update policy to a broader permissions set on kinesis as advised by AWS support and their doco
IT looks like AWS has made some changes to how the log subscription process behaves which now causes a log subscription deployment to fail if the test message can't get through. After an AWS support case it looks like broader permissions are required to get this going. 
Tested locally and on user deployment
- None
- None
- None
=> fix(cw): update permissions for cw logs to kinesis

aws/components/apigateway/setup.ftl, aws/components/apigateway/state.ftl, aws/components/cdn/setup.ftl, aws/components/cdn/state.ftl, aws/components/spa/setup.ftl, aws/services/cf/id.ftl, aws/services/cf/resource.ftl, awstest/modules/cdn/module.ftl
- Adds support for Cloudfront CachePolicies, Origin Request policies which split cache handling from origin requests to fine tune how the cache is managed
- Adds support for Cloudfront Response Policies which support injecting headers sent back to the client, this includes predefined support for HSTS, CORS and other security protocols
- Adds support for the new subcomponents origin, cache policy and response policy which can be used in complex cdn scenarios to reduce resource usage and complexity
- Cache and Origin request policies were [introduced](https://aws.amazon.com/blogs/networking-and-content-delivery/amazon-cloudfront-announces-cache-and-origin-request-policies/) to provide greater control over what is included in the …
=> feat(cloudfront): complex cdn scenarios

aws/components/ecs/setup.ftl
- Add a skip when the lb port component can not be found
Template generation would fail when a port can't be found
- None
- None
- None
=> fix(ecs): skip lb processing when no lb port

aws/components/network/state.ftl, aws/services/iam/policy.ftl
- Moves to using the more generic getTiers methods which supports occurrences in different district types
- Removes the use of the AppPublicDataPrefix - This has been removed from the engine to reduce the complexity in managing these different prefixes and is also considered a security risk. This was removed from the core engine to save having to migrate the segment level configuration required to use the public data prefix in the first place.
The preference for public data would be to use an explicitly defined S3 bucket for this particular purpose. It makes it easier to understand from a user perspective and reduces panic reporting when a core S3 bucket has some limited public access
Aligns …
=> refactor!: remove use of segmentObject

aws/dynamicvalues/aws_secret/dynamicvalue.ftl
- removes the defaulting behaviour for when a secret dynamic evaluation hasn't worked
Align with the changes to dynamic values in https://github.com/hamlet-io/engine/pull/2042 
Tested locally
- https://github.com/hamlet-io/engine/pull/2042
- None
- None
=> fix: dynamic value setup for aws secrets

aws/services/ecs/resource.ftl
- when using the containerregistry image type and a tag is included the tag is currently being stripped from the image name
- This sets the imageVersion if its not provided when using the registry
Ensures that the correct tag is used for container deployments 
Tested locally
- None
- None
- None
=> fix(ecs): handle container tagging for ecs version

aws/components/cdn/setup.ftl, aws/components/cdn/state.ftl, aws/services/cf/resource.ftl
Ensure the event handler for redirects includes the `Enabled` attribute that is assumed to be present later in the code.
Also ensure the required header configuration flows through to the cache policy and origin objects.
The `Enabled` attribute (with a default of `true`) was introduced in a previous change to permit event handlers to be configured but disabled, and code changed to assume the attribute was present.
However the in-built event handling for domain redirects wasn't updated to reflect the change.
- None
- None
- None
=> fix(cdn): Redirect processing

aws/components/datacatalog/id.ftl, aws/components/datacatalog/setup.ftl, aws/components/datacatalog/state.ftl, aws/services/glue/id.ftl, aws/services/glue/resource.ftl, aws/services/service.ftl, awstest/inputseeders/awstest/id.ftl, awstest/modules/datacatalog/module.ftl
- Adds support for creating datacatalogs using AWS Glue
- Creates resources for the key Glue services for dealing with catalogues
- Database - A collection of tables
- Table - A column based data structure
- Crawler - A service to automatically crawl data for a table
- Connector - A connection to a service that requires extra config
The formatting and layout use a relatively loose schema from hamlet perspective as there are quite a few config options available for both of these options which are best left to the user.
AWS Glue is now used to define and control the databases you can search for in Athena, Being able to discover and create tables for Athena makes it easy to query data stored in S3 …
=> feat(datacatalog): aws implemetation using Glue

aws/services/cw/resource.ftl
- Adds a default option to delete lambda functions when a CloudWatch canary that created it is deleted
This was added into CloudFormation after the initial support for Canary monitors was added, its useful to have and we didn't have other cleanup logic that would interfere.
- None
- None
- None
=> feat(cw): ensure lambda is deleted with canary

aws/extensions/computetask_awswin_cwlog/extension.ftl
- Fixes a missing variable declaration when setting up the cloudwatch agent for windows
template generation was failing when deploying a base windows machine using the aws_win deployment profile
Tested locally
- None
- None
- None
=> fix(windows): logContent setup for windows logging

aws/components/baseline/setup.ftl
Correct the extension/policy logic to work on the subOccurrence rather than the occurrence.
Bucket policy wasn't including permissions for the baseline OAI.
- None
- None
- None
=> fix(s3): oai permissions

aws/components/baseline/setup.ftl, aws/components/s3/setup.ftl, aws/services/s3/resource.ftl
- Adds support for the PublicAccessBlock feature of S3
- Sets the default policy to block, ignore and restrict the use of public S3 buckets
- Only allows public policy to be overridden if public access has been enabled for a s3 component
- Removes component and tier from s3 setup as its no longer used
The primary goal here is to increase security over S3 buckets and to ensure that users of hamlet aren't risking the use of public S3 objects unless they explicitly ask for it.
This also aligns with the changes to AWS S3 bucket creation which now enables this by default. 
- None
- None
- None
=> feat(s3): disable public access by default

aws/components/network/state.ftl
- Add a fall back when a subnet can not be determined
- Updates the error message when network configuration is missing to prevent console buffers from being overloaded.
This allow for other exceptions during the network processing to be exposed. 
Tested locally
- None
- None
- None
=> fix(network): handle missing subnet lookup

aws/components/cdn/setup.ftl
- Use the Cloudformation stack output to determine the CF ID when running an invalidation
When a CF Id has changed and not been reflected in the CMDB the invalidation command doesn't work as it tries to invalidate the wrong ID. Using the CFN stack ensures that its up to date. 
Tested locally
- None
- None
- None
=> fix(cdn): use cloudformation to find cdn id

aws/services/waf/resource.ftl
- Adds support for defining conditional rate based rules in wafv2
- Adds support for using Vendor Managed Rule groups which include detailed rule management from AWS
- Both are controlled as rules as they can have conditions applied to override their usage
AWS Implementation of https://github.com/hamlet-io/engine/pull/2055 
Tested locally
- None
- None
- None
=> feat(waf): add support for more wafv2 rules

aws/components/apigateway/setup.ftl, aws/components/cdn/setup.ftl
Add a default for forwarded headers to avoid `Hamlet:null` being added as a header if no specific config is provided.
While it didn't affect the operation of the policy, including an entry for this header value was unnecessary.
- None
- None
- None
=> fix(cdn): origin request policy headers

aws/components/datacatalog/setup.ftl
- Ensure the glue resources are only created in the standard template
Running an IAM or LG resource group would add the glue resource to their templates
Tested locally
- None
- None
- None
=> fix(datacatalog): add subset filter for resources

aws/components/network/setup.ftl, aws/components/network/state.ftl
Correct the reference to the vpc resource in the DNS resolver to work correctly with legacy vpcs.
Also remove a redundant line of code in the vpc state function.
Ensure continued support for older deployments.
- None
- None
- None
=> fix(network): dns resolver resource references

aws/services/iam/policy.ftl
This change removes the transitional code introduced as part of the move to include raw component ids in  settings paths. 
When settings was switched to using the component raw name, code was added to support a transition from the old paths to the new.
Unfortunately the transitional code did not include the `settings/` prefix at the start of the path (which is added by `getSettingsFilePrefix()`), meaning that the permissions it generated did not align to the previous format.
As a result the raw name based permissions have been the only effective ones for a number of months.
This change has been introduced partly to remove the unused permissions, but mainly in order to reduce the size of iam …
=> refactor(iam): remove transitional settings policy support

aws/components/apigateway/setup.ftl, aws/services/cf/resource.ftl
- remove `Authorization` header from the origin request policy for an API Gateway origin
- detect if the `Authorization` header is required in the cache policy for a cloudfront distribution associated with an API Gateway
Origin request policies cannot contain the "Authorization" header. If required by the origin, it must be included in the cache policy, the headers of which are then automatically included in the origin request.
- None
- None
- None
=> fix(apigateway): origin request policy

aws/components/apigateway/setup.ftl, aws/services/cf/resource.ftl
Switch to using the `allViewer` header behaviour on the origin request policy to get the Authorization header passed through.
This is an AWS suggested workaround. At present the `Authorization` can't be explicitly included in an origin request policy, and equally can't be included in a cache policy where the TTL=0.
- None
- None
- None
=> fix(apigateway): Authorization header passthrough

aws/components/apigateway/setup.ftl
Because the authorization model is converted to upper case when first fetched from the solution configuration, treat any provider prefix as upper case as well.
Add a default statement to the authorization processing to catch any internal error where the value being used is unknown.
- correct handling of provider prefixed values
- robustness of code
- None
- None
- None
=> fix(apigateway): authorization values

aws/components/baseline/setup.ftl, aws/components/db/setup.ftl, aws/components/docdb/setup.ftl
- Uses the expected array evaluation for BASH_SOURCE when generating bash scripts in the db components
The BASH_SOURCE builtin bash environment variable is actually an array of the source files for the script. Using array based lookup for the value ensures the file is right. 
Tested locally
- None
- None
- None
=> fix(db): BASH_SOURCE usage in bash scripts

aws/services/waf/resource.ftl
- Use the WAF Profile from the security profile at all times
- Fix the name for the default rule metric name
- The WAFProfile was being ignored if OWASP wasn't enabled on the WAF configuration
- The default metric would change to the name of the last rule or fail when no rules are present
Tested locally
- None
- None
- None
=> fix(waf): handle WAFProfiles and metric name

aws/components/user/setup.ftl, aws/components/user/state.ftl
- Ensures a unique psuedo stack is generated for each user instead of overriding when there are multiple users in a deploymentUnit
- Remove the SES password generation as the method being used is no longer accepted by SES API endpoints and instead requires Sig4 signing
- Cleans up some of the formatting for generating the bash script
When creating a deployment that has multiple users the pseudo stack for credentials would be overwrriten for each user created 
Tested locally
- None
- None
- The SES User password has been removed and replaced with a runbook/module as password generation is now dependent on the region of SES you are using. 
The Module …
=> fix(user): pseudo stack handling and ses removal

aws/components/mobileapp/setup.ftl
Removes the image filename from the `CODE_SRC_PREFIX` config value for the mobileapp component
The expo publish script appends the image filename when retrieving the image from the registry, leading to the incorrect link and failing the build. It was decided to fix the `CODE_SRC_PREFIX` config value to align it with the previous approach and the config parameter name.
Locally
- None
- None
- None
=> fix(images): remove filename from CODE_SRC_PREFIX config for mobileapp component

aws/components/lambda/setup.ftl
- Environment variables aren't supported for lambda@edge so don't include them
While we did disable them through the default context configuration, it was still easy to inject environment variables with the current process. 
This ensures that environment variables can't be added to the lambda function by directly removing the Environment object
Tested locally
- None
- None
- None
=> fix(lambda): remove env vars for lambda@edge

aws/components/db/setup.ftl
Fix getCWMonitoredResources call, reduce minCount and maxCount since it's scaling ReadInstances not all instances
Needed for HA GeoDB scaling
Local testing (desk check)
- None
- None
- None
=> fix: bugfix for aurora scaling

.github/workflows/release.yml
Update the workflow version to pick up the fix to ensure the edge tag is added correctly to docker images.
Unicycle release was not picking up changes as `edge` tags were not being added to docker builds.
Difficult to test outside of github. Tested immediately following commit.
- None
- None
- None
=> fix: update shared release workflow version

aws/components/db/setup.ftl, aws/components/db/state.ftl, aws/services/kms/policy.ftl, aws/services/rds/id.ftl, aws/services/rds/resource.ftl, aws/services/secretsmanager/policy.ftl, awstest/modules/db/module.ftl
- Implements the Proxy db subcomponent using the RDS Proxy service
- This adds support for the Proxy, TargetGroup and Endpoint services required to fully implement RDS Proxy
- Fixes an issue in secrets manager permissions which didn't support region refs
Implement the proxy definition outlined in https://github.com/hamlet-io/engine/pull/2074
Tested locally includes test suite updates and has been deployed into an environment
- https://github.com/hamlet-io/engine/pull/2074
- None
- None
=> feat(db): add support for RDS Proxies

aws/components/image/setup.ftl, aws/extensions/runbook_image_push_result/extension.ftl, aws/extensions/runbook_registry_destination_image/extension.ftl, aws/extensions/runbook_registry_destination_image_tag/extension.ftl, aws/extensions/runbook_registry_destination_object/extension.ftl, aws/modules/baseline/module.ftl, aws/services/image/resource.ftl
- Align and fix up the image push runbooks based on the changes made in the definition of images
- Fix the baseline module to include version for the image component
- Add backwards compatibility support around the registry vs local naming of image sources
This allows for images to be pushed to an image component using runbooks defined as part of the AWS provider. While implementing the overall Image support the runbooks were skipped from a development perspective so didn't quite align with what was expected
Tested locally
- None
- None
- None
=> fix(image): update image push runbooks

.github/workflows/release.yml, aws/extensions/runbook_registry_destination_object/extension.ftl, aws/modules/baseline/module.ftl, aws/services/image/resource.ftl
- Some minor fixes to the runbook setup for s3 based images
- fixes reference lookups when using the output based storage
Runbook based image uploads were failing to run when working with S3
Tested locally
- None
- None
- None
=> fix(images): output based reference handling

aws/components/baseline/state.ftl, aws/components/s3/state.ftl, aws/services/athena/policy.ftl
- Fixes the formatting of the athena workgroup policy to ensure that it works as expected
- Add support for linking to a baseline data bucket and using the same roles that you can on an S3 bucket
Updating the athena workgroup formatting fixes an issue in the consume policy which prevented querying 
The s3 policy update allows services to access the bucket overall when they need to.
Tested locally
- None
- None
- None
=> fix: athena s3 policy

aws/components/ecs/setup.ftl
- add check for secret links on ec2 containers so that the execution role can be assigned
When using the ECS secrets environment variable integration you need to assign an execution role to the ECS agent so that it can access the secrets. We need to do this for fargate containers but for EC2 tasks this isn't required by default. So we need to ensure that the execution role is added when secrets are found. 
Tested locally
- None
- None
- None
=> fix(ecs): handle secrets on ec2 tasks

aws/services/s3/resource.ftl
- include the DeleteReplicationMarker option for v2 based replication on S3 replication
This is required when using the V2 replication via filters. Set to a fixed value at the moment as it can only be used in limited circumstances and replication requires versioning so the data is still retained. 
Tested locally
- None
- None
- None
=> fix(s3): add delete marker replication handling

aws/components/baseline/setup.ftl
- Fixes the lookup for S3 policy to use the suboccurrence instead of parent baseline occurrence
Bucket policies couldn't be modified using the Extensions processing on baseline buckets
Tested locally
- None
- None
- None
=> fix(baselinedata): policy lookup on suboccurrence

aws/extensions/runbook_image_pull_result/extension.ftl, aws/extensions/runbook_registry_source_container/extension.ftl, aws/extensions/runbook_registry_source_object/extension.ftl, aws/modules/baseline/module.ftl
- Simplifies the names for the runbooks used in the baseline module
- adds a pull image runbook to pull images from the registry as required
Reducing the names to not include baseline explicitly makes it easy to remember/use common runbooks 
Adding the pull image runbook allows for transferring images between environments
Tested localy
- None
- None
- None
=> feat(runbooks): shorter names and pull image

aws/components/ecs/id.ftl, aws/services/ecs/resource.ftl
- Enable container insights for the ECS cluster to add enhanced monitoring for the ECS services running on the cluster
Container insights adds a heap of new monitoring features for containers to keep an eye on them and monitor them. As the containers are generally critical to management of a system we enable this by default
- None
- None
- None
=> feat(ecs): add support for container insights

aws/services/image/resource.ftl
- handle finding the tag for a docker image when a single level name is used on the docker image
When using ?keep_after_last if its not there it returns an empty string instead of the original string. So we need to check that it contains a / before stripping it
Tested locally
- None
- None
- None
=> fix(image): handle single level docker tags

aws/components/apigateway/setup.ftl, aws/components/apigateway/state.ftl, aws/components/cdn/setup.ftl, aws/components/cdn/state.ftl, aws/components/lb/setup.ftl, aws/components/lb/state.ftl, aws/services/kinesis/resource.ftl, aws/services/waf/id.ftl, aws/services/waf/resource.ftl, awstest/modules/apigateway/module.ftl, awstest/modules/cdn/module.ftl
- Removes the option to set the version on WAF configurations
- Defaults all resources to use wafv2 across all implementations of waf
Simplifies the configuration process allows for enabling more of the features available in WAFv2 and aligns with recommended practice from AWS. 
Migrations have been tested successfully from wafv1 to wafv2 without impact on the services so this shouldn't cause any issues with users going forward
Tested locally
- None
- None
- None
=> refactor(waf): remove wafv1 support

aws/services/waf/resource.ftl
Remove redundant version being passed to setupWAFRule, causing failures
Builds of CDN are failing 
Built locally
- None
- None
- None
=> fix: remove version on setupWAFRule call

aws/extensions/lambda_ses_mail_sender_eventlog/extension.ftl, aws/extensions/lambda_ses_mail_sender_notify/extension.ftl, aws/modules/ses_mail_sender/module.ftl
- Adds a module which configures a mail sending service using SES 
- Logging to the Ops Bucket for all send events 
- An email notification service for Complaint or Bounce messages that will be sent to a nominated address 
- SNS/SQS based queue workers for processing the log data
SES doesn't log information about sent emails by default, this adds a process similar to most other AWS services which will deliver events to our ops bucket and also notify for more critical services. 
Tested on active deployment in development
- None
- None
- None
=> feat(module): add ses based mail sender with log

aws/components/mta/setup.ftl, aws/components/mta/state.ftl, aws/services/ses/id.ftl, aws/services/ses/resource.ftl
- Moves from CLI to cloudformation resource for adding the configuration set event destination in the MTA component.
- Adds the MAIL_DOMAIN as an attribute so that it can be used by components to know their expected domain
Removes the use of the CLI and allows for streamlined management of the mta component through cfn
- None
- None
- None
=> refactor(mta): move to using cfn for config set event destination

aws/modules/aws_service_log_db/module.ftl
- Adds the saved SES send event logs into the service log athena table
Aligning with https://github.com/hamlet-io/engine-plugin-aws/pull/712 this would allow for easily querying and searching SES based send events to diagnose emails sent from systems
Tested locally
- None
- None
- None
=> feat(module): add ses send events to service logs

aws/components/mta/state.ftl
- Adds an SMTP_ENDPOINT attribute on the send MTA component to save having to remember or look it up when the SMTP service needs to be used
The current ENDPOINT attribute maps to the standard API service not the SMTP service
Tested locally
- None
- None
- None
=> feat: add smtp endpoint address to send mta

aws/components/cdn/setup.ftl, aws/services/cf/resource.ftl
Add new QueryParamExclude option to access allExcept querystring policy option
Needed to access allExcept querystring policy option
local build
- https://github.com/hamlet-io/engine/pull/2096
- None
- Set QueryParamExclude to true to access allExcept (default = false)
=> feat: add support for allExcept on cachepolicy

aws/extensions/cmk_cloudwatch_access/extension.ftl, aws/inputseeders/aws/masterdata.json, aws/modules/baseline/module.ftl
- Allows the cloudwatch service to access CMKs
- Used for sending alerts via CMK encrypted SNS topics
Aligns with the recommended security practices of encrypting any data at rest where possible including services like SNS
Tested locally
- None
- None
- None
=> feat(baseline): cmk access for cloudwatch service

aws/components/globaldb/state.ftl, aws/components/sqs/state.ftl, aws/components/topic/state.ftl, aws/services/kms/policy.ftl
- Adds KMS permissions for DynamoDB access when the table is encrypted
- Adds handling for missing baseline keys when state is being determined 
- DynamoDb permissions are added for cases when the default Decrypt permissions are disabled but you need to access a dynamoDb Table. The permissions are more restrictive when using the ones provided via the table state 
- Handling of missing baseline keys is for solutions that have been created in the CMDB before running the baseline deployment. Since occurrences are loaded during the baseline deployment setup the baseline keys couldn't be found and caused issues
- None
- None
- None
=> fix: handle cmk based encryption at rest

aws/components/mta/setup.ftl, aws/services/ses/resource.ftl
- Adds SES receive rule for sending bounces on a rules based approach
- Fixes an issue where a stop action wouldn't be added if a topic wasn't found for the SES receive rule
- Fixes an issue with send events that would disable forwarding by default !???
Bounces are used to notify mail senders that an email couldn't be accepted. This reduces email loads as or tells mail servers to back off when under load. 
Tested locally
- https://github.com/hamlet-io/engine/pull/2099
- None
- None
=> feat(mta): Add support for bounces on receive

aws/components/lambda/setup.ftl, aws/components/lb/id.ftl, aws/components/lb/setup.ftl, aws/components/lb/state.ftl
- Adds the ability to control the use of multi value headers/params
- fixes invoke permissions on lb component to support the lb or the tg
ALB -> Lambda by default only supports single headers so when using Set-Cookie headers in responses it doesn't work as the general practice is to provide the same header twice. 
MultiValue support is an lb configuration option which modifies the request received by the lambda to use arrays for headers and params
Tested locally
- None
- None
- None
=> feat(lb): add support for multi value in lb lambda

aws/components/lb/setup.ftl, aws/components/lb/state.ftl
- Adds support for including an array of paths for an lb port mapping
Allows for consolidating load balancer rules that do the same thing across different paths
Tested locally
- https://github.com/hamlet-io/engine/pull/2102
- None
- None
=> feat: add support for multiple paths on lb

aws/components/s3/setup.ftl, aws/services/s3/resource.ftl
Add support for control of the object ownership for the bucket.
By default, no explicit control is provided to be backwards compatible with previous deployments.
- track AWS enhancements
Local generation
- https://github.com/hamlet-io/engine/pull/2104
- None
- None
=> refactor(s3): object ownership support

aws/components/ecs/setup.ftl, aws/services/ecs/resource.ftl
- Adds support for setting CPU/Memory allocation at the task service level
- Adds support for the DependsOn setup that allows for init containers
- Adds readonly root file system support to increase security posture of running containers
Enabling root only file systems requires adding volumes for directories like /tmp. However doing this creates directories owned by root. Running an init container before the actual container lets you align the new volume permissions with what is expected
Tested locally
- https://github.com/hamlet-io/engine/pull/2103
- None
- None
=> feat(ecs): task cpu, depends on, readonly

aws/components/s3/setup.ftl
- Disables the restricted public sharing block rule that only allows sharing for local accounts
The expectation with our public policy is to allow anon access to contents of the bucket. One of the block policies were missed when this was setup so it was still blocking this level of access
Tested locally
- None
- None
- None
=> fix(s3): allow external policy sharing on public

aws/services/waf/resource.ftl
- Adds support for creating rules using the regex pattern set resource and then being able to reference it in a rule
- Adds support for custom block responses ( https://docs.aws.amazon.com/waf/latest/developerguide/customizing-the-response-for-blocked-requests.html ) to control how clients find out about the block that occurred
- This was partially implemented in the migration to wafv2 but a couple of the steps seem to have been missed along the way 
- Custom block responses provide a way to respond to clients in the same format that they would expect for the application or provide them with a way to get in touch if this isn't expected behaviour
Tested locally
- None
- None
- None
=> feat(waf): add support for regex pattern set and custom responses

aws/components/network/id.ftl, aws/components/network/setup.ftl, aws/components/network/state.ftl, aws/services/vpc/resource.ftl
- Adds support for setting rules on the default security group and NACL on a VPC created by hamlet
- Allows for passing a Ref through to a security group and NACL rule
- Fixes the port used for outbound rules in return traffic
AWS VPC's always include a default Security group and NACL which cannot be removed, being able to set base rules on these resources ensures that they can't be used for the wrong purpose
- https://github.com/hamlet-io/engine/pull/2107
- None
- None
=> feat(network): support default sg nacl control

aws/components/image/setup.ftl
When an image component uses the default configuration, it results in a `Source` attribute value of `Local`. Correct the handling of this value in the image setup, and remove the "registry" value which is not supported via the component configuration.
Correctly handle image components using a local registry.
Customer site
- None
- None
- None
=> fix(image): source values

aws/extensions/runbook_registry_source_object/extension.ftl
- fixes the formatting of the s3 path when pulling an image from the registry 
/ not included in the path for putting together the S3 uri
- None
- None
- None
=> fix(image): s3 path when pull image

aws/components/baseline/setup.ftl
Revert back to the provision of an ACL on data buckets, since cloudfront requires this when writing logs to the bucket.
Until AWS fix their own services to align with the object policy they recommend as best case, ACLs are needed to permit access logs to be written to S3.
Customer site
- None
- None
- None
=> fix(baseline): data bucket object ownership

aws/modules/baseline/module.ftl
- Change the default local path for the an image pull to use a full file path as this is required for the image download
The default parameter uses a directory path which causes the AWS boto command to fail
Tested localy
- None
- None
- None
=> fix(baseline): default file path for image pull

aws/services/image/resource.ftl
In order to ensure the tag is included in the image state, and to permit future rationalisation of the attribute used, support the use of either attribute to provide the tag value.
Currently the stack output generated by the executor uses the NAME attribute while the image state code expects the TAG attribute.
Customer site
- None
- None
- None
=> fix(image): include tag state from output

aws/services/image/resource.ftl
Ensure the path used to copy files from a bucket does not include the image specific filename.
At present the image filename is being included in thepath to file to copy, resulting inn no files being copied.
Customer site
- None
- None
- None
=> fix: image copying from registry

aws/components/apigateway/setup.ftl
Check for an image source of `Local` rather than `registry` as that is the value returned by `getOccurrenceImage()`.
Incorrect value checking results in no pregeneration script being generated and hence no definition file being available.
Customer site.
- None
- None
- None
=> fix(apigateway): image source type checking

aws/services/waf/id.ftl, aws/services/waf/resource.ftl
- Using labels applied during rule processing as conditions for subsequent rules
- Override the action of a rule provided by a vendor managed rule set
- Use WAFValue Sets for custom HTTP block responses
- Moves WAF conditions from the AWS engine to the core engine as they are generic and this allows for them to be included in our standard WAF rule schema
- Simplifies the resource mapping for WAF Sets as they aren't used much with the move to WAFv2
The main reason for this PR is to provide support for providing custom responses for block actions on vendoer managed rule sets. 
While overrides are possible on vendor managed rules they only support the basic action override and don't support the extended action options like custom …
=> feat(waf): label matching and vendor overrides

aws/components/baseline/setup.ftl
- Only allow s3:PutObject instead of s3:PutObject*
- Add support for the new region lb logging to use the fixed principal instead of a fixed AWS account
- AWS Security hub benchmark recommends only allowing minimal explicit actions when adding bucket policy for external accounts. Since the LB log forwarded uses an external account the reporting trips up on the current policy 
- Adding the new regions allows for using the new regions if we need to 
Tested locally
- None
- None
- None
=> fix(baseline): permissions for logging

aws/components/baseline/setup.ftl, aws/extensions/s3_cw_log_export_access/extension.ftl, aws/extensions/s3_elb_log_delivery_access/extension.ftl, aws/extensions/s3_log_delivery_access/extension.ftl, aws/inputseeders/aws/masterdata.json, aws/modules/baseline/module.ftl
Handle the simple bucket policy statements via extensions to give greater flexibility as to what gets included. The masterdata reflects the current situation but can be overridden as desired.
Extensions permit more flexibility in what policies are configured on the baseline buckets, and also neatly separate the specific policy rules associated with a given type of access.
Local template generation. Customer deployment post relase.
- None
- None
- None
=> refactor(baseline): bucket policy extensions

aws/components/cdn/setup.ftl
Ensure the creation of all resources is contained within a test for the required unit.
NOTE: while the changes look considerable, the only actual change was to move line 659 to line 59 to ensure all the encompassed code is only executed if the cdn deployment unit is requested. 
Currently extraneous resources will be created in any resourceset based deployment, such as `lg`.
Local template generation. Customer testing will follow once released.
- None
- None
- None
=> fix(cdn): extraneous resources in lg pass

aws/components/apigateway/setup.ftl, aws/components/apigateway/state.ftl, aws/services/policy.ftl
Add support for private APIs, with resource policy control based on vpc endpoints, following the pattern already used for IP address filtering on public APIs.
Consumer VPC endpoints are obtained via inbound links from external services.
Like IP address group support, if no limit is to be placed on where traffic to the API can originate, then an external service with a endpoint value of `_global` (or equivalent) must be provided.
- support new AWS feature
- support more security conscious deployment
- https://github.com/hamlet-io/engine/pull/2115
- None
- None
=> feat(apigateway): private APIs

aws/extensions/runbook_registry_destination_image_tag/extension.ftl
Correct the provision of the destination image when pushing docker tags.
The code was attempting to use a non-existent image attribute resulting in an invalid image path and exceptions in the cli.
Will be tested on site once merged. Customer is actively using the extension.
- None
- None
- None
=> fix: docker image tag extension

aws/components/objectsql/setup.ftl, aws/components/objectsql/state.ftl, aws/services/athena/policy.ftl
- Adds the REF attr to the workgroup creation output
- Updates the policy provided through links to the objectsql component to query athena
The first fix ensures that the objectsql component is considered deployed and the policy updates all for another component to consume the objectsql service 
- None
- None
- None
=> fix(objectsql): permissions state details

aws/inputseeders/aws/masterdata.json
- The cloudtrail deployment requires some configuration at the acct level before it can be used so we should disable it until its needed
Ensures that account deployments work first time
- None
- None
- None
=> fix(account): disable cloudtrail by default

aws/components/bastion/setup.ftl, aws/components/ec2/setup.ftl, aws/components/ecs/setup.ftl, aws/components/federatedrole/setup.ftl, aws/components/user/setup.ftl, aws/services/iam/resource.ftl
- Adds support for handling large iam policies across services that have user defined roles which can grow to hit iam policy limits
- Update the user policy setup to be deployed as part of the user instead of IAM to allow for the policy to be attached as required
- Minor typo fix in IAM service
The lambda component has had support for handling IAM policies which are outside of the policy document size for a little while now and that works as expected. This extends  this to other components which could hit the same limits 
Tested locally
- None
- None
- None
=> feat(iam): extend use of the large policy setup

aws/components/gateway/setup.ftl
Ensure route table ids are unique when creating vpc endpoints.
Where a route table is shared across zones, the current logic generates duplicate ids.
- customer site post release
- 
- None
- None
- None
=> fix(gateway): duplicate route table ids

aws/components/gateway/setup.ftl
Correct a bug introduced by recent changes while attempting to correct duplicate route table entries in vpc endpoints.
The absence of the addition operator meant the code would only work correctly where one route table was expected - ironically the situation used to verify the original change post merge.
- customer site application post merge
- None
- None
- None
=> fix(gateway): route table collection

aws/components/lb/setup.ftl
Provide the ability to control the way in which client IP information will be provided to a target.
The default mirrors the current situation where the lb client is hidden and the lb address is presented.
- https://github.com/hamlet-io/engine/pull/2119
- None
- None
=> feat(lb): client IP control

aws/components/ec2/setup.ftl, aws/components/lb/setup.ftl, aws/services/ec2/resource.ftl
- Add support for referencing an ec2 instance in a fixed target pool
- Adds IP output for ec2 eni interfaces
Simplifies the LB registration process from relying on a scripted process to having the load balancer look after it 
Tested locally
- None
- None
- None
=> feat(ec2): lb fixed target mapping

aws/extensions/vpcendpoint_sns_access/extension.ftl, aws/extensions/vpcendpoint_sqs_access/extension.ftl
Add extensions to permit addition of endpoint policies on vpc endpoints controlling access to SQS queues and SNS topics.
Also tighten the corresponding extension for private api access to only detect API gateway endpoints.
- limit queues/topics accessible from a VPC
- None
- None
- None
=> feat: SQS and SNS endpoint policies

aws/components/gateway/state.ftl, aws/extensions/vpcendpoint_source_access/extension.ftl, aws/services/policy.ftl
- Add an extension to limit access via policy to a component from specific vpc endpoints.
The initial user case is access to an IAM user.
- Add an attribute to a gateway destination to permit the corresponding vpc endpoint ids to be available.
- Modify any policy SID to ensure to meets the character limits.
As the source IP of packets is changed when using privatelinks, adding a condition to limit traffic to be from specified vpc endpoints is more reliable/functional that the use of source IPs. (AWS also requires IP addresses in public ranges).
In the process of testing, it was noted that the character constraints on policy Sids were not begin enforced. The are now title-cased alphanumeric strings. …
=> feat(vpcendpoint): source vpc endpoint extension

aws/components/datafeed/setup.ftl
Include any lambda function processor definitions even if the lambda function isn't deployed.
AWS requires that a lambda processor is configured if the prefix definitions include lambda based partitioning.
To permit the datafeed to be deployed at the solution level before the lambda has been deployed, the lambda processor configuration needs to be included even if the lambda function isn't deployed.
This also adds the necessary iam permissions that will take effect as soon as the lambda function is deployed.
- local template generation with customer cmdb
- deployment to customer post merge
- None
- None
- None
=> refactor(datafeed): undeployed lambda functions

aws/services/ecs/resource.ftl
- Round MaximumMemory when it is calculated
- Recent versions of freemarker have extended their number support and looks like decimal multiplication will return a decimal value now. So round it to the nearest whole number
Tested locally
- None
- None
- None
=> fix(ecs): round max memory when calculated

aws/components/datafeed/setup.ftl
If a datafeed is configured with a processing lambda, expect the lambda to be deployed before the datafeed can be deployed.
The datafeed will not deploy unless the lambda already exists if the prefixes reference partition keys from a lambda function.
- None
- None
- None
=> refactor(datafeed): check for undeployed lambda

aws/components/user/setup.ftl, aws/components/user/state.ftl
- Adds the ability to format user names
- Removes SSH key from baseline as its not required
When deploying user accounts used by actual people the automated names aren't easy to remember, so being able to configure it means you can  control the user naming details
Tested locally
- None
- None
- None
=> feat(user): name format handling

aws/components/firewall/setup.ftl, aws/services/networkfirewall/resource.ftl, awstest/modules/firewall/module.ftl
When selecting the all log types for firewalls only the flow log was being created not the alerts which log when a drop or deny occurs 
- When selecting the all option two log destinations should be created one for the flow logs and one for the alert logs
- None
- None
- None
=> fix(firewall): add both log destinations for all

aws/components/s3/setup.ftl, aws/services/kms/policy.ftl, aws/services/s3/policy.ftl
- When doing cross account replications for items that are encrypted at rest using SSE-KMS you need to provide a new key in the S3 account that can be used
- This update covers the extra permissions and processes that we do
- Adds PutObject permissions into the replication rule to accomodate Multipart uploads
Make secure buckets with SSE replication work to other accounts
Tested locally with active replication and works fine
- None
- None
- None
=> feat: add support for kms replication of objects

aws/components/cdn/setup.ftl, aws/components/lb/setup.ftl, awstest/modules/cdn/module.ftl
- AWS implementation of https://github.com/hamlet-io/engine/pull/2128 
- Adds the same features from #788 into the LB port SubComponent ( was previously only added to the backend component) 
Makes it easy to configure multiple hostname aliases on CloudFront
Tested locally and with test cases. 
- None
- None
- None
=> feat: cdn aliases

aws/components/db/id.ftl, aws/components/db/setup.ftl, aws/services/rds/resource.ftl
- Adds options for provisioned Iops and throughput on rds instances
AWS recently released the new gp3 storage option which provides a better way to manage IOPS on databases without them falling off the cliff when they hit burst balances. This allows for it to be used when required 
Tested locally
- None
- None
- None
=> feat(db): add storage type configuration support

aws/components/topic/state.ftl
- Adds decrypt permissions to the topic permissions policy when encryption at rest is enabled
Decrypt permissions are required for some reason when publishing mesages to SNS
Tested locally
- None
- None
- None
=> fix(topic): kms permissions

aws/components/ecs/setup.ftl, aws/services/ecs/resource.ftl
- Fixes an issue where iam policies split into managed policies aren't assigned to the task role
- Fixes an Id issue where the context id is used for policy naming which might not be unique
Large policies were completely removed from the task role 
Using the container id would create duplicate policies that couldn't be assigned to the managed policy list
tested locally
- None
- None
- None
=> fix(ecs): policy split for ecs tasks

aws/components/user/id.ftl, aws/components/user/setup.ftl
Allows for setting a permissions boundary on a user creation which can be set via the solution. This is generally an enforced value provided through external processes so configuring it makes sense
Permissions boundaries control what permissions can be assigned to a user. They are generally managed externally (i.e. via security policy ) so we make it a configured arn here
Tested locally
- None
- None
- None
=> feat(user): add permissions boundary arn config

aws/components/baseline/setup.ftl, aws/components/s3/setup.ftl, aws/services/s3/policy.ftl, aws/services/s3/resource.ftl
- Updates the existing IAM role used for the s3 object replication so that it can also be used for batch replication tasks
- Adds baseline support for providing a different KMS key when working with cross account replication
When you enable S3 bucket replication only new items are replicated and anything that matches the replication prefix before then isn't replicated. To replicate existing objects you need to use the S3 Batch Operations process to run a batch replication job. This needs an IAM role with very similar permissions to the replication role. So this just tweaks the role to work with both processes 
Tested locally
- None
- None
- None
=> feat(s3): batch replication support

aws/components/correspondent/setup.ftl, aws/services/pinpoint/resource.ftl
The recommended DefaultAuthenticationMethod for APNSChannel and GCMChannel is "TOKEN", which wasn't supported in hamlet
To get the push notifications working for one of our tenant.
The Pinpoint configuration was updated and push notifications are confirmed to be working for two environments and both ios and android platforms.
- hamlet-io/engine/pull/2133
- None
- None
=> feat: support recommended token auth method for Pinpoint channels

aws/components/ecs/setup.ftl
Security group needs to be set for a scheduled tasks running on aws fargate.
Without a security group specified for scheduled tasks running on aws fargate a default one is used which may have not required ingress and egress rules set for a task to access EFS volume.
Locally.
- None
- None
- None
=> fix(ecs): set security group for a scheduled task

aws/components/image/setup.ftl
Adds a default value for tagPatternList for ECR Lifecycle rule set to `["*"]`.
tagPatternList is required when tagStatus is set to tagged and tagPrefixList isn't specified
https://docs.aws.amazon.com/AmazonECR/latest/userguide/lifecycle_policy_parameters.html
Locally
- None
- None
- None
=> fix: add tagPatternList for tagged max count ECR lifecycle rule
